### ISSUE TITLE
-turbo 8000 for Haswell not working

### ISSUE THREAD

**Issue by brockbackups** [Piker-Alpha/ssdtPRGen.sh#108]
https://www.dropbox.com/s/2m0aecsozbra15o/Screenshot%202015-01-01%2014.59.10.png?dl=0

**Comment by Piker-Alpha** [comment]
The limit is hard coded to 6.3 GHz and that is exactly how it should work so this issue is invalid.

**Comment by brockbackups** [comment]
oh ok I guess I misunderstood that we should be using -turbo 8000 for Hasewell CPUs

**Comment by Piker-Alpha** [comment]
No. This argument is only useful when you OC your processor.
