### ISSUE TITLE
i5-3317U, -w 2 states missing, missing Turbo states?

### ISSUE THREAD

**Issue by Unbr8kbal** [Piker-Alpha/ssdtPRGen.sh#112]
add one to the top, 20 states
add one to the bottom, 19 states.
add one to top and bottom, 20 states

Does seem like the bottom state is ever added.

Also i'm missing the turboed states.

**Comment by Unbr8kbal** [comment]
I can email you all my generated .aml files.

**Comment by Piker-Alpha** [comment]
I can't help you without the output of ssdtPRGen.sh so please add it here.

**Comment by Unbr8kbal** [comment]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: i5-3317U!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!

System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz'

ACPI Processor {} Declaration(s) found in DSDT
sed: 1: "s/^[\n]*
Warning
	 Usin ...": unterminated substitute pattern

Warning
	 Using assumed Scope (\_PR) {}:
Generating ssdt.dsl for a 'MacBookAir5,2' with board-id [Mac-2E6FAB96566FE58C]
Ivy Bridge Core i5-3317U processor [0x306A9] setup [0x0604]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1700 MHz)
Number of Turbo States: 9 (1800-2600 MHz)
Number of P-States: 19 (800-2600 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0604 instead of 0x0704)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/michael/Library/ssdtPRGen/ssdt.dsl - 265 lines, 7894 bytes, 48 keywords
AML Output:    /Users/michael/Library/ssdtPRGen/ssdt.aml - 1589 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-e
Do you want to copy /Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by Unbr8kbal** [comment]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: i5-3317U!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!

System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz'

ACPI Processor {} Declaration(s) found in DSDT
sed: 1: "s/^[\n]*
Warning
	 Usin ...": unterminated substitute pattern

Warning
	 Using assumed Scope (\_PR) {}:
Generating ssdt.dsl for a 'MacBookAir5,2' with board-id [Mac-2E6FAB96566FE58C]
Ivy Bridge Core i5-3317U processor [0x306A9] setup [0x0604]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1700 MHz)
Number of Turbo States: 9 (1800-2600 MHz)
Number of P-States: 19 (800-2600 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0604 instead of 0x0704)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/michael/Library/ssdtPRGen/ssdt.dsl - 265 lines, 7894 bytes, 48 keywords
AML Output:    /Users/michael/Library/ssdtPRGen/ssdt.aml - 1589 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-e
Do you want to copy /Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by Unbr8kbal** [comment]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: i5-3317U!
Override value: (-w) Ivy Bridge workarounds, now set to: 3!

System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz'

ACPI Processor {} Declaration(s) found in DSDT
sed: 1: "s/^[\n]*
Warning
	 Usin ...": unterminated substitute pattern

Warning
	 Using assumed Scope (\_PR) {}:
Generating ssdt.dsl for a 'MacBookAir5,2' with board-id [Mac-2E6FAB96566FE58C]
Ivy Bridge Core i5-3317U processor [0x306A9] setup [0x0604]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1700 MHz)
Number of Turbo States: 9 (1800-2600 MHz)
Number of P-States: 19 (800-2600 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0604 instead of 0x0704)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/michael/Library/ssdtPRGen/ssdt.dsl - 265 lines, 7894 bytes, 48 keywords
AML Output:    /Users/michael/Library/ssdtPRGen/ssdt.aml - 1589 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-e
Do you want to copy /Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by Unbr8kbal** [comment]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: i5-3317U!
Override value: (-w) Ivy Bridge workarounds, now set to: 2!

System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz'

ACPI Processor {} Declaration(s) found in DSDT
sed: 1: "s/^[\n]*
Warning
	 Usin ...": unterminated substitute pattern

Warning
	 Using assumed Scope (\_PR) {}:
Generating ssdt.dsl for a 'MacBookAir5,2' with board-id [Mac-2E6FAB96566FE58C]
Ivy Bridge Core i5-3317U processor [0x306A9] setup [0x0604]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1700 MHz)
Number of Turbo States: 9 (1800-2600 MHz)
Number of P-States: 19 (800-2600 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0604 instead of 0x0704)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/michael/Library/ssdtPRGen/ssdt.dsl - 263 lines, 7817 bytes, 48 keywords
AML Output:    /Users/michael/Library/ssdtPRGen/ssdt.aml - 1570 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-e
Do you want to copy /Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by Piker-Alpha** [comment]
Right. Something goes bas when the script tries to determine the used scope. Please e-mail me your DSDT.aml (also check ~/Library/ssdtPRGen.sh is you can find it there with the proper length).

**Comment by Unbr8kbal** [comment]
No disrespect but you don't make it easy to find your email,

Could you please tell me what it is? 

Thank you

**Comment by Unbr8kbal** [comment]
I could only upload photo's so rename this to .aml and it's my dsdt.
![dsdt](https://cloud.githubusercontent.com/assets/1782545/5694352/97733ce2-99a6-11e4-8d84-183f415fa892.jpg)

I wanted to thank you in advance, i really admire that you would help anybody.

**Comment by Piker-Alpha** [comment]
I need your decompiled DSDT and I need that because I don't have the SSDT's that your BIOS/boot loader may include at boot time, or you could use the Beta version of ssdtPRGen (see link below) and zip up: ~/Library/ssdtPRGen/ and e-mail me that instead. My e-mail address can be found in the scripts on line 7:

https://github.com/Piker-Alpha/ssdtPRGen.sh/master/Beta/ssdtPRGen.sh#L7 
https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/ssdtPRGen.sh#L7 

Yes. That makes it a bit harder than usual, perhaps, but you have no idea what people are capable of when it comes to finding solutions for their broken hacks. And since I don't have a help desk… I have to protect myself and my free time a little.

**Comment by Unbr8kbal** [comment]
Hey mate did you get my email?

**Comment by Piker-Alpha** [comment]
No. I checked it (twice) and cannot find anything related to this issue.

**Comment by Unbr8kbal** [comment]
Um:

From:	 Mike G (mikegerlyand@hotmail.com)
Sent:	Monday, 12 January 2015 11:07:35 AM
To:	PikeRAlpha@yahoo.com (pikeralpha@yahoo.com)

Is that the correct email address/

**Comment by Piker-Alpha** [comment]
Yes. I got it.
