### ISSUE TITLE
i5-4590

### ISSUE THREAD

**Issue by buoo** [Piker-Alpha/ssdtPRGen.sh#114]
Hi Pike :)
-------------------------------------------------------------------------------------------------
gDataPath: /Users/francesco/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz'

Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac15,2' with board-id [Mac-FA842E06C61E91C5]
Haswell Core i5-4590 processor [0x306C3] setup [0x0605]
With a maximum TDP of 84 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 3300 MHz)
Number of Turbo States: 4 (3400-3700 MHz)
Number of P-States: 30 (800-3700 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'system-type' may be set improperly (1 instead of 2)         <---- 

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/francesco/Library/ssdtPRGen/ssdt.dsl - 273 lines, 8624 bytes, 47 keywords
AML Output:    /Users/francesco/Library/ssdtPRGen/ssdt.aml - 1771 bytes, 16 named objects, 31 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-------------------------------------------------------------------------------------------------

I got a warning, 
what does it mean and what should I do? 

thanks a lot
Francesco

**Comment by Piker-Alpha** [comment]
The warning means that the used "system-type" property in your IORegistry doesn't match with the target model identifier *iMac15,2). Note that 1 is used for desktop setups like the iMac, 2 for MacBook Pro and MacBookAir models, and 3 for the Mac Pro. This is of course just a warning, which may be wrong when you run ssdtPRGen.sh for another configuration i.e. not the running computer – but please note that some kext actually check this property, so you may want to fix this.

**Comment by buoo** [comment]
Thank you Pike :)
