### ISSUE TITLE
ssdtGen for i3-3110M sates missing?

### ISSUE THREAD

**Issue by microvnhaxor** [Piker-Alpha/ssdtPRGen.sh#117]
i use ssdtGen for i3-3110m 

Override value: (-c) CPU type, now using: Ivy Bridge!
Override value: (-w) Ivy Bridge workarounds, now set to: 3!

System information: Mac OS X 10.10.2 (14C109)
Brandstring 'Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz'

Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro9,1' with board-id [Mac-4B7AC7E43945597E]
Ivy Bridge Core i3-3110M processor [0x306A9] setup [0x0903]
With a maximum TDP of 35 Watt, as specified by Intel

Warning: Low Frequency Mode is 0 (unknown/unconfirmed)
         Now using 1200 MHz for Mobile processor

Number logical CPU's: 4 (Core Frequency: 2400 MHz)
Number of Turbo States: 0
Number of P-States: 13 (1200-2400 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0903 instead of 0x0703)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/Admin/Library/ssdtPRGen/ssdt.dsl - 262 lines, 7757 bytes, 48 keywords
AML Output:    /Users/Admin/Library/ssdtPRGen/ssdt.aml - 1548 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

-----------

Feb  3 11:50:40 localhost kernel[0]: AICPUPMI: CPU P-States [ 12 24 ]
Feb  3 11:51:07 Admins-MacBook-Air kernel[0]: AICPUPMI: CPU P-States [ 12 22 24 ]
Feb  3 12:05:38 Admins-MacBook-Air kernel[0]: AICPUPMI: CPU P-States [ 12 18 22 24 ]

**Comment by Piker-Alpha** [comment]
Ok so you get: 12 18 22 24 which to me is perfectly fine for your i3. Remember this. It isn't a powerful processor and thus OS X can't do much with it in terms of power management. In short. If you don't see PM related errors in your log, it's fine.

**Comment by microvnhaxor** [comment]
ok. thanks you so much
