### ISSUE TITLE
XEON W3540 Error: Invalid argument detected

### ISSUE THREAD

**Issue by AdamiPL** [Piker-Alpha/ssdtPRGen.sh#123]
Hi
I;m used the newest version of your script, but when i tried to generate ssd i've got this error

             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/adam/Library/ssdtPRGen/Data

Error: Invalid argument detected: W3540
Aborting ...
Done.

i'm started with command: 

sudo ./ssdtPRGen.sh 'W3540' 130 1580 2930 3200 4 8 

without arg :

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/adam/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.2 (14C109)
Brandstring 'Intel(R) Xeon(R) CPU W3540 @ 2.93GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
You cannot use
```
sudo ./ssdtPRGen.sh 'W3540' 130 1580 2930 3200 4 8
```
And for a long time already. See also: ./ssdtPRGen.sh -h(elp)
Also. The latest version is 15.7 (the Beta) so please download that is fire it up with
```
./ssdtPRGen.sh -p W3540 -c 0
```
For this to work you need to add this data to you copy of ~/Library/ssdtPRgen/Data/User\ Defined.cfg
```
gUserDefinedCPUList=(
W3540,130,1600,2930,3200,4,8,0,133
)
```

**Comment by Fraisdos** [comment]
Good day,

I have the same cpu, I have tried the above but I get this message:

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2018 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.13.2 (17C205)
Brandstring: "Intel(R) Xeon(R) CPU W3540 @ 2.93GHz"

Override value: (-p) processor model, now using: W3540!

Version: models.cfg v171 / User Defined.cfg v-1

ACPI Processor {} Declaration(s) found in ${basename}

Warning: No ACPI Processor declarations found in DSDT!
	 Using assumed Scope (\_PR) {}


Error: Processor name(s) not found ...
Aborting ...
Done.

DSDT included, many thanks for your advices
[DSDT.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/1628279/DSDT.txt)
