### ISSUE TITLE
i7-4720HQ unknown CPU

### ISSUE THREAD

**Issue by rajasekharmobile** [Piker-Alpha/ssdtPRGen.sh#125]
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/topsycrets/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.2 (14C109)
Brandstring 'Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Thank you for reporting this here – data now available in the Beta version of ssdtPRGen.sh

**Comment by rajasekharmobile** [comment]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.7 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.10.2 (14C109)
Brandstring 'Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz'

Scope (_PR_) {1644 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro11,2' with board-id [Mac-3CBD00234E554E41]
Haswell Core i7-4720HQ processor [0x306C3] setup [0x0705]
Processor NOT matched, checking required arguments!

Error: Low Frequency Mode is 0 ...
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Cpu data is there in https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/Haswell.cfg#L174
but your local copy of: /Users/topsycrets/Library/ssdtPRGen/Data/Haswell.cfg
need to be removed/updated by ssdtPRGen.sh

**Comment by androidrivne** [comment]
Hi, when using beta version got error "Unknown processor model ..." with these commands:
./ssdtPRGen.sh
./ssdtPRGen.sh -p 'i7-4720HQ' -f 2600 -turbo 3600

**Comment by Piker-Alpha** [comment]
Please do not use a closed issue to add something that should work already. Thank you.
