### ISSUE TITLE
i7 4790 with SMBIOS iMac15,1: lowest should be 800 mHz but won't go lower than 1.6 gHz

### ISSUE THREAD

**Issue by brousseau6933** [Piker-Alpha/ssdtPRGen.sh#129]
Hello and thanks for your hard work,

The title says all: the script use the correct values (I think) for my i7 4790 but the lowest idle frequency (verified with Intel Power Gadget) is 1.6 gHz.

Without the script and in Windows 7, it obviously idle at 800 mHz. I also noted that with the generated SSDT, the frequencies tend to stay a lot in the 3 gHz range.

For the record:

Gigabyte Z97X-UD3H rev. 1.1
i7 4790
Ozmosis BIOS F7 from Hackintosh-forums.de (maybe part of the problem?)
Yosemite 10.10.3

** I also use an SSDT from Toleda to enable loading of ami9lpcb.
**I've tried changing the lowest value directly in the script from 1600 mHz to 800 mHz, no progress...
**I've tried beta of ssdtPRGen.sh, no change either...

Could it be that a real iMac 15,1 won't go lower than 1600 mHz?

Thanks.

-----------------------------------------------------------------------

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.7 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.10.3 (14D136)
Brandstring 'Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz'

Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac15,1' with board-id [Mac-42FD25EABCABB274]
Haswell Core i7-4790 processor [0x306C3] setup [0x0701]
Processor matched!
With a maximum TDP of 84 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 3600 MHz)
Number of Turbo States: 4 (3700-4000 MHz)
Number of P-States: 33 (800-4000 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'system-type' may be set improperly (1 instead of 2)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/Hackintosh/Library/ssdtPRGen/ssdt.dsl - 328 lines, 10067 bytes, 71 keywords
AML Output:    /Users/Hackintosh/Library/ssdtPRGen/ssdt.aml - 2213 bytes, 28 named objects, 43 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Users/Hackintosh/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n
STUDIO-PC:~ Hackintosh$

**Comment by Piker-Alpha** [comment]
The new iMac is a power house and should be responsive, and thus Apple won't let it idle too much. If idle is what you want, then try the Macmini7,1

**Comment by brousseau6933** [comment]
Solution found one year later: I used your freqVectorsEdit script to trigger the macmini7,1 frequency vectors but let my SMBIOS as iMac 14,2. Now idling better...

**Comment by juniorporciuncula** [comment]
@brousseau6933, how you did that? I'm having the same problem with a i7 4790. Not idling and staying around 3Ghz most of the time.

**Comment by brousseau6933** [comment]
Assuming that you executed ssdtprgen script, then:
 download the following: https://github.com/Piker-Alpha/freqVectorsEdit.sh

Run the script as root and when asked, choose Macmini 7,1 definition.

My CPU is now running between 0.8 gHz and 4 gHz.

**Comment by lnn2204** [comment]
> Solution found one year later: I used your freqVectorsEdit script to trigger the macmini7,1 frequency vectors but let my SMBIOS as iMac 14,2. Now idling better...

I got iMac14,2. Should i config in CPUFriend with 0.8 and the next hex should be?

**Comment by brousseau6933** [comment]
> > Solution found one year later: I used your freqVectorsEdit script to trigger the macmini7,1 frequency vectors but let my SMBIOS as iMac 14,2. Now idling better...
> 
> I got iMac14,2. Should i config in CPUFriend with 0.8 and the next hex should be?

Here is my EFI folder without SN's. I use CPUFriend. Hope it helps!
https://1drv.ms/u/s!AsCftN_jdRMFg5JYLc6PjKLEa6iHfg?e=XCQ3za
