### ISSUE TITLE
Failed to set ring table on i3210m Ivy Bridge 

### ISSUE THREAD

**Issue by SiddRamesh** [Piker-Alpha/ssdtPRGen.sh#132]
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformPlugin::setRingTable - AICPM failed to load ring table with status 0x0: Get=0, Load=0, Install=0
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformPlugin::configResourceHandler - Failed to set ring table!
1/30/15 10:26:07.000 AM kernel[0]: IOPPF - Found another boot volume.SuperIODevice: [Fatal] found unsupported chip! ITE sequence ID=0xffff, Winbond sequence ID=0xfc11
1/30/15 10:26:07.000 AM kernel[0]: [AGPM Controller] unknownPlatform
1/30/15 10:26:07.000 AM kernel[0]: IOPPF: AppleIntelCPUPowerManagement mode
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:08.000 AM kernel[0]: X86PlatformShim::sendStepper - Done!

Is Everything OK :(

**Comment by Piker-Alpha** [comment]
Not related. You need to fix this error: "[AGPM Controller] unknownPlatform"
