### ISSUE TITLE
Clarification about Max TDP

### ISSUE THREAD

**Issue by mecanogrh** [Piker-Alpha/ssdtPRGen.sh#133]
Hello,
trying to add 5Y10C Core M to the Broadwell.cfg
but couldn't locate Max TDP in Intel docs, not sure if it's even relevant for Core M.
Would a low value like 12 be ok? At base frequency TDP is 4.5 watts.

**Comment by Piker-Alpha** [comment]
No need to add it yourself. It's already defined in the Beta https://github.com/Piker-Alpha/ssdtPRGen.sh/tree/Beta
