### ISSUE TITLE
Please support Intel i5-5200U Processor 

### ISSUE THREAD

**Issue by mannyvergel** [Piker-Alpha/ssdtPRGen.sh#138]
Could you please help me. I'm getting "Unknown processor model" for my Intel i5 5200U.

The link of ark is http://ark.intel.com/products/85212/Intel-Core-i5-5200U-Processor-3M-Cache-up-to-2_70-GHz

**Comment by theracermaster** [comment]
Your CPU is supported [in the beta version](https://github.com/Piker-Alpha/ssdtPRGen.sh/tree/Beta) as well.

**Comment by Piker-Alpha** [comment]
Correct. This processor is supported by the Beta.

Thank you for helping out theracermaster!
