### ISSUE TITLE
Please support intel CPU I7-4720HQ

### ISSUE THREAD

**Issue by sky-91** [Piker-Alpha/ssdtPRGen.sh#140]
I run ./ssdtPRGen.sh and get below information:

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/sky/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.3 (14D131)
Brandstring 'Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

so I goto http://ark.intel.com and get all required info about my CPU
       Processor Number: i7-4720HQ
       TDP:47W
       Low Frequency Mode (use AppleIntelInfo.kext):unknown?
       Base Frequency:2.6GHz
       Max Turbo Frequency:3.6GHz
       Cores:4
       Threads:8
hope to fix this issue as soon,thanks!

**Comment by theracermaster** [comment]
Your CPU is supported [in the beta version](https://github.com/Piker-Alpha/ssdtPRGen.sh/tree/Beta).

**Comment by Piker-Alpha** [comment]
Correct. Processor is supported in the Beta, and thus I will close this issue.
