### ISSUE TITLE
'E5-2618L v3',75,1200,2300,3400,6,12 wrong values

### ISSUE THREAD

**Issue by regs1980** [Piker-Alpha/ssdtPRGen.sh#142]
'E5-2618L v3',75,1200,2300,3400,8,16

http://ark.intel.com/products/83351/Intel-Xeon-Processor-E5-2618L-v3-20M-Cache-2_30-GHz

**Comment by Piker-Alpha** [comment]
Thanks. I fixed the core.thread count in the Beta.

Note: I will close this issue, but if there is anything else that I missed... then feel free to reopen it again.
