### ISSUE TITLE
Hi.... LOOKING FOR HELP

### ISSUE THREAD

**Issue by yaalla4** [Piker-Alpha/ssdtPRGen.sh#143]
First I would like to get this....what can I try?
Thanks

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/useruser/Library/ssdtPRGen/Data
System information: Mac OS X 10.9.5 (13F1096)
Brandstring 'Intel(R) Xeon(R) CPU X5650 @ 2.67GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/130
