### ISSUE TITLE
Please support intel CPU I3-4170

### ISSUE THREAD

**Issue by uzmi** [Piker-Alpha/ssdtPRGen.sh#144]
I run ./ssdtPRGen.sh and get below information:

gDataPath: /Users/uzmi/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.4 (14E46)
Brandstring 'Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

Could you please help me?
Thanks

**Comment by Piker-Alpha** [comment]
Thank you for reporting this. Now available [in the beta version](https://github.com/Piker-Alpha/ssdtPRGen.sh/tree/Beta).

**Comment by AdamiPL** [comment]
still doesn't work..

System information: Mac OS X 10.11 (15A284)
Brandstring 'Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz'

./ssdtPRGen.sh: line 2743: /Users/adam/Library/ssdtPRGen/Data/Skylake.cfg: No such file or directory
Scope (_PR_) {1644 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Haswell Core i3-4170 processor [0x306C3] setup [0x0905]
Processor NOT matched, checking required arguments!

Error: Low Frequency Mode is 0 ...
Aborting ...
Done.
