### ISSUE TITLE
There is not the creation of the file to the Desktop ssdt.aml

### ISSUE THREAD

**Issue by jacksonlima** [Piker-Alpha/ssdtPRGen.sh#147]
Hello everyone,

I have an i7 4790k Haswell with the motherboard GA-Z97X-UD7-TH with the BIOS version F5 and installation of Yosemite 10.10.4, with Clover.
I was following the tutorial Toleda in TonyMacx86(http://www.tonymacx86.com/mavericks-desktop-support/128926-mavericks-native-cpu-igpu-power-management.html) when we arrived in steps 6 and 7:
6. Prepare SSDT
The script uses the installed processor
For a different CPU, see ssdtPRGen.sh v11.0 | Pike's Universum
For Desktop / Ivy Bridge / Core i3 / 5/7 3xxx, 3rd Generation (Note 3)

Piker-Alpha / ssdtPRGen.sh / Download ZIP
terminal:
cd Downloads / ssdtPRGen.sh-master
sudo chmod 755 ssdtPRGen.sh
./ssdtPRGen.sh
n
n
7. Rename Desktop / ssdt.aml to Desktop / SSDT.aml

I run the script as asking, but is not generated ssdt.aml file on the Desktop and therefore can not proceed.

Can someone help me?

Thank you.

Best regards,

Jackson Lima

Edit: The command ./ssdtPRGen.sh

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/jacksonlima/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.4 (14E46)
Brandstring 'Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz'

Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Haswell Core i7-4790K processor [0x306C3] setup [0x0705]
With a maximum TDP of 88 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 4 (4100-4400 MHz)
Number of P-States: 37 (800-4400 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/jacksonlima/Library/ssdtPRGen/ssdt.dsl - 332 lines, 10361 bytes, 71 keywords
AML Output:    /Users/jacksonlima/Library/ssdtPRGen/ssdt.aml - 2278 bytes, 28 named objects, 43 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Users/jacksonlima/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by theracermaster** [comment]
ssdtPRGen outputs the the generated SSDT to ~/Library/ssdtPRGen/ssdt.aml. You can copy it from there (it used to place it on the desktop but it doesn't do that anymore).

**Comment by Piker-Alpha** [comment]
Very good guys!

@Jackson, may I ask you to inform Toleda about this change?
