### ISSUE TITLE
E5-2670 V1 Dual Socket PM Problem

### ISSUE THREAD

**Issue by mruepp** [Piker-Alpha/ssdtPRGen.sh#148]
Hi,

I have issues getting PM to work with my Setup. I run Supermicro X9Dai dual Socket Xeon with CPU ID 0x0206D5 currently on a MacPro5,1 Profile and never got PM to work, wether with or without SSDT patched. Always on Standard Multiplier which is x26, even when I remove the AICPUPM.kext.

Do I need to change the Profile to for example Mac-942459F5819B171B / MacBookPro8,3 or Mac-942B59F58194171B / iMac12,2 despite they have no dual Socket Support?

Do I have to patch the AICPUPM kext? 

And I am not able to boot with Hyperthreading enabled, it is stuck at the bootprocess with 32 logical cores. I read on your blog about another guy with the same problem, you offered to help. What was the outcome, was it a messed up dsdt table?

Is there any information available to learn editing the dsdt and how the entries have to look like that osx is accepting them? Do I have to investigate in the kexts, how the devices should be named?

Thanks a lot for your work,

Michael

**Comment by mruepp** [comment]
I now got at least an output from AICPUPMInfo.kext with ./ssdtPRGen.sh -c 0 -d 2 -p E5-2670 -x 0 and the AICPMPatch.pl because unpatched I got Kernel panic on boot.


Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MWAIT C-States.....................: 135456
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_CORE_THREAD_COUNT......(0x35)  : 0x80008
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PLATFORM_INFO..........(0xCE)  : 0xC006C011A00
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E008407
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_MPERF.................(0xE7)  : 0x1E7F952F34
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_APERF.................(0xE8)  : 0x1CE1C72878
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_FLEX_RATIO.............(0x194) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_STATUS.......(0x198) : 0x221B00001A00
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_CONTROL......(0x199) : 0x1A00
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_CLOCK_MODULATION......(0x19A) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_THERM_STATUS..........(0x19C) : 0x88310000
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_MISC_ENABLES..........(0x1A0) : 0x850089
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x1E1E1F1F20202121
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_POWER_CTL..............(0x1FC) : 0x2504005B
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_POWER_LIMIT........(0x610) : 0x68450005A8398
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_ENERGY_STATUS......(0x611) : 0xB938A8D
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKGC3_IRTL.............(0x60a) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKGC6_IRTL.............(0x60b) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKGC7_IRTL.............(0x60c) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x141494800005C8
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PP0_POWER_LIMIT........(0x638) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PP0_ENERGY_STATUS......(0x639) : 0x9026F0B
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PP0_POLICY.............(0x63a) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: CPU Low Frequency Mode.............: 1200 MHz
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: CPU Maximum non-Turbo Frequency....: 2600 MHz
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: CPU Maximum Turbo Frequency........: 3300 MHz
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 31 ]
Jul 25 13:02:33 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 31 32 ]
Jul 25 13:02:35 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 31 32 ]
Jul 25 13:02:49 sunrise kernel[0]: AICPUPMI: CPU P-States [ (26) 31 32 33 ]

But when I stress the cpu, the Turbo is still not working. Frequency always stays on 2,6GHz.

**Comment by mruepp** [comment]
Now I changed Sysdefs to iMac12,2 and regenerated ssdt with ./ssdtPRGen.sh -c 0 -b Mac-942B59F58194171B -d 2 -m iMac12,2 -p E5-2670 -t 115 -x 0

But still no change in multiplier when stress -c 16 the cpus. It stays at 26.

Thanks a lot for Input.

Output looks like:
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MWAIT C-States.....................: 135456
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_CORE_THREAD_COUNT......(0x35)  : 0x80008
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PLATFORM_INFO..........(0xCE)  : 0xC006C011A00
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E008403
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_MPERF.................(0xE7)  : 0x12E4AE2988
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_APERF.................(0xE8)  : 0x1145FD68B0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_FLEX_RATIO.............(0x194) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_STATUS.......(0x198) : 0x221B00001A00
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_CONTROL......(0x199) : 0x1A00
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_CLOCK_MODULATION......(0x19A) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_THERM_STATUS..........(0x19C) : 0x88310000
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_MISC_ENABLES..........(0x1A0) : 0x850089
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x1E1E1F1F20202121
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_POWER_CTL..............(0x1FC) : 0x2504005B
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_POWER_LIMIT........(0x610) : 0x68450005A8398
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_ENERGY_STATUS......(0x611) : 0x6C55E19
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKGC3_IRTL.............(0x60a) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKGC6_IRTL.............(0x60b) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKGC7_IRTL.............(0x60c) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x141494800005C8
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PP0_POWER_LIMIT........(0x638) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PP0_ENERGY_STATUS......(0x639) : 0x54402E0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PP0_POLICY.............(0x63a) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: CPU Low Frequency Mode.............: 1200 MHz
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: CPU Maximum non-Turbo Frequency....: 2600 MHz
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: CPU Maximum Turbo Frequency........: 3300 MHz
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 ]
Jul 25 15:01:32 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 31 ]
Jul 25 15:01:33 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 31 ]
Jul 25 15:01:34 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 30 31 ]
Jul 25 15:01:38 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 30 31 32 ]
Jul 25 15:02:07 sunrise kernel[0]: AICPUPMI: CPU P-States [ (26) 29 30 31 32 33 ]

**Comment by mruepp** [comment]
Here is the output log of the script:

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Volumes/Home/Users/michael/Library/ssdtPRGen/Data
Override value: (-c) CPU type, now using: Sandy Bridge!
Override value: (-b) board-id, now using: Mac-942B59F58194171B!
Override value: (-d) debug mode, now using: 2!
Override value: (-m) model, now using: iMac12,2!
Override value: (-p) processor model, now using: E5-2670!
Override value: (-t) maximum TDP, now using: 115 Watt!
Override value: (-x) XCPM mode, now set to: 0!

System information: Mac OS X 10.10.4 (14E46)
Brandstring 'Genuine Intel(R) CPU @ 2.60GHz'

Extracting ACPI tables ...Done.4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b824d9553434b30085f4849440d414350493030303400
5b824d9553434b31085f4849440d414350493030303400
5b824b9953434b32085f4849440d414350493030303400
5b824b9953434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C000) found in Device (SCK0) {...} (non ACPI 1.0 compliant)
logicalCore: 0 C000
logicalCore: 1 C002
logicalCore: 2 C004
logicalCore: 3 C006
logicalCore: 4 C008
logicalCore: 5 C00A
logicalCore: 6 C00C
logicalCore: 7 C00E
Warning: only 8 of 16 ACPI Processor declarations found in Device(SCK0) {}gProcessorStartIndex: 8
gLogicalCPUs        : 16
gProcessorNames     : 16
Searching for 8 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C100) found in Device (SCK1) {...} (non ACPI 1.0 compliant)
logicalCore: 8 C100
logicalCore: 9 C102
logicalCore: 10 C104
logicalCore: 11 C106
logicalCore: 12 C108
logicalCore: 13 C10A
logicalCore: 14 C10C
logicalCore: 15 C10E
Extracting ACPI tables ...Done.Generating ssdt.dsl for a 'iMac12,2' with board-id [Mac-942B59F58194171B]
Sandy Bridge Core E5-2670 processor [0x206D5] setup [0x0402]
With a maximum TDP of '115' Watt, as specified by argument: -t 115
Number logical CPU's: 16 (Core Frequency: 2600 MHz)
Number of Turbo States: 7 (2700-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for C000 (C1,C3,C6)
Warning: 'cpu-type' may be set improperly (0x0402 instead of 0x0602)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.dsl - 364 lines, 10797 bytes, 70 keywords
AML Output:    /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.aml - 2506 bytes, 36 named objects, 34 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by mruepp** [comment]
This is the script output without using flags:

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Volumes/Home/Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: E5-2670!
Override value: (-d) debug mode, now using: 2!

System information: Mac OS X 10.10.4 (14E46)
Brandstring 'Genuine Intel(R) CPU @ 2.60GHz'

Extracting ACPI tables ...Done.4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b824d9553434b30085f4849440d414350493030303400
5b824d9553434b31085f4849440d414350493030303400
5b824b9953434b32085f4849440d414350493030303400
5b824b9953434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C000) found in Device (SCK0) {...} (non ACPI 1.0 compliant)
logicalCore: 0 C000
logicalCore: 1 C002
logicalCore: 2 C004
logicalCore: 3 C006
logicalCore: 4 C008
logicalCore: 5 C00A
logicalCore: 6 C00C
logicalCore: 7 C00E
Warning: only 8 of 16 ACPI Processor declarations found in Device(SCK0) {}gProcessorStartIndex: 8
gLogicalCPUs        : 16
gProcessorNames     : 16
Searching for 8 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C100) found in Device (SCK1) {...} (non ACPI 1.0 compliant)
logicalCore: 8 C100
logicalCore: 9 C102
logicalCore: 10 C104
logicalCore: 11 C106
logicalCore: 12 C108
logicalCore: 13 C10A
logicalCore: 14 C10C
logicalCore: 15 C10E
Extracting ACPI tables ...Done.Generating ssdt.dsl for a 'iMac12,2' with board-id [Mac-942B59F58194171B]
Sandy Bridge Core E5-2670 processor [0x206D5] setup [0x0402]
With a maximum TDP of 115 Watt, as specified by Intel
Number logical CPU's: 16 (Core Frequency: 2600 MHz)
Number of Turbo States: 7 (2700-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for C000 (C1,C3,C6)
Warning: 'cpu-type' may be set improperly (0x0402 instead of 0x0602)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.dsl - 364 lines, 10797 bytes, 70 keywords
AML Output:    /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.aml - 2506 bytes, 36 named objects, 34 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Volumes/Home/Users/michael/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by theracermaster** [comment]
Have you tried MacPro6,1?

**Comment by mruepp** [comment]
Yes, unfortunately, with MacPro6,1 I get no GFX, just black screen on boot with Nvidia GTX770. And this Profile supports only Ivy Bridge/Haswell as far as I know. This CPU´s are Sandy Bridge, thus no xcpupm, but AICPUPM.kext. Really stuck on this one.

**Comment by theracermaster** [comment]
Have you tried [this](http://www.tonymacx86.com/os-x-updates/161314-os-x-10-10-3-update-17.html#post1018267)? It supposedly fixes black screens for system definitions that don't originally have NVIDIA cards (iMac15,1, MacPro6,1, etc.). And I think MacPro6,1 should still work, without XCPM it should still load AICPUPM.

**Comment by mruepp** [comment]
Hi Alex, thanks a lot for the hint. At least it runs now on the MacPro6,1. But still not able to enable hyperthreading to get all 32 logical cores to work. Kernel Panic @ boot...
Regarding PM I will check if something changed. Thanks!

**Comment by mruepp** [comment]
Here is the Output of AICPUPMINFO.kext. I do not have SSDT installed. But I do not observe State change to Turbo mode or slower P-Modes than default 2,6GHz...

I get an Error that Sandy Bridge is not supported on Mac Pro 6,1. Should I try to create a SSDT with -c 0 ?

Thanks for Input

sunrise:~ michael$ cat /var/log/system.log | grep "AICPUPMI"
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MWAIT C-States.....................: 135456
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_CORE_THREAD_COUNT......(0x35)  : 0x80008
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PLATFORM_INFO..........(0xCE)  : 0xC006C011A00
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E008407
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_MPERF.................(0xE7)  : 0x1B51D6B6C0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_APERF.................(0xE8)  : 0x1741A30693
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_FLEX_RATIO.............(0x194) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_STATUS.......(0x198) : 0x221B00001A00
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_IA32_PERF_CONTROL......(0x199) : 0x1A00
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_CLOCK_MODULATION......(0x19A) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_THERM_STATUS..........(0x19C) : 0x88320000
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_MISC_ENABLES..........(0x1A0) : 0x850089
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x1E1E1F1F20202121
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_POWER_CTL..............(0x1FC) : 0x2504005B
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_POWER_LIMIT........(0x610) : 0x68450005A8398
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_ENERGY_STATUS......(0x611) : 0x8729D2F
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKGC3_IRTL.............(0x60a) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKGC6_IRTL.............(0x60b) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKGC7_IRTL.............(0x60c) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x141494800005C8
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PP0_POWER_LIMIT........(0x638) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PP0_ENERGY_STATUS......(0x639) : 0x696296D
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PP0_POLICY.............(0x63a) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: CPU Low Frequency Mode.............: 1200 MHz
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: CPU Maximum non-Turbo Frequency....: 2600 MHz
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: CPU Maximum Turbo Frequency........: 3300 MHz
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 29 ]
Jul 25 18:29:01 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 27 29 ]
Jul 25 18:29:02 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 27 29 ]
Jul 25 18:29:06 localhost kernel[0]: AICPUPMI: CPU P-States [ (26) 27 29 30 ]
Jul 25 18:29:23 sunrise kernel[0]: AICPUPMI: CPU P-States [ (26) 27 29 30 31 ]

**Comment by mruepp** [comment]
The Machine is much more stable with the MacPro6,1 profile. Ethernet and Areca SAS Controller are now detected everytime. With MacPro5,1 I had to reboot twice or more, until they got detected! 

Now I created the SSDT with the script:

./ssdtPRGen.sh -p E5-2670 -d 2 -c 0 -m MacPro6,1 -x 0

Here is the debug output:
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Volumes/Home/Users/michael/Library/ssdtPRGen/Data
Override value: (-p) processor model, now using: E5-2670!
Override value: (-d) debug mode, now using: 2!
Override value: (-c) CPU type, now using: Sandy Bridge!
Override value: (-m) model, now using: MacPro6,1!
Override value: (-x) XCPM mode, now set to: 0!

System information: Mac OS X 10.10.4 (14E46)
Brandstring 'Genuine Intel(R) CPU @ 2.60GHz'

Extracting ACPI tables ...Done.4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b824d9553434b30085f4849440d414350493030303400
5b824d9553434b31085f4849440d414350493030303400
5b824b9953434b32085f4849440d414350493030303400
5b824b9953434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C000) found in Device (SCK0) {...} (non ACPI 1.0 compliant)
logicalCore: 0 C000
logicalCore: 1 C002
logicalCore: 2 C004
logicalCore: 3 C006
logicalCore: 4 C008
logicalCore: 5 C00A
logicalCore: 6 C00C
logicalCore: 7 C00E
Warning: only 8 of 16 ACPI Processor declarations found in Device(SCK0) {}gProcessorStartIndex: 8
gLogicalCPUs        : 16
gProcessorNames     : 16
Searching for 8 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
ACPI Processor declaration (C100) found in Device (SCK1) {...} (non ACPI 1.0 compliant)
logicalCore: 8 C100
logicalCore: 9 C102
logicalCore: 10 C104
logicalCore: 11 C106
logicalCore: 12 C108
logicalCore: 13 C10A
logicalCore: 14 C10C
logicalCore: 15 C10E
Extracting ACPI tables ...Done.Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Sandy Bridge Core E5-2670 processor [0x206D5] setup [0x0402]
With a maximum TDP of 115 Watt, as specified by Intel
Number logical CPU's: 16 (Core Frequency: 2600 MHz)
Number of Turbo States: 7 (2700-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 29
Adding C1
Adding C3
Adding C6
Adding C7
targetCStates: 29
Adding C1
Adding C3
Adding C6
Adding C7
Injected C-States for C000 (C1,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0402 instead of 0x0a02)

Error: board-id [Mac-F60DEB81FF30ACF6] not supported by Sandy Bridge – check SMBIOS data / use the -c option

Do you want to continue (y/n)?

**Comment by theracermaster** [comment]
Have you tried setting `-c` to 2 instead of 0?

**Comment by mruepp** [comment]
I tried witch -c 1 ivy bridge, but kernel panic at boot. The cpu is a sandy-bridge with cpuid 0x0206d5. Could this work wit -c 3?

**Comment by theracermaster** [comment]
Try `-c 2` first, then `-c 3` if that doesn't work.

**Comment by mruepp** [comment]
Tried now with 0, 1, 2, 3. 1-3 Results in Kernel Panic at Boot.
CLI was: ./ssdtPRGen.sh -c 2 -d 2 -p E5-2670 -x 0

Only thing worked was -c 0 but no change in states.

**Comment by theracermaster** [comment]
Hmm, Apple never used Sandy Bridge-E CPUs, you might need a modified AICPUPM.kext (see [here](http://www.insanelymac.com/forum/topic/302310-sandy-bridge-e-ivy-bridge-e-power-management-1010-yosemite/)).

**Comment by mruepp** [comment]
Thanks A LOT! That was exactly what I was searching for! Now I have PM working :-)
Do you no by chance maybe a patch to get yosemite kernel to accept more than 16 logical cores?

And again,

Thank you for your help!

**Comment by theracermaster** [comment]
Hmm, are you sure that there is a limit of 16 cores? MacPro6,1 has a 12-core Xeon as an official custom-order option (with HT, so 24 logical cores), so at the minimum 24 logical core should work.

**Comment by mruepp** [comment]
I tried limit active cores to 6 (2x6) and enable hyperthreading. Panic with aicpupm.kext in backtrace. Only 16c working. Have this prob since yosemite. 10.9 worked. Got a patched kernel from rampagedev once but for 10.10. Don't know what he patched... Thx!

**Comment by mruepp** [comment]
I found a post about editing the StepContextDict to reach lower states, is that possible? Which entries should we use to reach lower states? I got Turbo enabled, but my procs never go to lower states than x27-29. Best Regards

https://pikeralpha.wordpress.com/2014/02/23/ssdtprgen-v12-0-with-multi-processor-support/comment-page-1/#comment-1221

**Comment by mruepp** [comment]
There is a solution for more than 16 Cores. Pls visit the Rampagedev Site under "Kernel Patching", you will find the Perl Code there.

**Comment by theracermaster** [comment]
Ah, interesting. I assume your system is working now, correct?

**Comment by mruepp** [comment]
Pm is working, but unfortunately, the 32 core patch is not working. Was able to test it right now. Waiting for an answer from rampagedev.

**Comment by theracermaster** [comment]
The rampagedev patch find pattern seems to be missing in the kernel, which explains why it's not working. Did it work on a previous version of Yosemite?

**Comment by mruepp** [comment]
I was not able to test because I´ve got the ready patched kernel from rampagedev, but this should be the patch he used on the 14.0.0 Kernel. This one worked with 32 Cores.

**Comment by theracermaster** [comment]
10.10.4 kernel seems to be missing the find pattern, so the patch won't work for it (it does nothing).

**Comment by mruepp** [comment]
How do you know? I do not get any output from the command. Also, md5 hash is different...

**Comment by theracermaster** [comment]
Apologies, it actually is correct. I must've messed up when doing the diassembly (I redid it and it seems present as it should be). I don't know why you are receiving panics unfortunately.

**Comment by mruepp** [comment]
Hi, Rampagedev suggested I should use NullCPUPM, but I use already a patched AICPUPM which works perfectly with 16 Cores, including Turbo. Anyhow, will test after my holidays. BTW, could you give me a headstart or pointing me to resources how to disassembly kernel code, etc? I would really like to know what this patch does, I tried to look at the darwin source, Threads.c and so on, but I didn´t really got a clue... Thx

**Comment by fhill2** [comment]
mruepp please e-mail your SSDT I have the same setup as you!
Thankyou!
georgehill010@gmail.com

**Comment by subzerofun** [comment]
@mruepp  hey could you also please send me your patched files? have a dual E5-2670 setup and want to get powermanagement working. could you also send me your SSDT? thank you!
[dietrichstein@gmx.net](mailto:dietrichstein@gmx.net)

**Comment by mruepp** [comment]
Attached my DSDT (i patched directly, no SSDT)
[DSDT.aml.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/817050/DSDT.aml.zip)

Best

**Comment by mruepp** [comment]
Attached my DSDT. I currently don´t use SSDT but use MacPro 5,1 Profile

You can easily generate SSDT but you have to switch to imac14,2 or MacPro6,1 first. Then use the script (ssdtPRGen) and copy the SSDT to the clover acpi folder.

This DSDT works well with the Ethernet Interfaces and all other stuff vanilla (only with FakeSMC and VodooTSCSync.kext in the clover kext folder) no need to install kexts into system

[DSDT.aml.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/817053/DSDT.aml.zip)

**Comment by mruepp** [comment]
Closing, no longer applicable
