### ISSUE TITLE
Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

### ISSUE THREAD

**Issue by zhk0624** [Piker-Alpha/ssdtPRGen.sh#151]
Error: Low Frequency Mode is 0 ...
Aborting ...
Done.

**Comment by zhk0624** [comment]
Scope (_PR_) {1644 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro11,1' with board-id [Mac-189A3D4F975D5FFC]
Haswell Core i7-4720HQ processor [0x306C3] setup [0x0705]
Processor NOT matched, checking required arguments!

**Comment by Piker-Alpha** [comment]
Your processor is supported by the [Beta version](https://github.com/Piker-Alpha/ssdtPRGen.sh/tree/Beta).
