### ISSUE TITLE
No such file or directory on lines: 2624, 2633, 2643, 2653 and Error: Unknown processor model ...

### ISSUE THREAD

**Issue by vahids** [Piker-Alpha/ssdtPRGen.sh#157]
My cpu: http://ark.intel.com/products/71465/Intel-Core-i3-3120M-Processor-3M-Cache-2_50-GHz
I'm on Yosemite 10.10.5
currently using NullCpuPowerManagment.

Vahids-MacBook-Pro:Desktop vahid$ ./ssdtPRGen.sh -c 1 -f 2500 -t 35

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/vahid/Library/ssdtPRGen/Data
Override value: (-c) CPU type, now using: Ivy Bridge!
Override value: (-f) clock frequency, now using: 2500 MHz!
Override value: (-t) maximum TDP, now using: 35 Watt!

System information: Mac OS X 10.10.5 (14F27)
Brandstring 'Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz'

./ssdtPRGen.sh: line 2624: /Users/vahid/Library/ssdtPRGen/Data/Sandy Bridge.cfg: No such file or directory
./ssdtPRGen.sh: line 2633: /Users/vahid/Library/ssdtPRGen/Data/Ivy Bridge.cfg: No such file or directory
./ssdtPRGen.sh: line 2643: /Users/vahid/Library/ssdtPRGen/Data/Haswell.cfg: No such file or directory
./ssdtPRGen.sh: line 2653: /Users/vahid/Library/ssdtPRGen/Data/Broadwell.cfg: No
Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Seems like source is failing in 10.10.5. Try replacing it with a dot "."

**Comment by vahids** [comment]
replace what with dot ?!

**Comment by vahids** [comment]
I downloaded https://codeload.github.com/Piker-Alpha/ssdtPRGen.sh/zip/master file and put files on current path. seems like working:

Vahids-MacBook-Pro:Desktop vahid$ sudo ./ssdtPRGen.sh -c 1 -f 2500 -t 35
Password:


ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2015 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/vahid/Library/ssdtPRGen/Data
Override value: (-c) CPU type, now using: Ivy Bridge!
Override value: (-f) clock frequency, now using: 2500 MHz!
Override value: (-t) maximum TDP, now using: 35 Watt!

System information: Mac OS X 10.10.5 (14F27)
Brandstring 'Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz'

Scope (_PR_) æ220 byteså with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro9,2' with board-id ÆMac-6F01561E16C75D06Å
Ivy Bridge Core i3-3120M processor Æ0x306A9Å setup Æ0x0903Å
With a maximum TDP of '35' Watt, as specified by argument: -t 35

Warning: Low Frequency Mode is 0 (unknown/unconfirmed)
         Now using 1200 MHz for Mobile processor

Number logical CPU's: 4 (Core Frequency: 2500 MHz)
Number of Turbo States: 0
Number of P-States: 14 (1200-2500 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'cpu-type' may be set improperly (0x0903 instead of 0x0703)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 ÆNov  6 2014Å
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/vahid/Library/ssdtPRGen/ssdt.dsl - 263 lines, 7833 bytes, 48 keywords
AML Output:    /Users/vahid/Library/ssdtPRGen/ssdt.aml - 1566 bytes, 16 named objects, 32 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Is it OK now ?!

**Comment by vahids** [comment]
My hackintosh won't boot with generated ssdt.

**Comment by Piker-Alpha** [comment]
Ok so somehow the files where missing. And I meant replace "source" on the lines with a ".". Anyway. You should download/compile/run https://github.com/Piker-Alpha/AppleIntelInfo to find out the LFM (see output of the kext) and use that with -lfm 800 (or whatever you get).

Also. You should no longer use NullCpuPowerManagment and are you dropping power management SSDT's?

**Comment by vahids** [comment]
I can't find any LFM.
http://paste.ubuntu.com/12323672/

I know about NullCPUPowerManagment and dropSSDT in chameleon boot loader.

**Comment by Piker-Alpha** [comment]
"CPU Low Frequency Mode.............: 1200 MHz"

**Comment by vahids** [comment]
Done.
I have 4 steps now: 
9/10/15 8:54:17.000 AM kernel[0]: MSRDumper PStatesReached: 12 18 21 25 

Thanks/
