### ISSUE TITLE
i3-4170 Support

### ISSUE THREAD

**Issue by AdamiPL** [Piker-Alpha/ssdtPRGen.sh#162]
still doesn't work on official & beta version of ssdtPRGen.sh

System information: Mac OS X 10.11 (15A284)
Brandstring 'Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz'

./ssdtPRGen.sh: line 2743: /Users/adam/Library/ssdtPRGen/Data/Skylake.cfg: No such file or directory
Scope (PR) {1644 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-27ADBB7B4CEE8E61]
Haswell Core i3-4170 processor [0x306C3] setup [0x0905]
Processor NOT matched, checking required arguments!

Error: Low Frequency Mode is 0 ...
Aborting ...
Done.

and tried to looking for Skylake config, this is haswell

**Comment by AdamiPL** [comment]
Ok i add by self on to Haskell.cfg:

i3-4170,54,800,3700,3700,2,4

and i think is working :)

**Comment by Piker-Alpha** [comment]
Skylake.cfg was missing and that should now be solved (see issue #181).
