### ISSUE TITLE
i7-3517U (_HID, "ACPI0004") NOT found in the DSDT

### ISSUE THREAD

**Issue by bjgold** [Piker-Alpha/ssdtPRGen.sh#166]
Hello,
i have problem. 
~/ssdtPRGen.sh -b Mac-2E6FAB96566FE58C -x 1 -turbo 2400 -w 1 -c 1 -d 3
And:
MBA11:~ alex$ ~/ssdtPRGen.sh -b Mac-2E6FAB96566FE58C -x 1 -turbo 2400 -w 1 -c 1 -d 3

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
##              v15.6 Copyright (c) 2013-2015 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/alex/Library/ssdtPRGen/Data
Override value: (-b) board-id, now using: Mac-2E6FAB96566FE58C!
Override value: (-x) XCPM mode, now set to: 1!
Override value: (-turbo) maximum (turbo) frequency, now using: 2400 MHz!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!
Override value: (-c) CPU type, now using: Ivy Bridge!
Override value: (-d) debug mode, now using: 3!

System information: Mac OS X 10.11.1 (15B42)
Brandstring 'Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz'

Extracting ACPI tables .../Users/alex/ssdtPRGen.sh: line 2295:  3681 Segmentation fault: 11  "${gToolPath}/extractACPITables"
Done.Name (_HID, "ACPI0004") NOT found in the DSDT
1 Scope (_PR_) {..} object(s) found in the DSDT
scopeObjectData: 104e065f50525f
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4e/78
packageLength: 0x06e/110
scopeLength: 110
scopeLength: 206 (egrep pattern length)
scopeObjectData length 220 (includes egrep pattern)
ACPI Processor declaration (CPU0) {0x0b bytes} found in the DSDT (ACPI 1.0 compliant)
logicalCore: 0 CPU0
logicalCore: 1 CPU1
logicalCore: 2 CPU2
logicalCore: 3 CPU3
Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Extracting ACPI tables .../Users/alex/ssdtPRGen.sh: line 2295:  3736 Segmentation fault: 11  "${gToolPath}/extractACPITables"
Done.Generating ssdt.dsl for a 'iMac14,2' with board-id [Mac-2E6FAB96566FE58C]
Ivy Bridge Core i7-3517U processor [0x306A9] setup [0x0704]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1900 MHz)
Number of Turbo States: 5 (2000-2400 MHz)
Number of P-States: 17 (800-2400 MHz)
Adjusting C-States for detected (mobile) processor
targetCStates: 29
Adding C1
Adding C3
Adding C6
Adding C7
targetCStates: 7
Adding C1
Adding C2
Adding C3
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

How repair:
1) Done.Name (_HID, "ACPI0004") NOT found in the DSDT
2) Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Extracting ACPI tables .../Users/alex/ssdtPRGen.sh: line 2295:  3736 Segmentation fault: 11  "${gToolPath}/extractACPITables"

**Comment by Piker-Alpha** [comment]
Please use the latest Beta version of ssdtPRGen.sh
