### ISSUE TITLE
X5365 @ 3.00GHz Unknown processor model ...

### ISSUE THREAD

**Issue by nmano** [Piker-Alpha/ssdtPRGen.sh#169]
# X-5000 Xeon Processor Series

X-5365,150,0,2993,2993,4,4
I edit like this Sandy Bridge.cfg still not workSystem information: Mac OS X 10.11 (15A284)
Brandstring 'Intel(R) Xeon(R) CPU X5365 @ 3.00GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
The brand sting is clear. You should use "X5365" and not "X-5365".
