### ISSUE TITLE
Download links broken? No such file. i-5257u on 10.11.1

### ISSUE THREAD

**Issue by mipnope** [Piker-Alpha/ssdtPRGen.sh#172]
Is there a way for me to fix this? Am I doing something wrong? Anything I should have read and missed?

Tried with online and Zip Version. Loads only Sandy Bridge.cfg in Data. 

admins-MBP:~ admin$ curl -o ~/ssdtPRGen.sh https://raw.githubusercontent.com/Piker-Alpha/ssdtPRGen.sh/Beta/ssdtPRGen.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  134k  100  134k    0     0   182k      0 --:--:-- --:--:-- --:--:--  183k
admins-MBP:~ admin$  chmod +x ~/ssdtPRGen.sh
admins-MBP:~ admin$ ~/ssdtPRGen.sh

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
##              v160 Copyright (c) 2013-2015 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

/Users/admin/ssdtPRGen.sh: line 3416: /Users/admin/Library/ssdtPRGen/Data/Models.cfg: No such file or directory
System information: Mac OS X 10.11.1 (15B42)
Brandstring 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz'

gModelDataVersion: 
/Users/admin/ssdtPRGen.sh: line 2717: /Users/admin/Library/ssdtPRGen/Data/Ivy Bridge.cfg: No such file or directory
/Users/admin/ssdtPRGen.sh: line 2728: /Users/admin/Library/ssdtPRGen/Data/Haswell.cfg: No such file or directory
/Users/admin/ssdtPRGen.sh: line 2739: /Users/admin/Library/ssdtPRGen/Data/Broadwell.cfg: No such file or directory
/Users/admin/ssdtPRGen.sh: line 2750: /Users/admin/Library/ssdtPRGen/Data/Skylake.cfg: No such file or directory
Error: Unknown/unsupported processor model detected!

Do you want to continue (y/n)?

/// tried Help:
~/ssdtPRGen.sh -h

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
##              v160 Copyright (c) 2013-2015 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

/Users/admin/ssdtPRGen.sh: line 3416: /Users/admin/Library/ssdtPRGen/Data/Models.cfg: No such file or directory
Usage: ./ssdtPRGen.sh [-abcdfhlmptwx]
       -acpi Processor name (example: CPU0, C000)
       -bclk frequency (base clock frequency)
       -board-id (example: Mac-F60DEB81FF30ACF6)
       -cpu type [0/1/2/3/4]
etc.

////  Tried Zip:
admins-MBP:~ admin$ curl -o ~/Library/ssdtPRGen.zip https://codeload.github.com/Piker-Alpha/ssdtPRGen.sh/zip/Beta
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  357k    0  357k    0     0   286k      0 --:--:--  0:00:01 --:--:--  286k
admins-MBP:~ admin$ unzip -qu ~/Library/ssdtPRGen.zip -d ~/Library/
admins-MBP:~ admin$ mv ~/Library/ssdtPRGen.sh-master ~/Library/ssdtPRGen
mv: rename /Users/admin/Library/ssdtPRGen.sh-master to /Users/admin/Library/ssdtPRGen/ssdtPRGen.sh-master: No such file or direcctory

///  Tried manually copy Files .cfg files to ssdtPRGen/Data :
chmod +x ~/ssdtPRGen.sh
admins-MBP:~ admin$ ~/ssdtPRGen.sh

cmp: Data/Models.cfg: No such file or directory
System information: Mac OS X 10.11.1 (15B42)
Brandstring 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz'

gModelDataVersion: 160
cmp: Data/Ivy Bridge.cfg: No such file or directory
cmp: Data/Haswell.cfg: No such file or directory
cmp: Data/Broadwell.cfg: No such file or directory
/Users/admin/Library/ssdtPRGen/Data/Broadwell.cfg: line 35: unexpected EOF while looking for matching `''
/Users/admin/Library/ssdtPRGen/Data/Broadwell.cfg: line 140: syntax error: unexpected end of file
cmp: Data/Skylake.cfg: No such file or directory
Error: Unknown/unsupported processor model detected!

Do you want to continue (y/n)? n

///// The unofficial 15.7.Beta3 firewolf worked for me. However Warning about processor at the end.

**Comment by Piker-Alpha** [comment]
This issue should be fixed (see issue #181).
