### ISSUE TITLE
i3 3245 Low Frequency

### ISSUE THREAD

**Issue by eldzse** [Piker-Alpha/ssdtPRGen.sh#174]
![screen shot 2015-12-11 at 06 44 59](https://cloud.githubusercontent.com/assets/16250904/11736850/339f40e2-9fd3-11e5-907a-8ca804d71de1.png)

Hi!
Not working for me.
Any idea?

**Comment by Piker-Alpha** [comment]
The missing configuration files issue has been fixed in one of the latest Beta versions of ssdtPRGen.sh so please use that instead of older versions. Thanks.
