### ISSUE TITLE
i3 5005U( isn't recognized) osx how to set turbo?

### ISSUE THREAD

**Issue by Laquari95** [Piker-Alpha/ssdtPRGen.sh#182]
Hi Piker I have i3 5005U and hd5500 , i have tried your ssdt gen
this is my error:
System information: Mac OS X 10.11.2 (15C50)
Brandstring ‘Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz’

gModelDataVersion: 160
/Users/vittorio/Library/ssdtPRGen/Data/Broadwell.cfg: line 35: unexpected EOF while looking for matching `”
/Users/vittorio/Library/ssdtPRGen/Data/Broadwell.cfg: line 140: syntax error: unexpected end of file
Error: Unknown/unsupported processor model detected!

Do you want to continue (y/n)?

if I press y:
Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a ‘MacBookAir6,2’ with board-id [Mac-7DF21CB3ED6977E5]
Unknown Core i3-5005U processor [0x306D4] setup [0x0906]
Processor NOT matched, checking required arguments!

Error: Low Frequency Mode is 0 …
Aborting …
Done.

After see the low frequency error with text mate i open your broadwell.cfg and i see a note:
 A "low frequency mode" of 0 means that the frequency is unconfirmed (use AppleIntelInfo.kext).
Processors without turbo support should set Max Turbo Frequency equal to the Clock Speed.
Can you help me?
Thank you :)

**Comment by Piker-Alpha** [comment]
Thank you for reporting this issue here. The problem was that the Broadwell.cfg file was broken. The solution is simple. Download https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/Broadwell.cfg and replace ~/Library/ssdtPRGen/Data/Broadwell.cfg and ssdtPRGen.sh/Data/Broadwell.cfg with it. After that you can rerun ssdtPRGen.sh and the error should be gone.

**Comment by Laquari95** [comment]
Thank you very much! your work is very important for us
now i have created the ssdt :) the broadwell's owner now can say yesss big piker!
