### ISSUE TITLE
Can't execute the script.  APIC.aml not found  Aborting.

### ISSUE THREAD

**Issue by shixuev5** [Piker-Alpha/ssdtPRGen.sh#187]
<img width="767" alt="2016-01-26 10 26 19" src="https://cloud.githubusercontent.com/assets/3207014/12571041/15527140-c418-11e5-9dc4-e777f0116713.png">
<img width="586" alt="2016-01-26 10 25 58" src="https://cloud.githubusercontent.com/assets/3207014/12571042/15f0b22e-c418-11e5-9134-d015fb56aeba.png">

**Comment by Piker-Alpha** [comment]
Oh blimey. I forgot to undo a change I made for regression testing. Let me correct this... Done!

Thank you for filing this bug here!

**Comment by shixuev5** [comment]
<img width="584" alt="2016-01-26 1 15 18" src="https://cloud.githubusercontent.com/assets/3207014/12573039/ef1d26ca-c42e-11e5-930e-86f742f5913d.png">
have a new problem.

**Comment by Piker-Alpha** [comment]
Look at this line: 100 447 100 447 0 0 25 0 0:00:17 0:00:17 --:--:-- 97

The second value is the size of the download and the script is 142Kb. Not 447 bytes -> Download failure.

Edit: I added a note to the download instructions, about verifying the size of the download. Thanks!

**Comment by cecekpawon** [comment]
Maybe the curl command failed to follow new address, "`curl -Lo`" may help

**Comment by Piker-Alpha** [comment]
Thanks for the tip!
