### ISSUE TITLE
Unsupported Board-ID

### ISSUE THREAD

**Issue by kukumakusu** [Piker-Alpha/ssdtPRGen.sh#188]
I get this error: 
board-id [Mac-XXXXXXXXXXXX] not supported by Skylake – check SMBIOS data / use the -c option
I'm using 14.1 iMac SMBIOS ID on System.
Which SMBIOS ID supported by Skylake?  So i can change with correct one.

**Comment by Piker-Alpha** [comment]
That is easy, but you should have known that by reading the [README](https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/README.md) or using the -h argument, which both tells you to use ./ssdtPRGen.sh -show
