### ISSUE TITLE
cmp: Data/xxxx.xxx: No such file or directory

### ISSUE THREAD

**Issue by eminorb5** [Piker-Alpha/ssdtPRGen.sh#192]
Hi Piker,

Just to inform that i always have the message "cmp: Data/xxx.xxx: No such file or directory" every time, but it also can generated the SSDT without any error or warning. Here some of the message i got.

---

System information: Mac OS X 10.10.5 (14F1605)
Brandstring: "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz"

Override value: (-b) board-id, now using: Mac-27ADBB7B4CEE8E61!

cmp: Data/Sandy Bridge.cfg: No such file or directory
cmp: Data/Ivy Bridge.cfg: No such file or directory
cmp: Data/Haswell.cfg: No such file or directory
Version: models.cfg v160 / Haswell.cfg v150

cmp: Data/Restrictions.cfg: No such file or directory

---

So, I just try to copy the folder "Data" from "~/Library/ssdtPRGen/Data" to my "~/Data", then try run again and the message above disappear. not so sure which one is the correct way.

Anyway, both also can generate SSDT without any error.

Please let me know which one is correct?

Million thanks ;)
Tony

**Comment by Piker-Alpha** [comment]
Right. You may not have a Data directory. Only if you downloaded the ZIP file, but it should just work. Let me fix that right now... Done!

Thank you for filing this bug report here!

Edit: Please confirm the fix and close this issue. Thanks again!

**Comment by eminorb5** [comment]
Wow very fast reply !!
just tested, it is work perfectly !!

million thanks ;)

**Comment by anerik70** [comment]
Piker how can i solve this 
<img width="776" alt="captura de pantalla 2016-02-20 a las 1 28 51 p m" src="https://cloud.githubusercontent.com/assets/5209138/13204219/6f7721a4-d898-11e5-98be-1308c10a9339.png">

**Comment by infowolfe** [comment]
@anerik70 
1: don't hijack previously closed tickets
2: read what it says. the board/machine (MacBook8,1) you picked doesn't support broadwell.
3: if you're really incapable of item 2 above... pick a platform that _SUPPORTS_ or _SHIPS_ with broadwell cpus if you want to not see a non-fatal warning.
