### ISSUE TITLE
Library/ssdtPRGen/APIC.aml not found!

### ISSUE THREAD

**Issue by sw-gsic** [Piker-Alpha/ssdtPRGen.sh#195]
this is issue 
maverick 10.9.5 on dell inspiron 1720 
I think is not fix ?

thanky you

**Comment by Piker-Alpha** [comment]
I need the output of the script (use code tags) and the arguments that you used.

**Comment by sw-gsic** [comment]
I will send but I have question your script will be workin with that old computer like this inspiron ?
I was use only one argument: 

# ssdtPRgen -f 2600

**Comment by sw-gsic** [comment]
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen

##              v17.7 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.9.5 (13F1603)
Brandstring: "Intel(R) Core(TM)2 Duo CPU T9300 @ 2.50GHz"

./ssdtPRGen.sh: line 2469:   981 Segmentation fault: 11  "${gToolPath}/extractACPITables"
Error: /Users/grzes/Library/ssdtPRGen/DSDT.aml not found!
Aborting ...
Done.

MacBook-grzegorz:~ grzes$

now i got success DSDT.aml not found , before was APIC ?

**Comment by Piker-Alpha** [comment]
The segmentation error should have been fixed some time ago, thanks to TheRacerMaster, but what you can do is:

1.) Remove the binary with:

``` sh
rm ~/Library/ssdtPRGen/Tools/extractACPITables
```

2.) Re-run ssdtPRGen.sh (the executable will now be downloaded).

If that doesn't work then you can compile it yourself:

1.) Download https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Tools/extractACPITables.c

2.) Compile it with:

``` sh
cc -O2 extractACPITables.c -o extractACPITables -Wall -framework IOKit -framework CoreFoundation
```

3.) cp  extractACPITables ~/Library/ssdtPRGen/Tools

4.) Re-run ssdtPRGen.sh

**Comment by Piker-Alpha** [comment]
Closing issue. Re-open if you need more help.
