### ISSUE TITLE
i3-5015u rarely drops below 2.0 ghz

### ISSUE THREAD

**Issue by zawata** [Piker-Alpha/ssdtPRGen.sh#205]
When using the SSDT provide by the script, I get 17 states generated and i can see all of them with appleintelinfo but when monitoring with intel power gadget i get a graph like this:

[IPG](http://imgur.com/q2DB3uW)

I attempted to edit my frequency vectors using your script, [this issue](https://github.com/Piker-Alpha/freqVectorsEdit.sh/issues/3) and [this issue](https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/198) but with no success.

Are there any other courses of action/things that i've done wrong and can fix?

Thanks for any help anyone can provide, please let me know of any files you may need

**Comment by gfoury** [comment]
I don't think this is a freqVector problem; the symptoms I've seen are a lower limit at 1300MHz, but with peaks up to the CPU's turbo frequency.

This may sound like a stupid question, but Is something running on the CPU all the time? Check in Activity Monitor:CPU:Active Processes. I've had `mds` eat all my CPU time pretty often.

Could you paste the last line of AppleIntelInfo, the one showing all the P-States?

**Comment by zawata** [comment]
CPU P-States [ (10) 18 21 ] iGPU P-States [ (6) ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 2 3 ]
CPU C7-Cores [ 0 1 2 3 ]
CPU P-States [ (10) 14 18 21 ] iGPU P-States [ (6) ]
CPU P-States [ (10) 13 14 18 21 ] iGPU P-States [ (6) ]
CPU P-States [ 10 13 14 18 20 (21) ] iGPU P-States [ (6) ]
CPU P-States [ 10 13 14 15 18 20 (21) ] iGPU P-States [ (6) ]
CPU P-States [ (10) 12 13 14 15 18 20 21 ] iGPU P-States [ (6) ]
CPU P-States [ 10 12 13 14 15 18 19 20 (21) ] iGPU P-States [ (6) ]
CPU P-States [ 10 12 13 14 15 16 18 19 20 (21) ] iGPU P-States [ (6) ]
CPU P-States [ (10) 12 13 14 15 16 17 18 19 20 21 ] iGPU P-States [ (6) ]

i was getting more states previously, I'm not sure why its less now, i monitored for like 45 minutes 

Under my activity monitor, the heaviest process is one called kernel_task and its always more than 50% usage sometimes as high as 300%

**Comment by gfoury** [comment]
I think you legitimately have high CPU load. The CPU is staying in high states because it is in use.

**Comment by zawata** [comment]
I mean it's a reasonable assumption but I've seen people with worse cpu's have less cpu usage 

Man this is upsetting, my computer has been really easy get up an running other than this issue

**Comment by gfoury** [comment]
I have a Core 2 E8400 sitting at 0.3% kernel_task. This i5-5200U is at ~1.4%. Your CPU is slower, but not that much slower, I'd think.

What does your memory pressure graph look like in Activity Monitor? (Swapping can show up as kernel_task, IIRC.) Are you running something like VirtualBox? (I think virtual machines were charged to kernel_task at some point.)

**Comment by zawata** [comment]
![screen shot 2016-03-28 at 8 15 36 pm](https://cloud.githubusercontent.com/assets/6119870/14097041/4ca4ab00-f522-11e5-87c3-afd35c48de4a.png)

doesn't look out of the ordinary, the 470mb of kernel task is concerning but doesn't seem bad

No this is completely fresh install, all I've done on it is get it booting.

**Comment by gfoury** [comment]
Nope, doesn't look like memory to me either.

Maybe bring this up somewhere like tonymacx86? I bet somebody has seen this problem before (fresh install, high kernel_task CPU usage: 50-300%)

**Comment by zawata** [comment]
yeah, now that im pretty sure its not caused by an incorrect SSDT generation ill probably start branching out for fixes,

thanks for taking a look at this for me

**Comment by Piker-Alpha** [comment]
Please download/run debugMachKernel.sh and boot with the -cpuid argument. Then enter the following command in a terminal window:

```
cat /var/log/system.log| grep 'cpuid_fn(0x00000006) eax:'
```

What value do you get?

**Comment by zawata** [comment]
I don't get anything?
I tired booting with both "cpuid" and "-cpuid" and i ran the debug script multiple times but grepping the system log returns nothing.
I'm sure i'm doing this correctly too.

**Comment by zawata** [comment]
man, 7 years... how time flies.

Closing because I don't even know if I still have the laptop I was experiencing this issue on.
