### ISSUE TITLE
No support for Skylake? (i7 6700K, iMac17,1)

### ISSUE THREAD

**Issue by Turboman99** [Piker-Alpha/ssdtPRGen.sh#208]
When I try to run ssdtPRGen according to the instruction here and on tonymacx86, I get this error:

System information: Mac OS X 10.11.2 (15C50)
Brandstring 'Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Not in the one from the master branch. Only in the Beta branch.

**Comment by gfoury** [comment]
Make sure you remove `~/Library/ssdtPRGen` when switching branches.

**Comment by kebuder** [comment]
Hi Piker,

I reinstalled my mackintosh yesterday. first thing i did was try to get the power management working. I have an intel i7 6700hq. Last time i tried to run the script (beta) it automatically found the processor. this time also with the beta it does not find it. Do i need to set some settings? smbios? i tried the new macbook 9,1 you found. Does not work. Hope you can help!

**Comment by Piker-Alpha** [comment]
The data for the Intel i7-6700HQ can be found in Data/Skylake.cfg so it should work. Please check your copy of this file, and also add the output of the script (-d 3).

**Comment by kebuder** [comment]
Hi Piker, 
The error was something like: incorrect file end at line 107 in Skylake.cfg. I cant check it right now but you probably missed a comma somewhere :P I fixed it by downloading the old Skylake.cfg file. worked like a charm. Thanks allot!

**Comment by Piker-Alpha** [comment]
Ok. Fixed with commit 159 Thanks!

**Comment by kebuder** [comment]
No problem, Thank you for the script (and other hackintosh related stuff). 
Got to fix my hd530 now... saw your device id list so i'm going to give them a try.

**Comment by Piker-Alpha** [comment]
@Turboman99,

Can you please confirm that this bug is fixed now? Please confirm and close this issue. Thanks!

**Comment by Turboman99** [comment]
Got it, thanks for your help.
