### ISSUE TITLE
i5 6200u errors with' unterminated substitute pattern' and Invalid character

### ISSUE THREAD

**Issue by xinyuwufei** [Piker-Alpha/ssdtPRGen.sh#214]
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v18.2 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.4 (15E65)
Brandstring: "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz"

Version: models.cfg v160 / Ivy Bridge.cfg v0

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookAir6,2' with board-id [Mac-7DF21CB3ED6977E5]
Skylake Core i5-6200U processor [0x406E3] setup [0x]
With a maximum TDP of 15 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 2300 MHz)
Number of Turbo States: 5 (2400-2800 MHz)
Number of P-States: 24 (500-2800 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for -e CPU0 (C1,C3,C6,C7)
Injected C-States for -e CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x instead of 0x09)
sed: 1: "s/^[\n]*
Error://
": unterminated substitute pattern

Error:
Do you want to continue (y/n)? y

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160409-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

Compiler aborting due to parser-detected syntax error(s)
/Users/wufei/Library/ssdtPRGen/ssdt.dsl     20:     External (_PR_.-e CPU0, DeviceObj)
Error    6126 -                                                   ^ Invalid character (.), expecting ASL keyword or name

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     20:     External (_PR_.-e CPU0, DeviceObj)
Error    6126 -                                                    ^ syntax error, unexpected PARSEOP_EXP_SUBTRACT, expecting ')'

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     21:     External (_PR_.-e CPU1, DeviceObj)
Error    6126 -                                                   ^ Invalid character (.), expecting ASL keyword or name

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     21:     External (_PR_.-e CPU1, DeviceObj)
Error    6126 -                                                    ^ syntax error, unexpected PARSEOP_EXP_SUBTRACT, expecting ')'

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     22:     External (_PR_.-e CPU2, DeviceObj)
Error    6126 -                                                   ^ Invalid character (.), expecting ASL keyword or name

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     22:     External (_PR_.-e CPU2, DeviceObj)
Error    6126 -                                                    ^ syntax error, unexpected PARSEOP_EXP_SUBTRACT, expecting ')'

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     23:     External (_PR_.-e CPU3, DeviceObj)
Error    6126 -                                                   ^ Invalid character (.), expecting ASL keyword or name

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     23:     External (_PR_.-e CPU3, DeviceObj)
Error    6126 -                                                    ^ syntax error, unexpected PARSEOP_EXP_SUBTRACT, expecting ')'

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     25:     Scope (_PR_.-e CPU0)
Error    6126 -                                                ^ Invalid character (.), expecting ASL keyword or name

/Users/wufei/Library/ssdtPRGen/ssdt.dsl     25:     Scope (_PR_.-e CPU0)
Error    6126 -                                                 ^ syntax error, unexpected PARSEOP_EXP_SUBTRACT, expecting ')'

/Users/wufei/Library/ssdtPRGen/ssdt.dsl    174: 
Error    6126 - syntax error, unexpected PARSEOP_SCOPE, expecting $end and premature End-Of-File

ASL Input:     /Users/wufei/Library/ssdtPRGen/ssdt.dsl - 174 lines, 10537 bytes, 35 keywords

Compilation complete. 11 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
Do you want to open ssdt.dsl (y/n)? y

on[ ssdt.dsl](https://github.com/meimeidyyd/temp/blob/master/ssdt.dsl), it adds '-e 'on every scope:

   External (_PR_.-e CPU0, DeviceObj)
    External (_PR_.-e CPU1, DeviceObj)
    External (_PR_.-e CPU2, DeviceObj)
    External (_PR_.-e CPU3, DeviceObj)

if i replace by the empty character,  errors are gone but i'm not sure if it is the right way

thanks in advance!

**Comment by Piker-Alpha** [comment]
Please change the value on this line:
`https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/ssdtPRGen.sh#L161`
to 0 and run the script again.

**Comment by Piker-Alpha** [comment]
Closing due to lack of response!
