### ISSUE TITLE
Can't get ssdtPRGen to run...

### ISSUE THREAD

**Issue by kildufg** [Piker-Alpha/ssdtPRGen.sh#216]
All I see when I run the installer is this...

Do I need something else installed... xcode perhaps? Or am I doing something wrong here.

I am trying to create an ssdt for an i7 Acer S3. I have successfully patched a full DSDT... wifi sound and graphics all good... just need the SSDT.

Thanks.

![screen shot 2016-04-29 at 09 32 14](https://cloud.githubusercontent.com/assets/18708089/14911513/c6fa9dae-0ded-11e6-8ccf-c04c886250e0.png)

**Comment by Piker-Alpha** [comment]
Please read the README and use that. Nothing else. This is old stuff.
