### ISSUE TITLE
【solved】'No ACPI Processor declarations found in the DSDT' for E3 1241 v3

### ISSUE THREAD

**Issue by joyqing** [Piker-Alpha/ssdtPRGen.sh#217]
@Piker-Alpha 
Hi boss,
pls help me to solve my cpu ssdt problem. See the attachment log.txt pls.
I can find the Scope (_PR) in the DSDT.aml (both original or patched) but still get this warning:

Scope (_PR)
    {
        Processor (CPU0, 0x01, 0x00001810, 0x06) {}
        Processor (CPU1, 0x02, 0x00001810, 0x06) {}
        Processor (CPU2, 0x03, 0x00001810, 0x06) {}
        Processor (CPU3, 0x04, 0x00001810, 0x06) {}
        Processor (CPU4, 0x05, 0x00001810, 0x06) {}
        Processor (CPU5, 0x06, 0x00001810, 0x06) {}
        Processor (CPU6, 0x07, 0x00001810, 0x06) {}
        Processor (CPU7, 0x08, 0x00001810, 0x06) {}
    }

any help will be appreciated

[log.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/243467/log.txt)

**Comment by Piker-Alpha** [comment]
You don't need to use all the arguments that you used, and you _definitely_ don't have 4 processors. 

Try a run without the arguments and when that still fails, then please add your DSDT.aml and APIC.aml

**Comment by joyqing** [comment]
thx boss. sovled

**Comment by ghost** [comment]
@joyqing Hi. The power management is working 100%? The x86platformplugin is loading?

I own the same processor you, but I can not make the x86platformplugin be loaded without enabling the P and C-states in clover. But to enable them, I lose various power states.

**Comment by Piker-Alpha** [comment]
Cool. Closing issue!
