### ISSUE TITLE
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)

### ISSUE THREAD

**Issue by eembsen** [Piker-Alpha/ssdtPRGen.sh#218]
Hi Pike,

I ran the script off the Beta branch and all goes well except for this warning. Here's the complete output:

System information: Mac OS X 10.11.4 (15E65)
Brandstring: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"

Notice: Downloading extractACPITables.zip ...
Notice: Downloading Sandy Bridge.cfg ...
Notice: Downloading Ivy Bridge.cfg ...
Notice: Downloading Haswell.cfg ...
Notice: Downloading Broadwell.cfg ...
Notice: Downloading Skylake.cfg ...
Version: models.cfg v160 / Sandy Bridge.cfg v0

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Notice: Downloading Restrictions.cfg ...
Generating ssdt.dsl for a 'iMac17,1' with board-id [Mac-65CE76090165799A]
Skylake Core i7-6700K processor [0x506E3] setup [0x0705]
With a maximum TDP of 91 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 2 (4100-4200 MHz)
Number of P-States: 35 (800-4200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)
Notice: Downloading iasl.zip ...

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/erwin/Library/ssdtPRGen/ssdt.dsl - 364 lines, 11334 bytes, 73 keywords
AML Output:    /Users/erwin/Library/ssdtPRGen/ssdt.aml - 2375 bytes, 28 named objects, 45 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Is the warning something I should worry about?

**Comment by Piker-Alpha** [comment]
No. That's just a remnant of a previous version.
