### ISSUE TITLE
Skylake i7-6770HQ is just like i7-6700HQ (but with Iris Pro 580)

### ISSUE THREAD

**Issue by RehabMan** [Piker-Alpha/ssdtPRGen.sh#227]
The line in Skylake.cfg for i7-6700HQ can be duplicated for i7-6700HQ:

```
i7-6770HQ,45,500,2600,3500,4,8
```

**Comment by Piker-Alpha** [comment]
I see that we are missing more Q1 and Q2 models. File updated.

Thank you for the reminder!

**Comment by RehabMan** [comment]
Thanks for the quick fix... People with the Skull Canyon NUC will appreciate...
