### ISSUE TITLE
i7 5820k SSDT

### ISSUE THREAD

**Issue by jura11** [Piker-Alpha/ssdtPRGen.sh#228]
Hi Pike 

I have problem with creating SSDT,not sure if this is error or what,can you help me there

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
##              v15.6 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/Jura1/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.5 (14F1808)
Brandstring 'Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz'

Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core i7-5820K processor [0x306F2] setup [0x0507]
With a maximum TDP of 140 Watt, as specified by Intel
Number logical CPU's: 12 (Core Frequency: 3300 MHz)
Number of Turbo States: 4 (3400-3700 MHz)
Number of P-States: 26 (1200-3700 MHz)
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Warning: 'system-type' may be set improperly (1 instead of 3)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/Jura1/Library/ssdtPRGen/ssdt.dsl - 357 lines, 10496 bytes, 95 keywords
AML Output:    /Users/Jura1/Library/ssdtPRGen/ssdt.aml - 2637 bytes, 40 named objects, 55 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Thanks in advance,Jura

**Comment by Piker-Alpha** [comment]
I don't support older version of the script anymore, but you get that warning (not an error) because the MacPro6,1 is a workstation and then 'system-type' should be set to 3 not 1 (for desktop PC's).
