### ISSUE TITLE
IOREG GTX 1080

### ISSUE THREAD

**Issue by dr3nan** [Piker-Alpha/ssdtPRGen.sh#230]
I hope this is the right place to contact you!
[IOREG i7 6700 Z170X 1080.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/329961/IOREG.i7.6700.Z170X.1080.zip)

**Comment by Piker-Alpha** [comment]
This is what I get when I try to open the ioreg: "The document “IOREG i7 6700 Z170X 1080” could not be opened. It appears to be corrupted."

**Comment by dr3nan** [comment]
Hello Pike! Perhaps is the compression tool I used to compress the file. Have you tried the unarchiver from the mac app store? It usually does the trick, or maybe a server firewall is causing the file corruption.

**Comment by dr3nan** [comment]
Hello Pike,

Had a motorbike crash last week and I have been away from any kind of electronic device since! (nothing serious, but quite scolded)

I’ll attach the IOREG here uncompressed, lets hope you can use it.

BTW, I’m interested in testing the M.2 patch for El Capitan you mentioned on your blog, please send me what you need me to test.

Regards

Dolgar.

**Comment by Piker-Alpha** [comment]
I'm sorry to hear about your accident, but good to know that you have survived. Anyway. Attached you'll find the binary for El Capitan.
p.s. No time right now to look at the ioreg but Ill check it tonight.

**Comment by dr3nan** [comment]
Hello again, theres nothing attached to the email.. Might I be missing something..?

**Comment by Piker-Alpha** [comment]
I can see the attachment in the e-mail in my Sent box. Let's try again...

**Comment by dr3nan** [comment]
Nope, didn’t get it.. Usually I’d get a paperclip icon next to the sender’s name, but not in this case.

**Comment by dr3nan** [comment]
Ok, I think I know why, I just sent the last mail from my email app and attached an image of the missing icon location I just mentioned, and checking in the github thread, It doesn't appear.. Maybe you should attach the file here in the github thread?

**Comment by Piker-Alpha** [comment]
Right. I was so in a hurry that I failed to catch that this request was coming from a Github notification and not ordinary e-mail... and in case you want the patched filed. Just e-mail me ;)

**Comment by dr3nan** [comment]
I’d love to, but I don’t know your e-mail lol.. it only replies to github mails :S

**Comment by Piker-Alpha** [comment]
https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/ssdtPRGen.sh#L7
