### ISSUE TITLE
SCK0 is missing for 5960X SSDT.aml

### ISSUE THREAD

**Issue by nmano** [Piker-Alpha/ssdtPRGen.sh#235]
SCK0 is missing for 5960X SSDT.aml
My Board is X99gaming G1 wifi Bios is F22J
 
I fixed missing SCK0
Scope (_SB.SCK0.CP00)
Now X86PlatformPlugin and X86PlatformShim are  Loaded.
 
SCK0 simple patch Open your SSDT.aml click Edit button-Find-Find and Replace
 
Find              _SB_
Replace All   _SB_.SCK0
 
Find               _SB
 
Replace All    _SB.SCK0
[Archive.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/344803/Archive.zip)

**Comment by Piker-Alpha** [comment]
I don't think that this is the right way to solve this issue, and you forgot to mention the most important things like:

Which version of the script have you used?
What arguments did you use?
What was the terminal out?
Have you seen any errors and/or warnings?
Where is you DSDT.aml and APIC.aml?

**Comment by nmano** [comment]
I used new beta version.
curl -o ~/ssdtPRGen.sh https://raw.githubusercontent.com/Piker-Alpha/ssdtPRGen.sh/master/ssdtPRGen.sh

chmod +x ~/ssdtPRGen.sh

~/ssdtPRGen.sh

Look My DSDT
[DSDT.aml.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/345104/DSDT.aml.zip)

**Comment by nmano** [comment]
Last login: Fri Jul  1 19:12:38 on ttys000
manoranjansPro2:~ manoranjan$ curl -o ~/ssdtPRGen.sh https://raw.githubusercontent.com/Piker-Alpha/ssdtPRGen.sh/Beta/ssdtPRGen.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147k  100  147k    0     0   141k      0  0:00:01  0:00:01 --:--:--  141k
manoranjansPro2:~ manoranjan$ chmod +x ~/ssdtPRGen.sh
manoranjansPro2:~ manoranjan$ ~/ssdtPRGen.sh

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen

##              v18.8 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.5 (15F34)
Brandstring: "Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz"

Notice: Downloading extractACPITables.zip ...
Notice: Downloading Sandy Bridge.cfg ...
Notice: Downloading Ivy Bridge.cfg ...
Notice: Downloading Haswell.cfg ...
Version: models.cfg v160 / Sandy Bridge.cfg v150

Scope (_SB_) {67376 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Notice: Downloading Restrictions.cfg ...
Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core i7-5960X processor [0x306F2] setup [0x0507]
With a maximum TDP of 140 Watt, as specified by Intel
Number logical CPU's: 16 (Core Frequency: 3000 MHz)
Number of Turbo States: 4 (3100-3400 MHz)
Number of P-States: 23 (1200-3400 MHz)
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Warning..: FrequencyVectors missing in Mac-F60DEB81FF30ACF6.plist
     Download https://github.com/Piker-Alpha/freqVectorsEdit.sh to fix this
Warning: 'system-type' may be set improperly (1 instead of 3)
Notice: Downloading iasl.zip ...

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/manoranjan/Library/ssdtPRGen/ssdt.dsl - 408 lines, 11302 bytes, 121 keywords
AML Output:    /Users/manoranjan/Library/ssdtPRGen/ssdt.aml - 2808 bytes, 52 named objects, 69 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Users/manoranjan/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n
manoranjansPro2:~ manoranjan$

**Comment by nmano** [comment]
[ssdtPRGen.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/345114/ssdtPRGen.zip)

**Comment by Piker-Alpha** [comment]
Thanks you for reporting this issue here. Should now be fixed in ssdtPRGen.sh v18.9 so please give it a try and close this issue if it works. Thanks.

**Comment by nmano** [comment]
Thank you so much.Its worked now.I tested it.
