### ISSUE TITLE
Can't generate ssdt for i7 960

### ISSUE THREAD

**Issue by sofatiger51** [Piker-Alpha/ssdtPRGen.sh#241]
I have use your script generating ssdt for Sandy Bridge i5 2450M, Haswell Xeon E3-1225V3,i7 920
but try several time ssdtPRgen.sh but can't generate ssdt for i7 960. Below error outputs:
System information: Mac OS X 10.10.5 (14F1808)
Brandstring 'Intel(R) Core(TM) i7 CPU 960 @ 3.20GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
1.) Add the processor data from ark.intel.com to: ~ /Library/ssdtPRGen/Data/User Defined.cfg
2.) Use: ./ssdtPRGen.sh -p i7-960
