### ISSUE TITLE
Missing processor data Broadwell-E 6800k

### ISSUE THREAD

**Issue by ekwipt** [Piker-Alpha/ssdtPRGen.sh#244]
Processor Number
       TDP 140 W
       Low Frequency Mode (use AppleIntelInfo.kext) (this immediately crashes my system using the "kextload ~/Desktop/AppleIntelInfo.kext" in terminal
       Base Frequency 3.4 GHz
       Max Turbo Frequency 3.8 GHz
       Cores 6
       Threads 12

**Comment by ekwipt** [comment]
I downloaded the latest beta, and the processor is i the cfg file, but it just doesn't work, i've tried with flags: -p 'i7-6800K' -f 3400 -turbo 3600
But still the same error

**Comment by Piker-Alpha** [comment]
Are you using [this](https://github.com/Piker-Alpha/AppleIntelInfo/commit/81af2aef24613883e0d1f506d5af672c46cabec1) update of AppleIntelInfo.kext? That one works perfectly fine here.

And all that you really need is: `./ssdtPRGen.sh -turbo 4000`

Either that or any other higher turbo value that you use in the BIOS for when you OC your setup.

What's that about: "But still the same error"? What error are you referring to?

**Comment by ekwipt** [comment]
Hi Piker-Alpha thanks for reaching out, much appreciated, i'm using the latest update for AppleIntelInfo.kext now and pulled the following info for the chip:

> AppleIntelInfo.kext v1.5 Copyright © 2012-2016 Pike R. Alpha. All rights reserved
> 
> ## Settings:
> 
> logMSRs............................: 1
> logIGPU............................: 0
> logCStates.........................: 1
> logIPGStyle........................: 1
> InitialTSC.........................: 0x173200faa1e
> MWAIT C-States.....................: 8480
> 
> ## Model Specific Registers
> 
> MSR_CORE_THREAD_COUNT......(0x35)  : 0x6000C
> MSR_PLATFORM_INFO..........(0xCE)  : 0x20080C3BF3812200
> MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x3
> MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x0
> IA32_MPERF.................(0xE7)  : 0x12DD9764DF
> IA32_APERF.................(0xE8)  : 0x125D33B99F
> MSR_FLEX_RATIO.............(0x194) : 0xE0000
> MSR_IA32_PERF_STATUS.......(0x198) : 0x22F300002300
> MSR_IA32_PERF_CONTROL......(0x199) : 0x2400
> IA32_CLOCK_MODULATION......(0x19A) : 0x0
> IA32_THERM_STATUS..........(0x19C) : 0x884D0000
> IA32_MISC_ENABLES..........(0x1A0) : 0x810089
> MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
> MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x2323232323232424
> IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x7
> MSR_POWER_CTL..............(0x1FC) : 0x2304005B
> MSR_RAPL_POWER_UNIT........(0x606) : 0xA0E03
> MSR_PKG_POWER_LIMIT........(0x610) : 0x7FFD00014EA82
> MSR_PKG_ENERGY_STATUS......(0x611) : 0xB22A66B
> MSR_PKG_POWER_INFO.........(0x614) : 0x1700460
> MSR_PP0_POWER_LIMIT........(0x638) : 0x14FFD0
> MSR_PP0_ENERGY_STATUS......(0x639) : 0x0
> MSR_PKGC6_IRTL.............(0x60b) : 0x0
> MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
> MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
> IA32_TSC_DEADLINE..........(0x6E0) : 0x17322891A50
> 
> ## CPU Ratio Info:
> 
> CPU Low Frequency Mode.............: 1200 MHz
> CPU Maximum non-Turbo Frequency....: 3400 MHz
> CPU Maximum Turbo Frequency........: 3600 MHz
> CPU P-States [ (12) 31 35 ]
> CPU P-States [ 12 31 34 (35) ]
> CPU P-States [ (12) 19 31 34 35 ]
> CPU P-States [ (12) 19 25 31 34 35 ]
> CPU P-States [ (12) 19 22 25 31 34 35 ]
> CPU P-States [ (12) 19 22 24 25 31 34 35 ]
> CPU P-States [ (12) 19 22 24 25 31 33 34 35 ]
> CPU P-States [ (12) 19 22 24 25 27 31 33 34 35 ]
> CPU P-States [ (12) 19 22 24 25 27 29 31 33 34 35 ]
> CPU P-States [ (12) 19 21 22 24 25 27 29 31 33 34 35 ]
> CPU P-States [ (12) 19 21 22 24 25 27 28 29 31 33 34 35 ]
> CPU P-States [ (12) 19 21 22 24 25 27 28 29 30 31 33 34 35 ]
> CPU P-States [ 12 19 21 22 24 25 27 28 29 30 31 32 33 34 (35) ]
> CPU P-States [ (12) 19 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 16 19 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 16 17 19 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ 12 16 17 19 20 21 22 24 25 26 27 28 29 30 31 32 33 34 (35) ]
> CPU P-States [ (12) 14 16 17 19 20 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 13 14 16 17 19 20 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 13 14 16 17 18 19 20 21 22 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 13 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 ]
> CPU P-States [ (12) 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 ]

**Comment by ekwipt** [comment]
ok great 

> ./ssdtPRGen.sh -turbo 4000

worked, I've placed the SSDT in the Clover folder and it's rebooted

**Comment by ekwipt** [comment]
AppleIntelInfo.kext v1.5 Copyright © 2012-2016 Pike R. Alpha. All rights reserved

## Settings:

logMSRs............................: 1
logIGPU............................: 0
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0xa3be55e2f9
MWAIT C-States.....................: 8480

## Model Specific Registers

MSR_CORE_THREAD_COUNT......(0x35)  : 0x6000C
MSR_PLATFORM_INFO..........(0xCE)  : 0x20080C3BF3812200
MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x3
MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x0
IA32_MPERF.................(0xE7)  : 0xB5578D459
IA32_APERF.................(0xE8)  : 0xB2115D8A2
MSR_FLEX_RATIO.............(0x194) : 0xE0000
MSR_IA32_PERF_STATUS.......(0x198) : 0x22F300002300
MSR_IA32_PERF_CONTROL......(0x199) : 0x2400
IA32_CLOCK_MODULATION......(0x19A) : 0x0
IA32_THERM_STATUS..........(0x19C) : 0x88520000
IA32_MISC_ENABLES..........(0x1A0) : 0x810089
MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x2323232323232424
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x7
MSR_POWER_CTL..............(0x1FC) : 0x2304005B
MSR_RAPL_POWER_UNIT........(0x606) : 0xA0E03
MSR_PKG_POWER_LIMIT........(0x610) : 0x7FFD00014EA82
MSR_PKG_ENERGY_STATUS......(0x611) : 0x53D3328
MSR_PKG_POWER_INFO.........(0x614) : 0x1700460
MSR_PP0_POWER_LIMIT........(0x638) : 0x14FFD0
MSR_PP0_ENERGY_STATUS......(0x639) : 0x0
MSR_PKGC6_IRTL.............(0x60b) : 0x0
MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
IA32_TSC_DEADLINE..........(0x6E0) : 0xA3C0D07269

## CPU Ratio Info:

CPU Low Frequency Mode.............: 1200 MHz
CPU Maximum non-Turbo Frequency....: 3400 MHz
**CPU Maximum Turbo Frequency........: 3600 MHz**
CPU P-States [ (12) 33 35 ]
CPU P-States [ (12) 30 33 35 ]
CPU P-States [ 12 30 31 33 (35) ]
CPU P-States [ 12 30 31 33 34 (35) ]
CPU P-States [ (12) 30 31 32 33 34 35 ]
CPU P-States [ (12) 28 30 31 32 33 34 35 ]

**Comment by ekwipt** [comment]
Being very noob at this Piker Alpha, should i bother trying to get: freqVectorsEdit.sh-master
Going as of yet, i'm still on 10.11.6, and see you are running the beta of 10.12

**Comment by ekwipt** [comment]
Not sure if this is working right because the chip is supposed to be running at 3800Mhz in Maximum Turbo state as per the intel info sheet:

http://ark.intel.com/products/94189/Intel-Core-i7-6800K-Processor-15M-Cache-up-to-3_60-GHz

edit: ahhh i read this on your blog, so maybe it IS WORKING!

https://pikeralpha.wordpress.com/2016/06/03/intel-turbo-boost-max-technology-3-0/

3600mhz is the highest it will go under OSX, unless I try and overclock, thing is i tried to stress test in terminal and using Intel power gadget as a guide and the chip only turbo boosts to 3.5Mhz WEIRD

![screen shot 2016-08-02 at 8 05 58 pm](https://cloud.githubusercontent.com/assets/20624482/17330197/42632676-5909-11e6-99ab-b5c9a433ef86.png)

**Comment by Piker-Alpha** [comment]
You can set the core ratio for a single active core to 38 and run: 
`.//ssdtPRGen -turbo 3800`
Works just fine. That will change things in a positive way.
