### ISSUE TITLE
Abort when building for i5-660

### ISSUE THREAD

**Issue by BakaPhoenix** [Piker-Alpha/ssdtPRGen.sh#245]
I know this cpu is not supported so i took the info from ark and manually added them with this input:
`~/ssdtPRGen.sh -f 4030 -p 'i5-660' -turbo 4030 -tdp 73 -lfm 1400 -cpus 2 -l 4`
(yes i'm overclocking the cpu)
And get this as return:
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v18.9 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i5 CPU 660 @ 3.33GHz"

Override value: (-f) clock frequency, now using: 4030 MHz!
Override value: (-p) processor model, now using: i5-660!
Override value: (-turbo) maximum (turbo) frequency, now using: 4030 MHz!
Override value: (-t) maximum TDP, now using: 73 Watt!
Override value: (-lfm) low frequency mode, now using: 1400!
Override value: (-cpus) number of processors, now using: 2!
Override value: (-l) number of logical processors, now using: 4!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

What i'm doing wrong?

**Comment by BakaPhoenix** [comment]
I created the User Define.cgf and put in:
`gUserDefinedCPUList=(`
`i5-660,73,1200,3330,3600,2,4`
`)`
http://ark.intel.com/products/43550/Intel-Core-i5-660-Processor-4M-Cache-3_33-GHz
Then when i input `./ssdtPRGen.sh`
I still get the unknown processor model.
What i'm doing wrong this time?

**Comment by Piker-Alpha** [comment]
1.) Missing argument. Use -p i5-660

2.) Missing data.  Please check out the examples that I added to User Defined.cfg.

**Comment by BakaPhoenix** [comment]
i changed the Usee Defined.cfg to
gUserDefinedCPUList=(
i5-660,73,1200,3330,3600,2,4
)

and used ./ssdtPRGen.sh -p i5-660 and still have the problem

**Comment by Piker-Alpha** [comment]
**1.**) You made a mistake; the last two parameters are missing (Again. See examples in said file).

**2.**) In which folder did you edit the file? 

**Note**: The script reads: "~/Library/ssdtPRGen/Data/User Defined.cfg" so make sure that you edit this file.

**Comment by BakaPhoenix** [comment]
Hi, sorry again, i managed to build the ssdt.aml this time, i put it in /Volumes/EFI/EFI/CLOVER/ACPI/patched/SSDT.aml and set it using clover configuration under Sorted Order as SSDT.aml
https://dl.dropbox.com/s/5myin8uxvnqdk9f/Screenshot%202016-08-13%2020.46.29.png?dl=0
the User Defined.cfg is 

`gUserDefinedCPUList=(
i5-660,73,1200,3330,3600,2,4,0,133
)
`

The problem is that with this set up the cpu only run on the lower multiplier (9) 
This the outputted SSDT:
https://dl.dropboxusercontent.com/u/5095587/SSDT.aml

I built the ssdt using the command:

`./ssdtPRGen.sh -p i5-660 -f 4000` because my cpu is overclocked to 4ghz
