### ISSUE TITLE
Error: Unknown processor model i7 950 

### ISSUE THREAD

**Issue by highnrg-duplicate** [Piker-Alpha/ssdtPRGen.sh#246]
this is what i get 
when i run ssdtPRGen.sh later ver that is on this site 
this is the output will love any help

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i7 CPU 950 @ 3.07GHz"

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by highnrg-duplicate** [comment]
well i tried this one as well with no go 
/ssdtPRGen.sh-Beta/ssdtPRGen.sh -f 3006 -p 'i7-950' -turbo 3330 -tdp 130 -cpus 4 -l 4

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen

##              v18.9 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i7 CPU 950 @ 3.07GHz"

Override value: (-f) clock frequency, now using: 3006 MHz!
Override value: (-p) processor model, now using: i7-950!
Override value: (-turbo) maximum (turbo) frequency, now using: 3330 MHz!
Override value: (-t) maximum TDP, now using: 130 Watt!
Override value: (-cpus) number of processors, now using: 4!
Override value: (-l) number of logical processors, now using: 4!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Please use search first – there are plenty of examples for unsupported processors.
