### ISSUE TITLE
Wrong data for i5-4590T

### ISSUE THREAD

**Issue by bolmen** [Piker-Alpha/ssdtPRGen.sh#247]
Hi,

it seems the entry for the Haswell i5-4590T is wrong:

Clock Speed is 2000 MHz, Max Turbo Frequency is 3000 MHz.

Entry should be: i5-4590T,35,800,2000,3000,4,4

Cheers,
Tim

**Comment by Piker-Alpha** [comment]
Thanks! Fixed (sorry, I referred to the wrong issues # in my commit).
