### ISSUE TITLE
Missing data for Xeon E5-2686 v3 (OEM of E5-2699 v3)

### ISSUE THREAD

**Issue by MtVinterest** [Piker-Alpha/ssdtPRGen.sh#249]
Hey I was trying to do a proper SSDT for my Xeon and X99 based system. 

System information: Mac OS X 10.11.6 (15G31)
Brandstring 'Intel(R) Xeon(R) CPU E5-2686 v3 @ 2.00GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...

Intel doesn't list this CPU in the ARK, so everything you need is gathered from CPU-World.
http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-2686%20v3.html

**Comment by Piker-Alpha** [comment]
There are dozens of OEM tray processors for which the data is missing, but you can easily add the missing data for your processor to 'Data/User Defined.cfg' 
`gUserDefinedCPUList=('E5-2686 v3',120,1200,2000,3500,18,36)`

**Comment by MtVinterest** [comment]
Okay, nice to know. Thank you Pike!

**Comment by MtVinterest** [comment]
**Okay, I don't know what I'm doing wrong right now. This is how I edited the User Defined.cfg:**

<img width="1013" alt="bildschirmfoto 2016-08-14 um 15 04 22" src="https://cloud.githubusercontent.com/assets/20917192/17649264/6d798b54-6230-11e6-9d27-f17333d954aa.png">

**And this is how I run the shell, but he seems to not register the changes in the .cfg**

_~ MtVinterest$ /Users/MtVinterest/Library/ssdtPRGen/ssdtPRGen.sh-Beta/ssdtPRGen.sh -p 'E5-2686 v3' -turbo 3500

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen

##              v19.0 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Xeon(R) CPU E5-2686 v3 @ 2.00GHz"

Override value: (-p) processor model, now using: E5-2686 v3!
Override value: (-turbo) maximum (turbo) frequency, now using: 3500 MHz!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done._

**Comment by Piker-Alpha** [comment]
Spaces are not allowed in the data and thus you should use: 'E5-2686 v3'. That should work.

**Comment by MtVinterest** [comment]
Okay, all my bad. Thanks for you help this work until there!
