### ISSUE TITLE
E5-2658 v3

### ISSUE THREAD

**Issue by kkieslich** [Piker-Alpha/ssdtPRGen.sh#250]
Hi,
although I know there are many threads mainly discussing the same problem, I didn't got any useful information from it. I'm having the above mentioned CPU with a X99 setup and having trouble to reach the max turbo frequency of 2.6 GHz (Windows). I get at max 2.3 GHz :/
I tried the script and just got the expected Unknown Processor Model
However I'm unable to add it to the Data Folder as it still doesn't recognize it. Is it just impossible or am I doing something wrong.

Thanks in Advance

**Comment by Piker-Alpha** [comment]
What is the output of:

```
sysctl machdep.cpu.brand_string
```

**Comment by kkieslich** [comment]
I get the following output:
`machdep.cpu.brand_string: Genuine Intel(R) CPU @ 2.00GHz`

**Comment by Piker-Alpha** [comment]
That is not a normal brandstring for [your processor](http://ark.intel.com/nl/products/81905/Intel-Xeon-Processor-E5-2658-v3-30M-Cache-2_20-GHz). It should be:

Intel(R) Xeon(R) CPU E5-2658 v3 @ 2.20GHz 

I don't know what the problem is. Or did you run that command in a VM?

The only solution that I can come up with right now is to run:

```
./ssdtPRGen.sh -p 'E5-2658 v3'
```

**Comment by kkieslich** [comment]
Thank you, it worked :) I thought I already tried it but now I'm getting full speedster support. I forgot to say that it is an ES version which could explain the weird brand string.

**Comment by Piker-Alpha** [comment]
Right. I should have known it.  Sort of expected. What do you get when you run:

```
machdep.cpu.model
```

**Comment by kkieslich** [comment]
Then I get:

machdep.cpu.model: 63

2016-08-11 19:55 GMT+02:00 Pike R. Alpha notifications@github.com:
