### ISSUE TITLE
system-type warning

### ISSUE THREAD

**Issue by llamafilm** [Piker-Alpha/ssdtPRGen.sh#251]
What does this warning mean?  I tried with `-target 3` for Broadwell, but it makes no difference.  I'm using a 6950x with Clover's FakeCPUID 0306F2.

```
Warning: 'cpu-type' may be set improperly (0x0402 instead of 0x0a02)
Warning: 'system-type' may be set improperly (1 instead of 3)
```

**Comment by Piker-Alpha** [comment]
The **-target** argument is used to specify the processor architecture: 

0 = Sandy Bridge
1 = Ivy Bridge
2 = Haswell
3 = Broadwell
4 = Skylake

Not to change the SMBIOS 'system-type'. You can change it with a Clover SMBIOS settings. 

1 = Desktop
2 = Notebook
3 = Workstations (like the Mac Pro)

The other warning, the one about the 'cpu-type' is another SMBIOS setting.

Hope this help... closing issue.
