### ISSUE TITLE
Mac6,1 - FrequencyVectors missing in Mac-F60DEB81FF30ACF6.plist

### ISSUE THREAD

**Issue by zebuscat** [Piker-Alpha/ssdtPRGen.sh#252]
I get the following 2 warnings when running the latest script on my i7-5820K / X99 Clover MacPro6,1 setup.
Is this a bug - or do I need to fix my config.plist ?

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v19.0 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz"

Override value: (-m) model, now using: MacPro6,1!
Override value: (-p) processor model, now using: i7-5820K!
Override value: (-turbo) maximum (turbo) frequency, now using: 4300 MHz!

Version: models.cfg v160 / Sandy Bridge.cfg v150

Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core i7-5820K processor [0x306F2] setup [0x0507]
With a maximum TDP of 140 Watt, as specified by Intel
Number logical CPU's: 12 (Core Frequency: 3300 MHz)
Number of Turbo States: 10 (3400-4300 MHz)
Number of P-States: 32 (1200-4300 MHz)
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Warning..: FrequencyVectors missing in Mac-F60DEB81FF30ACF6.plist
         Download https://github.com/Piker-Alpha/freqVectorsEdit.sh to fix this
Warning: 'system-type' may be set improperly (1 instead of 3)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/me/Library/ssdtPRGen/ssdt.dsl - 365 lines, 11095 bytes, 97 keywords
AML Output:    /Users/me/Library/ssdtPRGen/ssdt.aml - 2851 bytes, 40 named objects, 57 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Users/me/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? n
Do you want to open ssdt.dsl (y/n)? n

**Comment by Piker-Alpha** [comment]
Ehm. It's right there in front of you. Go download/run that script.

The warning about the system-type can be fixed with a SMBIOS setting in Clover (don't ask, I do not use Clover).
