### ISSUE TITLE
Unknown processor: Core M

### ISSUE THREAD

**Issue by franzpisto** [Piker-Alpha/ssdtPRGen.sh#254]
Hello, 
How can I solve this error?
I'm on an Asus UX305FA-FC061T.
Thank you in advance.

<img width="471" alt="schermata 2016-08-23 alle 03 26 17" src="https://cloud.githubusercontent.com/assets/21186319/17877246/ea62ea18-68e1-11e6-8fd1-ea984386343e.png">

**Comment by Piker-Alpha** [comment]
Hmm. It should read "M-5Y10" but perhaps not for OEM processors like in your ZenBook. Now you have a couple of options.

1.) You can add the processor data **5Y10,4.5,500,800,2000,2,4** to "Data/User Defined.cfg" 
2.) You can change _M-5Y10,4.5,500,800,2000,2,4_ into **5Y10,4.5,500,800,2000,2,4** in "Broadwell.cfg"

I would say go for option 1.

**Comment by franzpisto** [comment]
Okay I was able to solve, now my system is smooth like a Mac, thank you so much Piker!
If anyone will have the same problem, I solve that by download the zip via command tool, you will have now two data folder, insert the information that Piker provided in both folder (I follow both option) that must be the same, run the script, copy the ssdt generated file in patched, DON'T REBOOT NOW, install DummyX86PlatformPlugin.kext, reboot only now, you have now good cpu power management.

Thank you very much Piker! :)
