### ISSUE TITLE
G2030 problem help

### ISSUE THREAD

**Issue by freddy3k** [Piker-Alpha/ssdtPRGen.sh#255]
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/osx/Library/ssdtPRGen/Data
System information: Mac OS X 10.8.5 (12F45)
Brandstring 'Intel(R) Pentium(R) CPU G2030 @ 3.00GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

need help thanks

**Comment by Piker-Alpha** [comment]
Please provide the data for the GXXX processor series and I'll add it.

http://ark.intel.com/products/codename/29902/Ivy-Bridge#@Desktop

**Comment by freddy3k** [comment]
am sorry i forgot to add it
here is its details thanks

http://ark.intel.com/products/74749/Intel-Pentium-Processor-G2030-3M-Cache-3_00-GHz

**Comment by Piker-Alpha** [comment]
That is a link. Not the data that I need. 

Not that I am lazy or anything but it is your processor and I don't have a whole lot of spare time so there you have it. Please help me to help you.

Thanks.

**Comment by freddy3k** [comment]
am sorry am a nood at this kindly point me out what data you need and i'll try to gather everything out.. thanks again

**Comment by Piker-Alpha** [comment]
The data is there already. Make sure to delete ~/Library/ssdtPRGen/Data/Ivy Bridge.cfg

**Comment by freddy3k** [comment]
thanks it works

**Comment by Piker-Alpha** [comment]
Thanks for the confirmation. Closing issue... time for my Siesta ;)
