### ISSUE TITLE
Problem adding 'E5 2696 v3' in User Defined.cfg

### ISSUE THREAD

**Issue by fabiosun** [Piker-Alpha/ssdtPRGen.sh#256]
Hello Pike

I am trying to add my Oem CPU in User Defined.cfg with this data:
gUserDefinedCPUList=(
'E5-2696 v3’,150,1200,2300,3600,18,36

but I received this error below

fabios-Mac-Pro:~ fabio$ /Users/fabio/Downloads/ssdtPRGen.sh-Beta/ssdtPRGen.sh -p 'E5-2696 v3'

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v19.2 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz"

Override value: (-p) processor model, now using: E5-2696 v3!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

May I miss something?
Thank you
PS. Cpu has the same specs of 2699 v3 in Haskell.cfg data file except for tdp,  in my case is different (150)

**Comment by Piker-Alpha** [comment]
The script failed to locate the processor data for the given processor. One reason could be that you didn't add it to "~/Library/ssdtPRGen/Data/User Defined.cfg" but somewhere else.

**Tip**: Try this:

```
./ssdtPRGen.sh -p 'E5-2699 v3' -tdp 150
```

Now you won't need to add the data to Data/User Defined.cfg.

**Comment by fabiosun** [comment]
thank you pike without adding in Data/User Defined.cfg is working
I don't understand why it is not working with my Data/User Defined.cfg attached
[User Defined.cfg.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/439610/User.Defined.cfg.zip)

**Comment by Piker-Alpha** [comment]
There's an apostrophe ( ’ ) at the end of the processor model. Change that into a prime symbol (feet mark  ' ) or use a double prime (inch mark ") instead. That will work and cause less issues with TextEdit.

**Comment by fabiosun** [comment]
[User Defined.cfg.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/439776/User.Defined.cfg.zip)

Now seems to be well written but same problem..
Maybe a texWrangler editor problem?
However thank you for your time, I use previous line command you give me

**Comment by Piker-Alpha** [comment]
No problem, but you changed "v3" into "v4" ;)

**Comment by fabiosun** [comment]
yes it is the other  Broadwell EP  rig I have
And for this I'd have a tons of question for you! :-)
xcpm, kernel patch ,vectors..an so on! :-))
But this is the wrong place i Think
