### ISSUE TITLE
I7-6700HQ

### ISSUE THREAD

**Issue by ettoreribaudo** [Piker-Alpha/ssdtPRGen.sh#259]
Good morning Sirs, i have a problem with ssdt.aml, i changed parameters but is the result.

System information: Mac OS X 10.11.6 (15G1004)
Brandstring: "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz"

now: 150
latest: 150
Version: models.cfg v160 / Ivy Bridge v

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBook9,1' with board-id [Mac-9AE82516C7C6B903]
Skylake Core i7-6700HQ processor [0x506E3] setup [0x0705]
With a maximum TDP of 45 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 2600 MHz)
Number of Turbo States: 9 (2700-3500 MHz)
Number of P-States: 31 (500-3500 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/ettore/Library/ssdtPRGen/ssdt.dsl - 360 lines, 12220 bytes, 73 keywords
AML Output:    /Users/ettore/Library/ssdtPRGen/ssdt.aml - 2388 bytes, 28 named objects, 45 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

**Comment by Piker-Alpha** [comment]
What problem? And please do not remove the header with version information. Thanks.

**Comment by ettoreribaudo** [comment]
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v19.4 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G1004)
Brandstring: "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz"

now: 150
latest: 150
Version: models.cfg v160 / Ivy Bridge v


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBook9,1' with board-id [Mac-9AE82516C7C6B903]
Skylake Core i7-6700HQ processor [0x506E3] setup [0x0705]
With a maximum TDP of 45 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 2600 MHz)
Number of Turbo States: 9 (2700-3500 MHz)
Number of P-States: 31 (500-3500 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/ettore/Library/ssdtPRGen/ssdt.dsl - 360 lines, 12220 bytes, 73 keywords
AML Output:    /Users/ettore/Library/ssdtPRGen/ssdt.aml - 2388 bytes, 28 named objects, 45 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
-------------------------------------------------------------------------------------------------

The problem is that my cpu is Skyline i7-6700HQ, i tried various smbios in clover but noting, see error "warning"; your version is: model.cfg v160 / ivy Bridge v.
Please verify.
Regards
Ettore

**Comment by Piker-Alpha** [comment]
Right. Got it. Thank you for reporting this here. Please try ssdtPRGen.sh v19.6

**Comment by ettoreribaudo** [comment]
Thanks for update, you have correct the model, but the error of C-state Injected is the same.


System information: Mac OS X 10.11.6 (15G1004)
Brandstring: "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz"

Version: models.cfg v160 / Skylake.cfg v193


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBook9,1' with board-id [Mac-9AE82516C7C6B903]
Skylake Core i7-6700HQ processor [0x506E3] setup [0x0705]
With a maximum TDP of 45 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 2600 MHz)
Number of Turbo States: 9 (2700-3500 MHz)
Number of P-States: 31 (500-3500 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/ettore/Library/ssdtPRGen/ssdt.dsl - 360 lines, 12220 bytes, 73 keywords
AML Output:    /Users/ettore/Library/ssdtPRGen/ssdt.aml - 2388 bytes, 28 named objects, 45 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

**Comment by Piker-Alpha** [comment]
And? What exactly is it that you are talking about?

**Comment by ettoreribaudo** [comment]
I'm talking about mistakes, the i7-6700HQ CPU is not recognized correctly, there are injections. I inserted properly SMBIOS is macbook 9.1 Skyline but I warning problems, look.

**Comment by Piker-Alpha** [comment]
You can fix the cpu-type warning with [https://clover-wiki.zetam.org/Configuration/CPU#cpu_type](https://clover-wiki.zetam.org/Configuration/CPU#cpu_type)
