### ISSUE TITLE
Skylake Processors

### ISSUE THREAD

**Issue by macordie** [Piker-Alpha/ssdtPRGen.sh#260]
Will ssdPRGen.sh be updated with the INTEL Skylake profiles?  Hoping that Native CPU management will clear up a wake from sleep issue.  Thank you.

**Comment by Piker-Alpha** [comment]
[Skylake is already supported](https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/Skylake.cfg).

**Comment by macordie** [comment]
Thank you, I pulled an old version.   

Also, I would like to say thank you again. This script works great and sleep/wake are now fully supported.
