### ISSUE TITLE
Low number of P-States, C-States disabled/unsupported and processor running at 3.8Mhz for Broadwell-E 6800K

### ISSUE THREAD

**Issue by ekwipt** [Piker-Alpha/ssdtPRGen.sh#261]
hi Piker-Alpha, 

I was hoping I could get some help with generating my ssdt.aml.

I was concerned with the following lines regarding c -states:

**C3 State Auto Demotion............. : 0 (disabled/unsupported)
- C1 State Auto Demotion............. : 0 (disabled/unsupported)
- C3 State Undemotion................ : 0 (disabled/unsupported)
- C1 State Undemotion................ : 0 (disabled/unsupported)
- Package C-State Auto Demotion...... : 0 (disabled/unsupported)
- Package C-State Undemotion......... : 0 (disabled/unsupported)**

Also concered with the following P-State situation (only two P-States:

**CPU P-States [ 37 (38) ]**

Also my CPU is running at 3.8Mhz at all times, so doesn't seem to be ramping up and down during times of idle/In need of power

(i've added a screenshot for reference)

I have the following hardware:
Motherboard: Gigabyte-X99P-SLi
CPU - Intel Broadwell-E i7-6800K

Running Sierra PB 6, with Clover 4.32

I have attached my IORegistry Explorer for reference.

Any other info you need please ask

I get the following output from AppleIntelInfo.kext v1.6:

```
AppleIntelInfo.kext v1.6 Copyright © 2012-2016 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 1
logIGPU............................: 0
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0xf055d016146 (485 MHz)
MWAIT C-States.....................: 8480

Model Specific Registers (MSRs)
---------------------------------------

MSR_CORE_THREAD_COUNT..........(0x35)  : 0x6000C
----------------------------------------
 - Core Count......................... : 6
 - Thread Count....................... : 12

MSR_PLATFORM_INFO..............(0xCE)  : 0x20080C3BF3812200
----------------------------------------
 - Maximum Non-Turbo Ratio............ : 34
 - Ratio Limit for Turbo Mode......... : 1 (programmable)
 - TDP Limit for Turbo Mode........... : 1 (programmable)
 - Low Power Mode Support............. : 1 (LPM supported)
 - Number of ConfigTDP Levels......... : 1 (additional TDP level(s) available)
 - Maximum Efficiency Ratio........... : 12
 - Minimum Operating Ratio............ : 8

MSR_PMG_CST_CONFIG_CONTROL.....(0xE2)  : 0x403
----------------------------------------
 - I/O MWAIT Redirection Enable....... : 1 (enabled, IO read of MSR(0xE4) mapped to MWAIT)
 - CFG Lock........................... : 0 (MSR not locked)
 - C3 State Auto Demotion............. : 0 (disabled/unsupported)
 - C1 State Auto Demotion............. : 0 (disabled/unsupported)
 - C3 State Undemotion................ : 0 (disabled/unsupported)
 - C1 State Undemotion................ : 0 (disabled/unsupported)
 - Package C-State Auto Demotion...... : 0 (disabled/unsupported)
 - Package C-State Undemotion......... : 0 (disabled/unsupported)

MSR_PMG_IO_CAPTURE_BASE........(0xE4)  : 0x10414
----------------------------------------
 - LVL_2 Base Address................. : 0x414
 - C-state Range...................... : 1 (C6 is the max C-State to include
)

IA32_MPERF.....................(0xE7)  : 0xE1EB81DAF3
IA32_APERF.....................(0xE8)  : 0xFBE414C02F
MSR_0x150......................(0x150) : 0x0

MSR_FLEX_RATIO.................(0x194) : 0xE0000
----------------------------------------

MSR_IA32_PERF_STATUS...........(0x198) : 0x259C00002600
----------------------------------------
 - Current Performance State Value.... : 0x2600

MSR_IA32_PERF_CONTROL..........(0x199) : 0x2600
----------------------------------------
 - Target performance State Value..... : 0x2600
 - Intel Dynamic Acceleration......... : 0 (IDA engaged)

IA32_CLOCK_MODULATION..........(0x19A) : 0x0
IA32_THERM_STATUS..............(0x19C) : 0x883C0000

IA32_MISC_ENABLES..............(0x1A0) : 0x850089
----------------------------------------
 - Fast-Strings....................... : 1 (enabled)
 - Automatic Thermal Control Circuit.. : 1 (enabled)
 - Performance Monitoring............. : 1 (available)
 - Enhanced Intel SpeedStep Technology : 1 (enabled)

MSR_MISC_PWR_MGMT..............(0x1AA) : 0x402000
----------------------------------------
 - EIST Hardware Coordination......... : 0 (enabled)

MSR_TURBO_RATIO_LIMIT..........(0x1AD) : 0x2323262626262626
----------------------------------------
 - Maximum Ratio Limit for C01........ : 38 
 - Maximum Ratio Limit for C02........ : 38 
 - Maximum Ratio Limit for C03........ : 38 
 - Maximum Ratio Limit for C04........ : 38 
 - Maximum Ratio Limit for C05........ : 38 
 - Maximum Ratio Limit for C06........ : 38 

IA32_ENERGY_PERF_BIAS..........(0x1B0) : 0x0
----------------------------------------
 - Power Policy Preference.............: 0 (highest performance)

MSR_POWER_CTL..................(0x1FC) : 0x2104005B
MSR_RAPL_POWER_UNIT............(0x606) : 0xA0E03
MSR_PKG_POWER_LIMIT............(0x610) : 0x7FFD00014EA82
MSR_PKG_ENERGY_STATUS..........(0x611) : 0x13976069
MSR_PKG_POWER_INFO.............(0x614) : 0x1700460
MSR_PP0_POWER_LIMIT............(0x638) : 0x14FFD0
MSR_PP0_ENERGY_STATUS..........(0x639) : 0x0
MSR_TURBO_ACTIVATION_RATIO.....(0x64C) : 0x0
MSR_PKGC3_IRTL.................(0x60a) : 0x0
MSR_PKGC6_IRTL.................(0x60b) : 0x0
MSR_PKG_C2_RESIDENCY...........(0x60d) : 0x0
MSR_PKG_C3_RESIDENCY...........(0x3f8) : 0x0
MSR_PKG_C2_RESIDENCY...........(0x60d) : 0x0
MSR_PKG_C6_RESIDENCY...........(0x3f9) : 0x0
IA32_TSC_DEADLINE..............(0x6E0) : 0xF05603C2EBC

CPU Ratio Info:
----------------------------------------
CPU Maximum Efficiency Ratio...........: 1200 MHz
CPU Maximum non-Turbo Frequency........: 3400 MHz
CPU Maximum Turbo Frequency............: 3800 MHz
CPU P-States [ 37 (38) ]

```

[Ben’s Mac Pro.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/465460/Ben.s.Mac.Pro.zip)

**Comment by ekwipt** [comment]
sorry I also have attached my SSDT.aml i've created aready:

[ssdt.aml.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/465462/ssdt.aml.zip)

**Comment by Piker-Alpha** [comment]
Hi Ben,

I hope that you are not getting confused by the text: "_disabled/unsupported_" for MSR(0xE2) because that does not mean that C-States are disabled and/or unsupported.

Just take a look at the text below MSR(0x4) and there you find: "_C6 is the max C-State to include_" which shows you that C-State are enabled/supported. But perhaps I do not yet understand what the problem is. Do I?

**Comment by ekwipt** [comment]
Hi Piker Alpha,

Yes I was concerned with the lines specifically:

C3 State Auto Demotion............. : 0 (disabled/unsupported)
C1 State Auto Demotion............. : 0 (disabled/unsupported)
C3 State Undemotion................ : 0 (disabled/unsupported)
C1 State Undemotion................ : 0 (disabled/unsupported)
Package C-State Auto Demotion...... : 0 (disabled/unsupported)
Package C-State Undemotion......... : 0 (disabled/unsupported)

Also there are only 2 P-States:

CPU P-States [ 37 (38) ]

and finally, my chip runs at 3.8 mhz at all times and doesn't throttle down, how do I fix this??

I have changed in the bios the individual cores turbo frequency to 38 (3.8Mhz) to get past the limitation of the Intel Speedstep 3.0 (windows only turbo boost) 

NB I've edited title and first post and added more information.

Added a screenshot to show Intel Power Gadget and chip running at 3.8MHz constantly

**Comment by Piker-Alpha** [comment]
I think that the C-State question is answered now. 

Also. I was under the impression, reading some older posts from you, that you had XCPM working. What did you change to break it?

**Comment by ekwipt** [comment]
No i think the older posts were in error, i believe the combination of still having to use a fakeCPUID in clover, me not getting the XCPM patches correct for my system and Frequency Vectors not loading correctly are working against me.

Sorry for the confusion and thanks for re-reading old posts PikerAlpha

Below is a copy from some posts i've made at your blog:

> I think there is a problem, i’m having random reboots, and i think it may be due to using the FAKECPUID, where other people seem to be using your patches but without FAKECPUID on clover. Using the following patches on Sierra PB6, I was hoping you could check if these are ok and should I use them all or are there other patches to try:
> 
> _xcpm_bootstrap Sierra © Pike R. Alpha Find 83C3C483FB22 Replace 83C3C183FB22
> _xcpm_pkg_scope_msr © Pike R. Alpha Find BE0700000031D2E894FCFFFF Replace BE0700000031D29090909090
> _xcpm_core_scope_msrs © Pike R. Alpha Find BE0200000031D2E86CFCFFFF Replace BE0200000031D29090909090
> xcpm performance fix 1 (wrsmr fix to get CPU max) © okrasit Find 89D8C1E008B99901 Replace B800FF0000B99901
> XCPM_idle fix by Pike R. Alpha find 20B9E20000000F30 replace 20B9E20000009090

copy of post 2:

> Hi Pikeralpha,
> 
> I am using fakeCPID 0x040674, I will try you fix an report back, I’m guessing I wil try and delete fakeCPUID as well and just use the patch?
> 
> Is this patch called (from what i’ve read from other peoples patches…cpuid_set_info
> 
> thanks for the help, always appreciated
> 
> Edit: I already had the one you mentioned set:
> 
> xcpm performance fix 1 (wrsmr fix to get CPU max) © okrasit
> Find 89D8C1E008B99901 replace B800FF0000B99901
> 
> I hope it was credited correctly in comments
> 
> Do you have a patch for cpuid_set_info (i can only find the one for 10.11.6), I want to be able to have no entry in Clover for fakeCPUID (currently 0x040674) and use the patch instead:
> 
> Example (cpuid_set_info (OS X 10.11.6)
> find 5D7F288D48BB83F902 replace 5D7F288D48B883F902

**Comment by Piker-Alpha** [comment]
1.) Your BIOS does not set the lock bit for MSR(0xE2) and thus you don't need the _xcpm_idle patch.

2.) I would recommend to use FakeCPUID 0x040674 whenever possible. and not use the XCPM patches. Except for the reboot patch. Without a FakeCPUID you would of course need the XCPM patches.

3.) Then run FreqEditVectors.sh to inject the missing data. I used one of the plists of the iMac171,1

4.) The reboot patch can be replaced by other patches to stop the kernel (XCPM routines) from programming the following MSR's: 0x01A0, 0x01AA, 0x0620, 0x063A, 0x0642.

5.) I do not recommend to use the max turbo patches from okrasit as this basically reduces the meaning of XCPM to zero. You either want XCPM to function or keep using IOPPF: AppleIntelCPUPowerManagement mode.

This procedure works for other people. Me included. So why wouldn't it work for you? Perhaps you need to restore the factory vanilla kernel and possibly IOPlatformPluginFamily.kext as well. And start all over again. I simply fail to understand the problem. I would love to hear from people that solved it, but in my book this is due to user error. No pun intended.

**Comment by ekwipt** [comment]
I'm sure its down to user error, it's my first hackintosh and i'm just reading a lot and trying to understand what people are doing... thanks for taking the time out for well thought out answers

**Comment by ekwipt** [comment]
Can I please ask one stupid question:

2.) The reboot patch, what would this be for Broadwell-E, Sierra PB7?

Is it the bootstrap patch?

xcpm_bootstrap Sierra © Pike R. Alpha
Find       83C3C483FB22
Replace 83C3C183FB22

If not could you pretty please write what the patch is?

**Comment by ekwipt** [comment]
Nope i can't get this damn thing to work:

machdep.xcpm.io_filtered_reads: 0
machdep.xcpm.io_control_disengages: 0
machdep.xcpm.io_control_engages: 0
machdep.xcpm.io_thermal_level: 0
machdep.xcpm.gpu_thermal_level: 0
machdep.xcpm.cpu_thermal_level: 0
machdep.xcpm.deep_idle_total_stats: n/a
machdep.xcpm.deep_idle_last_stats: n/a
machdep.xcpm.deep_idle_count: 0
machdep.xcpm.qos_txfr: 1
machdep.xcpm.deep_idle_log: 0
machdep.xcpm.forced_idle_period: 30000000
machdep.xcpm.forced_idle_ratio: 100
machdep.xcpm.mbd_relaxations: 0
machdep.xcpm.mbd_applications: 0
machdep.xcpm.mbd_mode: 1
machdep.xcpm.maxintdelay: 0
machdep.xcpm.maxbusdelay: 0
machdep.xcpm.ratio_changes_total: 0
machdep.xcpm.ratio_change_ratelimit_ns: 500000
machdep.xcpm.vectors_loaded_count: 0
machdep.xcpm.tuib_ns: 0
machdep.xcpm.bootpst: 0
machdep.xcpm.bootplim: 0
machdep.xcpm.power_source: 0
machdep.xcpm.tuib_enabled: 0
machdep.xcpm.tuib_plimit_min_100mhz_ratio: 0
machdep.xcpm.tuib_plimit_max_100mhz_ratio: 0
machdep.xcpm.soft_plimit_min_100mhz_ratio: 0
machdep.xcpm.soft_plimit_max_100mhz_ratio: 0
machdep.xcpm.hard_plimit_min_100mhz_ratio: 0
machdep.xcpm.hard_plimit_max_100mhz_ratio: 0
machdep.xcpm.mode: 0

**Comment by fabiosun** [comment]
Pike, Is it available a reboot fix patch for Sierra (GM) as the one you created for El Capitan 10.11.6?

```
**reboot fix 10.11.6 © Pike R. Alpha**

find 554889E5415741564155415453504189D64189F74889FB4585FF0F84
replace C34889E5415741564155415453504189D64189F74889FB4585FF0F84
```

Many people uses boot strap patch or idle patch that inhibit XCPM start...

**Comment by Piker-Alpha** [comment]
@fabiosun,

Sure. I was about to write this down for Ben so here goes.

**Step 1**

```
otool -tV /S*/L*/Kernels/kernel > ~/Documents/kernel.txt
```

**Step 2**

```
open ~/Documents/kernel.txt
```

**Step 3**

Search for: "_xcpm_init:"

**Step 4**

Scroll down to:

```
leaq    _xcpm_pkg_scope_msrs(%rip), %rdi
movl    $0x7, %esi
xorl    %edx, %edx
callq   0xffffff80004283c0
```

**Note**: This callq is our target. The address itself is wrong, as you have a different one, but that is the one that we are looking for.

**Step 5**

Get file offset like this: 0x4283c0 - 0x200000 = 0x2283c0

**Step 6**

```
xxd -s 0x2283c0 -l 28 -psu /S*/L*/Kernels/kernel
```

Here I get this (in DP8):

```
554889e5415741564155415453504189d64189f74889fb4585ff0f84
```

This is your Find pattern fro Clover. The Replace pattern is the same, but for this you replace the first 55 with C3 (example below):

```
C34889e5415741564155415453504189d64189f74889fb4585ff0f84
```

**Tip**: If you copy the kernel and patch it manually, then you can use Hopper to verify the used address. In Hopper you search for: "_xcpm_init" and scroll down the the same callq instruction. If you follow it – with a double-click – then you can check the first byte of the routine. It should now be C3 (ret) and no longer 55.

**Comment by fabiosun** [comment]
Thank you Pike..
I will elaborate it , but maybe with this you are helping many confused people! :-)

**Comment by ekwipt** [comment]
wow thank you Pike!, this is the next step I want to learn to be able to search for the patches myself.

Much appreciated!!!!

**Comment by ekwipt** [comment]
Step 6 Pike, how did you get to this?

**Comment by fabiosun** [comment]
Hi
It is a command that you have to fill with data calculated in step five
In my case, macOS Sierra (GM) is identical to pike DP8 as you can see and if I have not done some errors

```
ffffff80003f5ab1    leaq    _xcpm_pkg_scope_msrs(%rip), %rdi
ffffff80003f5ab8    movl    $0x7, %esi
ffffff80003f5abd    xorl    %edx, %edx
ffffff80003f5abf    callq   0xffffff80003f6190
```

0x3f6190 - 0x200000 = 0x1f6190

```
xxd -s 0x1f6190 -l 28 -psu kernel
```

in macOS Sierra (GM) seems the same of DP8

```
554889e5415741564155415453504189d64189f74889fb4585ff0f84
```

so replace is:

```
C34889e5415741564155415453504189d64189f74889fb4585ff0f84
```

**Comment by Piker-Alpha** [comment]
@fabiosun,

Correct. And in the Public Beta GM-1 and GM-2 the address is: 0x4283a0 - 0x200000 = 0x2283A0

**Comment by fabiosun** [comment]
Thank you Pike, I am asking in your XCPM for unsupported processor blog article some advice to proceed.
I hope it is the right place to ask

**Comment by ekwipt** [comment]
And DP7 is the same as DP8 and GM?

**Comment by Piker-Alpha** [comment]
The best thing that you can do is to do exactly what I wrote down in my reply. This will also help you in the future.

**Comment by ekwipt** [comment]
yes i understand and was able to get the same patch as you for DP7 as with DP8 and GM, i just wanted to check because I've applied the patch in Clover and it still doesn't work :(

**Comment by fabiosun** [comment]
ekwipt..you are there, take a look what it is possible to achieve with your config.plist:
![screen shot 2016-09-14 at 16 10 45](https://cloud.githubusercontent.com/assets/6358373/18515658/591bfdb2-7a96-11e6-8007-4bd606b5efba.png)

Pike, if you want to smile...
same behaviour of El Capitan..
so or it is a my issue..or asus bios issue! :-)

Edit
Sierra (16A322)
ffffff8000428734    leaq    _xcpm_SMT_scope_msrs(%rip), %rdi
ffffff800042873b    movl    $0xb, %esi
ffffff8000428740    xorl    %edx, %edx
ffffff8000428742    callq   0xffffff80004283a0
so
fabios-Mac-Pro:desktop fabio$ xxd -s 0x2283a0 -l 28 -psu kernel
554889e5415741564155415453504189d64189f74889fb4585ff0f84

uhm...

**Comment by Piker-Alpha** [comment]
Have you fixed the bus frequency error?

**Comment by fabiosun** [comment]
No Pike
I am searching for right parameter to add  in  config.plist in clover Wiki 
found something but I have to understand better
If no value for bus frequency in clover it put 099997 and seems that value is multiply for 4
if I put 25000 the checked value is 100000, but other cpu values seem strange

**Comment by fabiosun** [comment]
I have found something but it seems  only for cosmetic purposes

**Comment by fabiosun** [comment]
https://clover-wiki.zetam.org/Configuration/CPU#cpu_busspeedkhz
100000?

**Comment by fabiosun** [comment]
Pike, your reboot fix patch is the same if you have or not a MSR 0xE2 locked?
Or it is an unrelated noob question? :-)
Then, to boot properly with my Broadwell EP CPU I need of reboot fix and 5960XPatch by Brumbaer in IOPCIFamily:
find
4881F901000040
replace
4881F901000080

Other mandatory fix is a FakeCPUId as you advised time ago

this behaviour is valid in El Capitan and also in Sierra

Both OS seems to have a partial XCPM, but frequency vector are not loaded
in El Capitan machdep.xcpm.vectors_loaded_count is not present as voice
in Sierra machdep.xcpm.vectors_loaded_count is 0

Any advice ?

**Comment by Piker-Alpha** [comment]
Yes. The reboot fix (patch) is the same for people with a locked MSR(0xE2) and people without the lock bit set for this MSR. Keep in mind; other MSR's that get programmed by the kernel (sub) routine that we patch can also trigger a KP/reboot.

The first thing that I would do in this case is to check the plist with your board-id to see if the FrequencyVectors data is there or not.

**Comment by fabiosun** [comment]
Thank you Pike
In my board-id [Mac-F60DEB81FF30ACF6]
I have these in frequency vector array

> <02000000 00000000 02000000 00000000 64000000 00000000 19000000 00000000 0064ffff ffffffff 0f000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 64000000 02000000 00000000 e8030000 00000000 a00f0000 00000000 0164ffff ffffffff 0f000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 64000000 03000000 00000000 40420f00 00000000 a00f0000 00000000 0264ffff ffffffff 0f000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Edit
 cut cut cut

**Comment by ekwipt** [comment]
Hello PikerAlpha, 

I didn't want to post until i have had success... and guess what success.

Glad to say it wasn't total user error!!! Clover was updated yesterday i think, so i thought i would try the new version, installed over my current build of Sierra PB7, changed my FakeCPUID to 0x040671 (i'm not sure if this is right now, but i tried and it worked because it's the first CPU of Broadwell-E line (totally random thought i had today) previously 0x040674.

Redid the script  ssdtPRGen.sh (latest build) Better fix...
Redid AppleIntelInfo.kext (latest build) kext to v1.8 

and now i get the following from AppleIntelInfo.kext, i'm not getting straight line for turbo, so not sure what performance fixes patches i can try with your help. i just want to say thanks again for the patience, i'm also glad that it was not user error!!!

```
AppleIntelInfo.kext v1.8 Copyright © 2012-2016 Pike R. Alpha. All rights reserved

Settings:
------------------------------------------
logMSRs..................................: 1
logIGPU..................................: 0
logCStates...............................: 1
logIPGStyle..............................: 1
InitialTSC...............................: 0x285838719d8 (81 MHz)
MWAIT C-States...........................: 8480

Processor Brandstring....................: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

Processor Signature..................... : 0x406F1
------------------------------------------
 - Family............................... : 6
 - Stepping............................. : 1
 - Model................................ : 0x4F (79)

Model Specific Registers (MSRs)
------------------------------------------

MSR_CORE_THREAD_COUNT............(0x35)  : 0x6000C
------------------------------------------
 - Core Count........................... : 6
 - Thread Count......................... : 12

MSR_PLATFORM_INFO................(0xCE)  : 0x20080C3BF3812200
------------------------------------------
 - Maximum Non-Turbo Ratio.............. : 0x22 (3400 MHz)
 - Ratio Limit for Turbo Mode........... : 1 (programmable)
 - TDP Limit for Turbo Mode............. : 1 (programmable)
 - Low Power Mode Support............... : 1 (LPM supported)
 - Number of ConfigTDP Levels........... : 1 (additional TDP level(s) available)
 - Maximum Efficiency Ratio............. : 12
 - Minimum Operating Ratio.............. : 8

MSR_PMG_CST_CONFIG_CONTROL.......(0xE2)  : 0x403
------------------------------------------
 - I/O MWAIT Redirection Enable......... : 1 (enabled, IO read of MSR(0xE4) mapped to MWAIT)
 - CFG Lock............................. : 0 (MSR not locked)
 - C3 State Auto Demotion............... : 0 (disabled/unsupported)
 - C1 State Auto Demotion............... : 0 (disabled/unsupported)
 - C3 State Undemotion.................. : 0 (disabled/unsupported)
 - C1 State Undemotion.................. : 0 (disabled/unsupported)
 - Package C-State Auto Demotion........ : 0 (disabled/unsupported)
 - Package C-State Undemotion........... : 0 (disabled/unsupported)

MSR_PMG_IO_CAPTURE_BASE..........(0xE4)  : 0x10414
------------------------------------------
 - LVL_2 Base Address................... : 0x414
 - C-state Range........................ : 1 (C6 is the max C-State to include)

IA32_MPERF.......................(0xE7)  : 0x11F721F962
IA32_APERF.......................(0xE8)  : 0x1094F7A244
MSR_0x150........................(0x150) : 0x52424

MSR_FLEX_RATIO...................(0x194) : 0xE0000
------------------------------------------

MSR_IA32_PERF_STATUS.............(0x198) : 0x226900002300
------------------------------------------
 - Current Performance State Value...... : 0x2300 (3500 MHz)

MSR_IA32_PERF_CONTROL............(0x199) : 0x2600
------------------------------------------
 - Target performance State Value....... : 0x2600 (3800 MHz)
 - Intel Dynamic Acceleration........... : 0 (IDA engaged)

IA32_CLOCK_MODULATION............(0x19A) : 0x0
IA32_THERM_STATUS................(0x19C) : 0x884E0000

IA32_MISC_ENABLES................(0x1A0) : 0x850089
------------------------------------------
 - Fast-Strings......................... : 1 (enabled)
 - Automatic Thermal Control Circuit.... : 1 (enabled)
 - Performance Monitoring............... : 1 (available)
 - Enhanced Intel SpeedStep Technology.. : 1 (enabled)

MSR_TEMPERATURE_TARGET...........(0x1A2) : 0x640A00
------------------------------------------
 - Turbo Attenuation Units.............. : 0 
 - Temperature Target................... : 100
 - TCC Activation Offset................ : 0

MSR_MISC_PWR_MGMT................(0x1AA) : 0x402000
------------------------------------------
 - EIST Hardware Coordination........... : 0 (enabled)

MSR_TURBO_RATIO_LIMIT............(0x1AD) : 0x2323232323232626
------------------------------------------
 - Maximum Ratio Limit for C01.......... : 26 (3800 MHz) 
 - Maximum Ratio Limit for C02.......... : 26 (3800 MHz) 
 - Maximum Ratio Limit for C03.......... : 23 (3500 MHz) 
 - Maximum Ratio Limit for C04.......... : 23 (3500 MHz) 
 - Maximum Ratio Limit for C05.......... : 23 (3500 MHz) 
 - Maximum Ratio Limit for C06.......... : 23 (3500 MHz) 

IA32_ENERGY_PERF_BIAS............(0x1B0) : 0x0

MSR_POWER_CTL....................(0x1FC) : 0x2104005B
------------------------------------------
 - C1E Enable............................: 1

MSR_RAPL_POWER_UNIT..............(0x606) : 0xA0E03
------------------------------------------
 - Power Units.......................... : 3 (1/8 Watt)
 - Energy Status Units.................. : 14 (61 micro-Joules)
 - Time Units .......................... : 10 (976.6 micro-Seconds)

MSR_PKG_POWER_LIMIT..............(0x610) : 0x7FFD00014EA82
------------------------------------------
 - Package Power Limit #1............... : 3408 Watt
 - Enable Power Limit #1................ : 1 (enabled)
 - Package Clamping Limitation #1....... : 0 (disabled)
 - Time Window for Power Limit #1....... : 10 (2560 milli-Seconds)
 - Package Power Limit #2............... : 4090 Watt
 - Enable Power Limit #2................ : 1 (enabled)
 - Package Clamping Limitation #2....... : 1 (allow going below OS-requested P/T state setting Time Window for Power Limit #2)
 - Time Window for Power Limit #2....... : 3 (20 milli-Seconds)
 - Lock................................. : 0 (MSR not locked)

MSR_PKG_ENERGY_STATUS............(0x611) : 0x3AC7B4E
------------------------------------------
 - Total Energy Consumed................ : 3761 Joules (Watt = Joules / seconds)

MSR_PKG_POWER_INFO...............(0x614) : 0x1700460
------------------------------------------
 - Thermal Spec Power................... : 140 Watt
 - Minimum Power........................ : 0
 - Maximum Power........................ : 0
 - Maximum Time Window.................. : 0

MSR_PP0_POWER_LIMIT..............(0x638) : 0x14FFD0
------------------------------------------
 - Power Limit.......................... : 4090 Watt
 - Enable Power Limit................... : 1 (enabled)
 - Clamping Limitation.................. : 0 (disabled)
 - Time Window for Power Limit.......... : 10 (10240 milli-Seconds)
 - Lock................................. : 0 (MSR not locked)

MSR_PP0_ENERGY_STATUS............(0x639) : 0x0

MSR_TURBO_ACTIVATION_RATIO.......(0x64C) : 0x0

MSR_PKGC3_IRTL...................(0x60a) : 0x0
MSR_PKGC6_IRTL...................(0x60b) : 0x0
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x60FA75686
MSR_PKG_C3_RESIDENCY.............(0x3f8) : 0x0
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x60FA75686
MSR_PKG_C6_RESIDENCY.............(0x3f9) : 0x1580ECC93C

IA32_TSC_DEADLINE................(0x6E0) : 0x28587BD735C

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......: 12 (1200 MHz)
Maximum non-Turbo Ratio/Frequency........: 34 (3400 MHz)
Maximum Turbo Ratio/Frequency............: 38 (3800 MHz)
P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 ]
```

**Comment by r2tincan** [comment]
I know this is an old thread but I'm gathering from it that if I'm using a CPUID patch I don't need the XCPM patches to get XCPM working on a Haswell-E Xeon?

I'm finding 83C0E9 and replacing with 83C0E6
