### ISSUE TITLE
SSDT Mac definition vs SMBIOS

### ISSUE THREAD

**Issue by phathak** [Piker-Alpha/ssdtPRGen.sh#262]

**Comment by Piker-Alpha** [comment]
If you don't add text then I'm afraid that I have to close this issue.

**Comment by phathak** [comment]
Hi Pike! Sorry for the confusion.

I have a 3930k. So it's a Sandy Bridge E, that is known. I've been generating a few ssdt with different board-ids for testing. So far I only tested two, that is the Mac Mini 5,3 and the iMac12,2. I think the iMac is giving me better results. I'll have to keep testing to others though because CPU is more often at 3.2 Ghz than 1,2. Even on idle.

So my question is : Even though I'm using MacPro 5,1 in my clover config SMBIOS, the Mac model defined in the SSDT is not relevant to the one in SMBIOS? They don't need to be the same?

Thanks for you advices.

```
./ssdtPRGen.sh -s 'Sandy Bridge'
Sandy Bridge
Mac-942B5BF58194151B / iMac12,1
Mac-942B59F58194171B / iMac12,2
Mac-8ED6AF5B48C039E1 / Macmini5,1
Mac-4BC72D62AD45599E / Macmini5,2
Mac-7BA5B2794B2CDB12 / Macmini5,3
Mac-94245B3640C91C81 / MacBookPro8,1
Mac-94245A3940C91C80 / MacBookPro8,2
Mac-942459F5819B171B / MacBookPro8,3
Mac-C08A6BB70A942AC2 / MacBookAir4,1
Mac-742912EFDBEE19B3 / MacBookAir4,2
```

**Comment by Piker-Alpha** [comment]
No. They do not have to be the same. The board-id's in the script are merely there to setup C-States and their latency, but they are almost always the same.

**Comment by phathak** [comment]
Ok. So I should try different board IDs and see which one gives me better results?

**Comment by Piker-Alpha** [comment]
Yes. This is basically all you can do at this point.
