### ISSUE TITLE
Warning: 'system-type' ; Warning: 'cpu-type' 

### ISSUE THREAD

**Issue by phathak** [Piker-Alpha/ssdtPRGen.sh#265]
Hey Pike, me again,

Can you help me get rid of these two warnings?

Thank you

```
./ssdtPRGen_master.sh -b Mac-742912EFDBEE19B3 -m MacBookAir4,2



ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/User/Library/ssdtPRGen/Data
Override value: (-b) board-id, now using: Mac-742912EFDBEE19B3!
Override value: (-m) model, now using: MacBookAir4,2!

System information: Mac OS X 10.11.6 (15G31)
Brandstring 'Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz'

Scope (_SB_) {12806 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookAir4,2' with board-id [Mac-742912EFDBEE19B3]
Sandy Bridge Core i7-3930K processor [0x206D7] setup [0x0402]
With a maximum TDP of 130 Watt, as specified by Intel
Number logical CPU's: 12 (Core Frequency: 3200 MHz)
Number of Turbo States: 6 (3300-3800 MHz)
Number of P-States: 27 (1200-3800 MHz)
Injected C-States for C000 (C1,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0402 instead of 0x0602)
Warning: 'system-type' may be set improperly (1 instead of 2)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/User/Library/ssdtPRGen/ssdt.dsl - 274 lines, 7878 bytes, 64 keywords
AML Output:    /Users/User/Library/ssdtPRGen/ssdt.aml - 2015 bytes, 27 named objects, 37 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
```

**Comment by fabiosun** [comment]
Hi
If you are using clover bootloader you have to insert in cpu Type 0x0602 for first warning
for the second one you have to flag SmartUPS
Second warning is strange because if you are using mac 6.1 smbios should be set automatically
see also here:
https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/257#issuecomment-244510144

Ps
I don't know why you are overriding board -id and model..maybe you have some reasons I don't know

**Comment by Piker-Alpha** [comment]
Thank you for answering this Fabio. 

**Note**: I added two new helpful links for Clover users in my latest commit. Please give it a go and let me know what you think. Is that enough?

**Comment by fabiosun** [comment]
Yes :-)

**Comment by phathak** [comment]
Thank you Fabio and Pike for your answers.

I'll update my clover config tonight and see if it works. I'm using MacPro 5,1 so that's why it wasn't set automatically. I was told MacPro 5,1 was the proper definition to use for my system (GA-X79-UD5, 3930k, GTX 660ti). I'll try with 6,1 though I might need to patch the graphics for it to keep working.

I'm overriding board-id and model because the script was giving me an error when detecting I was using MacPro 5,1/6,1 in SMBIOS. I'll try it again tonight without overriding it and post the results here.

Thanks for the links Pike. I'll go do my homeworks :)

**Comment by Piker-Alpha** [comment]
Ok. Closing issue.
