### ISSUE TITLE
Intel(R) Core(TM) i3 CPU U 330 @ 1.20GHz - Unknown processor model

### ISSUE THREAD

**Issue by nnkovt** [Piker-Alpha/ssdtPRGen.sh#266]
Console output:
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v19.8 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i3 CPU U 330 @ 1.20GHz"

Override value: (-w) Ivy Bridge workarounds, now set to: 3!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

Link to the processor model:
http://ark.intel.com/products/49021/Intel-Core-i3-330UM-Processor-3M-cache-1_20-GHz
Processor Number    i3-330UM
TDP 18 W
Processor Base Frequency    1.2 GHz
Cores   2
Threads 4

**Comment by Piker-Alpha** [comment]
The processor data for the Arrandale processors is not pre-defined in data files, but you can add the data for your i3-330UM yourself in [Data/User Defined.cfg](https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/User%20Defined.cfg) and there are some examples that you can use.

After this you run the script with: ./ssdtPRGen.sh -p 'i3-330UM'
