### ISSUE TITLE
i7 5820K giving errors while creating ssdt for cpu

### ISSUE THREAD

**Issue by dr3nan** [Piker-Alpha/ssdtPRGen.sh#267]
Hello Pike, how are you?

The reason for this ticket is the above mentioned.. I'm having issues creating a ssdt for the 5820K.. I've never had this issue before..

I'll attach a picture so you see whats the issue
![captura de pantalla 2016-09-16 a las 19 02 38](https://cloud.githubusercontent.com/assets/19169582/18594419/31c94606-7c40-11e6-9699-4c1aa918c25a.png)

Let me know if you need any more information.

Thanks in advanced!

**Comment by dr3nan** [comment]
BTW I'm on a Asus X99 A  bios 3301, with latest clover and latest 10.11.6 + security update

**Comment by Piker-Alpha** [comment]
Hmm. This is a regression and was introduced by the fix for issue #238

Thank you for reporting this issue here.  Please let me know if v20.1 works for you.
