### ISSUE TITLE
egrep no such file or directory on 10.11.6 with xcode 8

### ISSUE THREAD

**Issue by souhaiebtar** [Piker-Alpha/ssdtPRGen.sh#268]
sudo ./ssdtPRGen.sh -p 'i5-4590S' -f 3000 -turbo 3700

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
##              v20.1 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G1004)
Brandstring: "Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz"

Override value: (-p) processor model, now using: i5-4590S!
Override value: (-f) clock frequency, now using: 3000 MHz!
Override value: (-turbo) maximum (turbo) frequency, now using: 3700 MHz!

Version: models.cfg v160 / Haswell.cfg v151

egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory
egrep: : No such file or directory

Warning: No ACPI Processor declarations found in !
     Using assumed Scope (_SB) {}

Error: Processor name(s) not found ...
Aborting ...
Done.

**Comment by souhaiebtar** [comment]
![2016-09-17_15-29-22](https://cloud.githubusercontent.com/assets/15350774/18608824/cf585b72-7ceb-11e6-9157-e9ffe0d16b28.png)

**Comment by souhaiebtar** [comment]
![2016-09-17_15-30-12](https://cloud.githubusercontent.com/assets/15350774/18608827/d71d386e-7ceb-11e6-81e7-e6c2b47e3b10.png)

**Comment by Piker-Alpha** [comment]
I found two bugs in the script – thanks to you.

**1.**) filename wasn't set.
**2.**) basename wasn't set.

Please try the latest update and see if that works for you. If not, then run the script with the -d 2 argument.

Thanks.

**Comment by souhaiebtar** [comment]
**thanks for the reply**
 i will test in the next week

**Comment by souhaiebtar** [comment]
it works thanks
