### ISSUE TITLE
Getting two SSDT.aml

### ISSUE THREAD

**Issue by phathak** [Piker-Alpha/ssdtPRGen.sh#269]
Whenever I run the script, I always get SSDT.aml and SSDT-1.aml. Do I need both or just the first one? Why is it generating two aml? Is it because of my CPU? I have a Sandy Bridge E 3930k.

Thank you

**Comment by Piker-Alpha** [comment]
SSDT-1.aml is not created by ssdtPRGen.sh You can check this yourself by searching the script for: "SSDT-1". You won';t find it. It isn't there.
