### ISSUE TITLE
i7-3517u KPs, & Stuck at Lowest Freq After Seirra Upgrade

### ISSUE THREAD

**Issue by shinzon76** [Piker-Alpha/ssdtPRGen.sh#270]
My machine is an Acer v5-171-9661 laptop with an i7-3517u and HM77 chipset.

When I was originally setting my machine up for Yosemite some time back, I had to pick a MacBookAir5,1 system def, and use the -xcpm boot flag else I'd get a AICPUPM kernel panic on boot. I was able to use ssdtPRGen with the arguments -x 2 -x 1 to get working power management/speedstep.

This worked through El Capitan until I upgraded to Sierra. With the old generated ssdt installed, I get a KP on boot; without the ssdt the system boots fine. It appears Apple has changed or removed xcpm for Ivy Bridge processors, as I can now boot the system without the -xcpm flag and it wont KP as in releases before, though I get no PM obviously, and the processor is stuck at 1.8ghz.

Ive tried updating to the current version of ssdtPRGen, and reran the script with -b Mac-66F35F19FE2A0D05 -w 2 and while I get nothing but success messages from x86platformshim at boot, I'm stuck at 800mhz without speedstep. I've tried w1 and w3; both give KPs. I also tried the beta version of the script, which no longer seems to have the workarounds, but running it with just the board id results in being stuck at 800mhz.

Here's the output of the current version of the script running with Mac-66F35F19FE2A0D05 -w 2 flags

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
##              v15.6 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/shinzon/Library/ssdtPRGen/Data
Override value: (-b) board-id, now using: Mac-66F35F19FE2A0D05!
Override value: (-w) Ivy Bridge workarounds, now set to: 2!

System information: Mac OS X 10.12 (16A323)
Brandstring 'Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz'

Scope (_PR_) {220 bytes} with ACPI Processor declarations found in the DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookAir5,1' with board-id [Mac-66F35F19FE2A0D05]
Ivy Bridge Core i7-3517U processor [0x306A9] setup [0x0704]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1900 MHz)
Number of Turbo States: 11 (2000-3000 MHz)
Number of P-States: 23 (800-3000 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/shinzon/Library/ssdtPRGen/ssdt.dsl - 266 lines, 8087 bytes, 47 keywords
AML Output:    /Users/shinzon/Library/ssdtPRGen/ssdt.aml - 1620 bytes, 16 named objects, 31 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Any ideas what's wrong?

Attached is my original ssdt that was working pre-Sierra, and one generated with the current version.
[3517uSierra.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/485809/3517uSierra.zip)

**Comment by shinzon76** [comment]
I appear to have solved the issue. First problem is that ssdtPRGen doesn't seem to be actually applying the extra low power state workaround. My processor bottoms out at 800mhz, and even with -w 2, ssdtPRGen would have 800mhz as the bottom state. I added a 700mhz state: 

Package (0x06) { 0x02BC, 0x0015E0, 0x0A, 0x0A, 0x0700, 0x0700 }

Second is that ssdtPRGEN has Name (APLF, Zero) when it should be set to One.

With both of those changes added to the above attached ssdt generated with -b Mac-66F35F19FE2A0D05 -w 2, I get full power managment/speedstep.

Attached is the working ssdt.

[3517uSierraWorking.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/486017/3517uSierraWorking.zip)

**Comment by Piker-Alpha** [comment]
Thanks. I recently worked on a couple of changes and something went wrong/was forgotten/ignored/overlooked. Please try v20.3 That should be fine.

Note: -w has been renamed to -c (see ssdtPRGen.sh -help).

**Comment by shinzon76** [comment]
Thanks for getting this sorted so quickly. Ran the new version and the resultant ssdt gives me working speedstep/power mangement, however I do notice that the extra low power state has a voltage value of Zero. I don't know if this is intentional or not considering this state will never be reached.

```
        Package (0x06) { 0x02BC,     Zero, 0x0A, 0x0A, 0x0700, 0x0700 }
```

Output: 

```
./ssdtPRGen.sh: line 3833: /Users/shinzon/Library/ssdtPRGen/Data/Versions.cfg: No such file or directory

System information: Mac OS X 10.12 (16A323)
Brandstring: "Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz"

Override value: (-b) board-id, now using: Mac-66F35F19FE2A0D05!
Override value: (-c) CPU workarounds, now set to: 2!

Notice: Downloading extractACPITables.zip ...
Notice: Downloading User Defined.cfg ...
Notice: Downloading Sandy Bridge.cfg ...
Notice: Downloading Ivy Bridge.cfg ...
Version: models.cfg v160 / Ivy Bridge.cfg v150

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Notice: Downloading Restrictions.cfg ...
Generating ssdt.dsl for a 'MacBookAir5,1' with board-id [Mac-66F35F19FE2A0D05]
Ivy Bridge Core i7-3517U processor [0x306A9] setup [0x0704]
With a maximum TDP of 17 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 1900 MHz)
Number of Turbo States: 11 (2000-3000 MHz)
Number of P-States: 23 (800-3000 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20141107-64 [Jan  2 2015]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/shinzon/Library/ssdtPRGen/ssdt.dsl - 270 lines, 8300 bytes, 49 keywords
AML Output:    /Users/shinzon/Library/ssdtPRGen/ssdt.aml - 1725 bytes, 16 named objects, 33 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
```

ssdt is attached.
[ssdt.dsl.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/488250/ssdt.dsl.zip)

**Comment by Piker-Alpha** [comment]
Yeah that is intentional. Also about the line 3833 error. That should be gone when you delete ~/Library/ssdtPRGen and run the script again. Your data is still from the old version.

**Comment by shinzon76** [comment]
Thanks again, Piker, for this and all you bring to the community.
