### ISSUE TITLE
CPU Name '0000' any workaround ?

### ISSUE THREAD

**Issue by TpwUK** [Piker-Alpha/ssdtPRGen.sh#272]
Morning Pike, hope you are doing well :)

I have here a couple of E5-2603 Engineering Samples that I am trying out on the ASUS Z10PE-D8 WS. I have macOS Sierra installed and running. As far as I know the CPUs are locked to 1.7Ghz no hyper threading none turbo and therefore I assume no EIST but they should have an idle speed and was hoping to discover that via your script, however it doesn't like the CPUID 0000 is there any workaround ?

I have tried things like 0406 CP00 C000 CPU0 

Martin

**Comment by Piker-Alpha** [comment]
You should try AppleIntelInfo.kext for this. What is the brandstring of the processor?

```
sysctl machdep.cpu.brand_string
```

We already have a check for it in function _showSystemData (line 3899) but that may still be wrong.

**Comment by TpwUK** [comment]
Thanks for the reply Pike, I tried AppleIntelInfo from your source files. I had to change that to build for Sierra as it nagged about it being built for 10.11 but when I try to load it I get an error saying that I or it must be root:wheel so I have not got this to work, the previous version puts my computer into an instant reboot. As an artist I am not too great at the administrator level.

machdep.cpu.brand_string: Genuine Intel(R) CPU 0000 @ 1.70GHz

Is the result of running sysctl .... From reading pages from google these CPU's are 0x000406F1

I try over-riding the detection using the -a option shown below, but the script still dies with unknown processor.

-a CP00 -c 3 -p 'E5-2603 v4' -x 1 -t 85 -bclk 1700 -f 100 -l 12

Results with ...
`ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen

##              v15.6 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/tpwuk/Library/ssdtPRGen/Data
Override value: (-a) label for ACPI Processors, now using 'CP00'!
Override value: (-c) CPU type, now using: Broadwell!
Override value: (-p) processor model, now using: E5-2603 v4!
Override value: (-x) XCPM mode, now set to: 1!
Override value: (-t) maximum TDP, now using: 85 Watt!
Override value: (-bclk) frequency, now using: 1700 MHz!
Override value: (-f) clock frequency, now using: 100 MHz!
Override value: (-l) number of logical processors, now using: 12!

System information: Mac OS X 10.12 (16A323)
Brandstring 'Genuine Intel(R) CPU 0000 @ 1.70GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.
`
 I assume this is why I am not seeing any x86PlatformPlugin regarding power management.
Appreciate any help/suggestions you can offer

Martin

**Comment by Piker-Alpha** [comment]
Ah ok. That explain it. Why you didn't get to see the warning. You are using an old version of the script.

1.) [Download ssdtPRGen.sh v20.4](https://github.com/Piker-Alpha/ssdtPRGen.sh/archive/Beta.zip)

2.) cleanups

```
rm ~/Library/ssdtPRGen
```

3.) run script

```
./ssdtPRGen.sh -p E5-2603
```

**Comment by TpwUK** [comment]
Bonsai!! - Thank you sir

Martin
