### ISSUE TITLE
Script doesn't detect W3565 

### ISSUE THREAD

**Issue by Mtkhan13** [Piker-Alpha/ssdtPRGen.sh#273]
Hi, I'm new to this and trying to generate SSDT for my HP Z400 Hackintosh with W3565 Processor. But every time it says unknow processor.
Can you please tell me step by step process on how to create SSDT manually (I mean using arguments)?

I appreciate your help. Thank you

**Comment by Piker-Alpha** [comment]
Correct. The script was written to support Intel Core I processors and newer. See also the updated readme for the workaround.  Thanks for the reminder.

**Comment by Mtkhan13** [comment]
Thank you for letting me I really didn't read the file. Can you please tell me how can I do this for xeon w/x series processors? I appreciate your help. Thanks again
