### ISSUE TITLE
How can i enable a C-state and P-state HP Z420, E5-2670 v1(SandyBridge)

### ISSUE THREAD

**Issue by SIXFLOW-OpenCore-KR** [Piker-Alpha/ssdtPRGen.sh#275]
hi, i was trying many times but doesn't enable a speedstep.

System Specification
- HP Z420
- Single E5-2670 V1 (Sandibridge)
- GTX 760
- BCM94360CD

[My files]
[aml & config.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/504353/aml.config.zip)
also i was made up a SSDT.aml with ssdtPRGen 16.7 
(ssdtPRGen-beta won't running. it just displaying a Unknown Processor even if select a ivybridge)

![1](https://cloud.githubusercontent.com/assets/22560422/19014154/3965c7b8-8820-11e6-80fb-f66ca7a044c1.png)
btw, i was set it up with these options.
**ssdtPRGen.sh -a C000 -c 1 -lfm 1200 -turbo 3300 -l 16 -t 115 -w 3**

so~ looks pretty... just looks pretty... T_T
but still be running on P-states (26) (base clock) only.

![2](https://cloud.githubusercontent.com/assets/22560422/19014155/429cef50-8820-11e6-8e6f-4138c13b84b6.png)

![3](https://cloud.githubusercontent.com/assets/22560422/19014156/4679d728-8820-11e6-8607-d67b98498a92.png)

![4](https://cloud.githubusercontent.com/assets/22560422/19014168/5e832f7c-8820-11e6-86f7-11a983a3b31d.png)

and somebody said me such a "checking a msr lock" but there are not found any problem.

![5](https://cloud.githubusercontent.com/assets/22560422/19014175/a11a3c0e-8820-11e6-91d7-4963e7cef34b.png)

![6](https://cloud.githubusercontent.com/assets/22560422/19014176/a3ed01d2-8820-11e6-8adb-c7a0d94bb1c6.png)

could you please let me know how can i fix this problem of. T_T

![7](https://cloud.githubusercontent.com/assets/22560422/19014184/f3b78034-8820-11e6-86de-248f702d03ae.png)

**Comment by Piker-Alpha** [comment]
I do not support the old script versions. Please use v20.4 without arguments. If you get an unknown CPU error, then add -p ' E5-2670'

**Comment by SIXFLOW-OpenCore-KR** [comment]
yes thank. i was ran out with -mode custom -p 'E5-2670' with v20.4
then there are no problem it but only one of state (26) found.

how can i force unlocked msr lock?? (also enable a AsusAICPUPM and MSR lock code in my config.plist)

**Comment by SIXFLOW-OpenCore-KR** [comment]
Finally i did!!!

HP Z series with the C602 chipset are must be AIPCMpatch! 

because of clover boot loader and custom MSR lock patch are not run exactly even if insert a de tour code.

[AICPMPatch.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/505991/AICPMPatch.zip)
http://olarila.com/forum/viewtopic.php?f=9&t=1003

run ssdtPRGen -mode custom 'E5-2670' is running  gooooooood!!
just run a AICPMPatch first if somebody wanna get a speedster with SandyBridge system.
