### ISSUE TITLE
Unknown cpu    i5   3340s

### ISSUE THREAD

**Issue by deucecoupe** [Piker-Alpha/ssdtPRGen.sh#281]
ssdt prgen  reports    i5 3340s  as unknown cpu..     

Please could some one help

**Comment by Piker-Alpha** [comment]
Thank you for reporting this issue here. The processor data for your i5-3340S is now available so please do a: 

```
rm ~/Library/ssdtPRGen/Data
```

and try again.

**Comment by deucecoupe** [comment]
Well what can I say,  I have tried so many times to find a work around that works but could not do it.  You fixed it in a jiffy    thank you.  My cpu will now go over 3ghz for the 1st time on my hack.  Cheers and thank you very much,  power management is great now at last.  Great stuff Piker-Alpha.

**Comment by ameenjuz** [comment]
i3-3217U,17,800,1800,1800,2,4   this processor cpu stuck issues 1.70 ghz on macos sierra how to fix it
