### ISSUE TITLE
-xcpm mode: 1 not working

### ISSUE THREAD

**Issue by maikie1** [Piker-Alpha/ssdtPRGen.sh#285]
hi Piker,

I get an error with generating the ssdt file when using the -xcpm mode: 1 flag
![screen shot 2016-10-19 at 12 16 15](https://cloud.githubusercontent.com/assets/22933682/19514982/ef7f9c62-95f5-11e6-9de5-a7a28bdf7c79.png)

also frequency stays flat at 3,40 Ghz :-(

any suggestions?

thanks M

**Comment by Piker-Alpha** [comment]
Version 20.6 of the script only supports -x [0/1] 
Version 20.7 also supports -xcpm [0/1]
