### ISSUE TITLE
Intel Core i5 6600K - Warning: 'cpu-type' may be set improperly (0x0605 instead of 0x0905)

### ISSUE THREAD

**Issue by ghost** [Piker-Alpha/ssdtPRGen.sh#286]
> ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
>             v6.6  Copyright (c) 2013 by † Jeroen
> ##             v20.8 Copyright (c) 2013-2016 by Pike R. Alpha
> 
> Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <
> 
> System information: Mac OS X 10.12.1 (16B2555)
> Brandstring: "Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz"
> 
> Version: models.cfg v150 / Skylake.cfg v193
> 
> Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
> Generating ssdt.dsl for a 'iMac17,1' with board-id [Mac-B809C3757DA9BB8D]
> Skylake Core i5-6600K processor [0x506E3] setup [0x0605]
> With a maximum TDP of 91 Watt, as specified by Intel
> Number logical CPU's: 4 (Core Frequency: 3500 MHz)
> Number of Turbo States: 4 (3600-3900 MHz)
> Number of P-States: 32 (800-3900 MHz)
> Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
> Injected C-States for CPU1 (C1,C2,C3,C6,C7)
> Warning: 'cpu-type' may be set improperly (0x0605 instead of 0x0905)
> - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
>   Compiling: ssdt_pr.dsl
>   Intel ACPI Component Architecture
>   ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
>   Copyright (c) 2000 - 2014 Intel Corporation
> 
> ASL Input:     /Users/bartek/Library/ssdtPRGen/ssdt.dsl - 309 lines, 9923 bytes, 49 keywords
> AML Output:    /Users/bartek/Library/ssdtPRGen/ssdt.aml - 1968 bytes, 16 named objects, 33 executable opcodes
> 
> Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Hallo. Should I worry about this error? This is something important?

**Comment by Piker-Alpha** [comment]
If you follow the link that I provide, then you see what it is i.e. a cosmetic only thing.
