### ISSUE TITLE
Can't create SSDT for i7 6800K - Directory issues

### ISSUE THREAD

**Issue by dr3nan** [Piker-Alpha/ssdtPRGen.sh#287]
Hello Pike,
Im trying to create a ssdt for the i7 6800K and the following error came up: At first it said the it couldn't find the 'tools' folder, which I downloaded afterwards and placed in the right location, and then this comes up (see picture), what am I doing wrong..?

![captura de pantalla 2016-10-26 a las 6 02 02](https://cloud.githubusercontent.com/assets/19169582/19726848/c9c13fb6-9b41-11e6-8733-1984cf02f183.png)

Let me know if you need any more info,

thx!

**Comment by dr3nan** [comment]
No need to worry!! 

I've found the answer in issue #100 after reading a while in the bug report section! Thank you so much anyway :)

**Comment by Piker-Alpha** [comment]
Good work finding that issue!
