### ISSUE TITLE
i5-6600K issue

### ISSUE THREAD

**Issue by oguz463** [Piker-Alpha/ssdtPRGen.sh#290]
Using sysdef 17,1
gDataPath: /Users/ouz/Library/ssdtPRGen/Data
System information: Mac OS X 10.12.1 (16B2555)
Brandstring 'Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
I cannot help you without additional information like how did you launch the script?
What arguments did you use?
Which version of the script are you using? 
Have you cleaned up the ~/Library/ssdtPRGen folder already (think rm -r ~/Library/ssdtPRGen)?

**Comment by oguz463** [comment]
I followed this https://www.tonymacx86.com/threads/quick-guide-to-generate-a-ssdt-for-cpu-power-management.177456/ then I tried to put skylake. cfg to library/data. i download latest one and without args.

**Comment by Piker-Alpha** [comment]
Please use the link from the README – to the beta branch – because the master branch hasn't had an update for ages. Don't forget to remove the old files!

**Comment by oguz463** [comment]
thanks for your support i really appreciate your hard work.

**Comment by Piker-Alpha** [comment]
Thanks. Please close this issue when the Beta is working for you.

**Comment by oguz463** [comment]
this is irrelevant but can u look at... some amd gpus driver cant initialize in sierra with clover. booting to black screen. especially 8000 and 9000 controllers. only way setting igpu as primary with blind boot. they say its sort of bootloader issue. anyway actually ive been following you since skylake thing. i believe when it comes to osx you are a magician.
