### ISSUE TITLE
i7-6700HQ Mac OS X 10.12.1 (MacBookPro13,3 Mac-A5C67F76ED83108C) Kernel Panic

### ISSUE THREAD

**Issue by idaima** [Piker-Alpha/ssdtPRGen.sh#293]
Hi,Pike!
I just use "./ssdtPRGen.sh"(ssdtPRGen version 21.1 ) generate the ssdt.aml,but it cause can not boot system.

**Comment by slayer2333** [comment]
Same issue here:
Alienware 15 R2 Skylake (Late 2015)
HM170 + Intel CPU 6820HK + Intel HD530 + Nvidia 980m GTX (optimus)
Sierra 10.12.1 (Build 2657)

**Comment by Piker-Alpha** [comment]
And you can you boot without the generated SSDT?

**Comment by slayer2333** [comment]
Yeah. As soon as i drop the generated SSDT.aml the system boots.

**Comment by idaima** [comment]
yes,when i drop  the generated SSDT.aml  the system can boot.

**Comment by idaima** [comment]
when i use "DummyX86PlatformPlugin.kext"，i can boot system.but "Energy - saving devices" is not working

**Comment by Piker-Alpha** [comment]
@slayer2333,

Do you also have this error: **AppleLPC:: start – RCBA not enabled**? Meaning that bit-0 is not set.

You could try to workaround this by commenting out your device-id from the AppleLPC.kext/Contents/Info.plist and see if it boots.

**Comment by slayer2333** [comment]
Yes i do have the error AppleLPC:: start – RCBA not enabled at boot.
So how do i get the device id to be removed from AppleLPC ?

**Comment by gustavocmotta** [comment]
I have the same error AppleLPC:: start – RCBA not enabled at boot and a CPU panic using SSDT.aml.
Without SSDT.aml It boots just fine. I commented pci8086,9cc1 on AppleLPC. AppleLPC was not loaded after boot. I´ve got the same CPU panic. My CPU is i7 6500u.

**Comment by idaima** [comment]
it's good news. i boot system success with ssdt and hwp ,please visit http://www.insanelymac.com/forum/topic/321021-guide-hwpintel-speed-shift-enable-with-full-power-management/
check it  by yourself~
thanks syscl and pike
