### ISSUE TITLE
M3 6Y30 shown as i5

### ISSUE THREAD

**Issue by ghost** [Piker-Alpha/ssdtPRGen.sh#296]
Device: Xiaomi Air 12"
Speedstep works with SSDT from this script, but CPU isn't shown as Intel Core M3 in "About this Mac", but as Intel Core i5. Just a cosmetic issue, but there should be a way to fix it, as the same CPU in MacBook9,1 works just fine.

**Comment by al3xtjames** [comment]
That has nothing to do with the SSDT. The label in About This Mac depends on `cpu-type`, which is injected by your bootloader.

**Comment by OttoEdler** [comment]
Ok. So what is the correct cpu type? Any way to find out the correct value?
