### ISSUE TITLE
Sript work for Ivy Bridge Celeron 1007U in 10.11.x but Panic in 10.12.x

### ISSUE THREAD

**Issue by sonvirgo** [Piker-Alpha/ssdtPRGen.sh#299]
It used to work with Ivy Bridge Celeron 1007U in 10.11.x -xcpm. But cause panic in 10.12.x
The infor is here https://www.tonymacx86.com/threads/sierre-upgrade-break-power-management-ivy-bridge.207802/#post-1375981

**Comment by Piker-Alpha** [comment]
I added the processor data for your Celeron to Data/User Defined.cfg and fired up the latest version of ssdtPRGen.sh like so:
```
./ssdtPRGen.sh -p 1007U -c 2 -xcpm 0
```
I need argument **-xcpm 0** because XCPM is enabled on my setup.

**Comment by sonvirgo** [comment]
Thank you
I hope this would help others who has same Ivy Bridge U 1xxx/2xxx too

**Comment by sonvirgo** [comment]
Do you include the processor data in the stable release or beta?
Because I try beta but it not work
`sun$ ~/ssdtPRGen.sh -b Mac-2E6FAB96566FE58C  -m MacBookAir5,2 -p 1007U -c 2  -x 0


ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.2 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.1 (16B2657)
Brandstring: "Intel(R) Celeron(R) CPU 1007U @ 1.50GHz"

Override value: (-b) board-id, now using: Mac-2E6FAB96566FE58C!
Override value: (-m) model, now using: MacBookAir5,2!
Override value: (-p) processor model, now using: 1007U!
Override value: (-c) CPU workarounds, now set to: 2!
Override value: (-x) XCPM mode, now set to: 0!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.
`

**Comment by sonvirgo** [comment]
Sorry. I confirm removing old release and it work.
![img_20161125_113303](https://cloud.githubusercontent.com/assets/10823037/20614713/b6afaf04-b304-11e6-8827-1260ac363a62.jpg)
![screen shot 2016-11-25 at 11 41 41 am](https://cloud.githubusercontent.com/assets/10823037/20614758/c2c1900a-b304-11e6-9a1a-d0fbddc79293.png)

**Comment by Piker-Alpha** [comment]
Ok. Thank you for this confirmation.

**Note**: People with a different processor model will need to add the processor data to: Data/User Defined.cfg
