### ISSUE TITLE
Missing processor

### ISSUE THREAD

**Issue by php75** [Piker-Alpha/ssdtPRGen.sh#300]
Hi,
before all, thank you for your great job.
I own two of http://ark.intel.com/de/products/96899/Intel-Xeon-Processor-E5-2699A-v4-55M-Cache-2_40-GHz , but ES version that doesn't give motherboard the processor version.
What can I do to use successfully ssdtPRGen.sh and get power management working?
Thank you for your answer
[Result_ssdtPRGen.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/607949/Result_ssdtPRGen.txt)

**Comment by Piker-Alpha** [comment]
I added the missing processor data to Broadwell.cfg and you can use it with:
```
./ssdtPRGen -p 'E5-2699A v4'
```

**Comment by php75** [comment]
Thank you very much
