### ISSUE TITLE
Unknown processor of i don't understand

### ISSUE THREAD

**Issue by zer969696** [Piker-Alpha/ssdtPRGen.sh#302]
ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/benzoback/Library/ssdtPRGen/Data
System information: Mac OS X 10.11.6 (15G31)
Brandstring 'Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by zer969696** [comment]
Hello, this is output after i ran ~/ssdtPRGen.sh, could you please tell me, what should i do? with much thanks

**Comment by Piker-Alpha** [comment]
Please do **not** use the old script from the master branch. Please use the one from the beta branch.

**Comment by Piker-Alpha** [comment]
Closing issue due to the use of an older/unsupported version.
