### ISSUE TITLE
I got Error until execute script

### ISSUE THREAD

**Issue by dhdhxk** [Piker-Alpha/ssdtPRGen.sh#304]
$ sudo ./ssdtPRGen.sh 

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.2 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.11.6 (15G31)
Brandstring: "Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz"

Version: models.cfg v150 / Haswell.cfg v151

Scope (_PR_) {1646 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,1' with board-id [Mac-031B6874CF7F642A]
Haswell Core i5-4570R processor [0x40661] setup [0x0605]
With a maximum TDP of 65 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 2700 MHz)
Number of Turbo States: 5 (2800-3200 MHz)
Number of P-States: 25 (800-3200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/mac-admin/Library/ssdtPRGen/ssdt.dsl - 270 lines, 9457 bytes, 49 keywords
AML Output:    /Users/mac-admin/Library/ssdtPRGen/ssdt.aml - 1801 bytes, 16 named objects, 33 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

Do you want to copy /Users/mac-admin/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml? (y/n)? y
cp: /Extra/ssdt.aml: No such file or directory
umount: /Volumes/EFI: not currently mounted
Do you want to open ssdt.dsl (y/n)? y

it said no such file or directory for ssdt.aml. Do you know why it happened?

And also EFI volume is mounted, but it said not currently mounted,

Thanks!

**Comment by dhdhxk** [comment]
It seems script copy /Users/mac-admin/Library/ssdtPRGen/ssdt.aml to /Extra/ssdt.aml, but I can`t find such directory as that. What am I suppose to do? I believe this script generate file and copy that file into somewhere, so it can work. and also it seems that destination will be somewhere in EFI volumn. Please let me know am I getting right direction and let me know how to fix it. Thanks.

**Comment by Piker-Alpha** [comment]
Thank you for reporting this issuer here. I added a new check in v21.4 to remedy this; and thus we will no longer (try to) copy the generated file to a none existing directory. The question: "Do you want to copy..." should now (in this specific case) also be skipped.

You should copy the generated file to the Clover directory (see WiKi).
