### ISSUE TITLE
Add i7-5600u data?

### ISSUE THREAD

**Issue by rsend** [Piker-Alpha/ssdtPRGen.sh#307]
Trying to run this on a board with an i7-5600u. I looked at your Haswell data file, it's not currently included. What's the quickest / best way to add this?

**Comment by al3xtjames** [comment]
i7-5600U is Broadwell, and [is already present in Broadwell.cfg](https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/Broadwell.cfg#L154).
