### ISSUE TITLE
Kaby Lake i5-7200U - seems unsupported

### ISSUE THREAD

**Issue by t-anjan** [Piker-Alpha/ssdtPRGen.sh#308]
I have a Kaby Lake i5-7200U processor. I can see that there is a `Kaby Lake.cfg` file with the required data for my processor. But when I execute the ssdtPRGen.sh script, it says Unknown Processor Model.

Output of `./ssdtPRGen.sh -d 2` below.

```
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.2 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.1 (16B2555)
Brandstring: "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz"

Override value: (-d) debug mode, now using: 2!

Setting executing bit of extractACPITables ...
_checkForExecutableFile(extractACPITables) Done.
Extracting ACPI tables ... Done.
Checking User Defined processor data ...
Checking Sandy Bridge processor data ...
Checking Ivy Bridge processor data ...
Checking Haswell processor data ...
Checking Broadwell processor data ...
Checking Skylake processor data ...

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.
```
ACPI.zip attached.
[ACPI.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/646258/ACPI.zip)

I even tried passing the processor model number using `-p 'i5-7200U'`. But that gave an error as well:

```
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.2 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.1 (16B2555)
Brandstring: "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz"


Error: Invalid argument detected: -p i5–7200U (check ssdtPRGen.sh -h)
Aborting ...
Done.
```

What could be the problem?

**Comment by t-anjan** [comment]
Okay, I figured out what the issue is. The attached image should make it clear.

The Kaby Lake cfg file has some "faulty" hyphen characters. Replacing them with regular hyphens solved the issue.

You can close the ticket when the file has been fixed in the repo. If you want me to make a PR for this, please let me know.

![screen shot 2016-12-14 at 12 57 20 am](https://cloud.githubusercontent.com/assets/743179/21155635/dff5f506-c198-11e6-9e5a-e866d7c968f9.png)

**Comment by Piker-Alpha** [comment]
Oops. Good catch. Thanks!
