### ISSUE TITLE
Can't boot with SSDT using MacBookPro13,2

### ISSUE THREAD

**Issue by ben9923** [Piker-Alpha/ssdtPRGen.sh#311]
Hello,
I created an SSDT.aml using ssdtPRGen.sh.
CPU: i5-6200U Skylake
Configuration: MacBookPro13,2
I used the beta branch, of course.
When booting after a copy to \Volumes\EFI\EFI\CLOVER\ACPI\patched, I get an error.
Screenshot is attached, and also my CLOVER folder+IOReg+some terminal commands outputs.
I manually added the SSDT for the uploaded file as I can't boot with it. IOReg copy was made when booting without it as well.
Any solution? I saw another MBP2016 boot failure comment on this tonymacx86 thread:
https://www.tonymacx86.com/threads/native-power-management-smbios-configuration.212093/#post-1412630

I successfully boot without the SSDT, didn't try a different SMBIOS since only one if the MBP2016's is appropriate for a Skylake laptop. (I was using an older SMBIOS before, but didn't try to use ssdtPRGen because I needed a Skylake SMBIOS)

Here is the terminal output when running ssdtPRGen.sh:

```
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.3 (16D32)
Brandstring: "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz"

Version: models.cfg v160 / Skylake.cfg v193


Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'MacBookPro13,2' with board-id [Mac-66E35819EE2D0D05]
Skylake Core i5-6200U processor [0x406E3] setup [0x0605]
With a maximum TDP of 15 Watt, as specified by Intel
Number logical CPU's: 4 (Core Frequency: 2300 MHz)
Number of Turbo States: 5 (2400-2800 MHz)
Number of P-States: 24 (500-2800 MHz)
Adjusting C-States for detected (mobile) processor
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: Model identifier (MacBookPro13,2) not found in..: /S*/L*/CoreServices/PlatformSupport.plist

Warning: 'cpu-type' may be set improperly (0x0605 instead of 0x0905)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20161210-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/benraz/Library/ssdtPRGen/ssdt.dsl - 301 lines, 10483 bytes, 49 keywords
AML Output:    /Users/benraz/Library/ssdtPRGen/ssdt.aml - 1844 bytes, 16 named objects, 33 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
Do you want to open ssdt.dsl (y/n)? n
Bens-MacBook-Pro:~ benraz$ 
```

I saw this odd message, can it cause the problem?

> Warning: Model identifier (MacBookPro13,2) not found in..: /S*/L*/CoreServices/PlatformSupport.plist

[ben9923.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/705266/ben9923.zip)
![img_9111](https://cloud.githubusercontent.com/assets/20676420/21944673/13e0044c-d9e0-11e6-867d-5669f8c0a80c.JPG)

**Comment by ben9923** [comment]
Fixed using your locked MSR 0xE2 idle patch (With the help of RehabMan):
`Comment: MSR 0xE2 _xcpm_idle instant reboot (c) Pike R. Alpha`
`MatchOS: 10.12`
`Find:    20b9e200 00000f30`
`Replace: 20b9e200 00009090`

I would recommend posting about this patch, I'm not sure many are aware it exists.
With your freqVectorsEdit I even reach 0.5Ghz when idle, thanks! :)

**Comment by Judder** [comment]
Hopefully obvious if you are here, but the MSR 0xE2 patch needs to be updated to also include OS 10.13 if you are using High Sierra

```
                <key>KernelToPatch</key>
                <array>
                        <dict>
                                <key>Comment</key>
                                <string>MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha</string>
                                <key>Disabled</key>
                                <false/>
                                <key>Find</key>
                                <data>
                                ILniAAAADzA=
                                </data>
                                <key>MatchOS</key>
                                <string>10.12,10.13</string>
                                <key>Replace</key>
                                <data>
                                ILniAAAAkJA=
                                </data>
                        </dict>
                </array>
```
