### ISSUE TITLE
": unterminated substitute pattern Same processor as below

### ISSUE THREAD

**Issue by Niresh12495** [Piker-Alpha/ssdtPRGen.sh#319]
System information: Mac OS X 10.12.3 (16D32)
Brandstring: "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz"

Version: models.cfg v150 / Skylake.cfg v193

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMac14,1' with board-id [Mac-031B6874CF7F642A]
Skylake Core i7-6700K processor [0x506E3] setup [0x0705]
With a maximum TDP of 91 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 4000 MHz)
Number of Turbo States: 2 (4100-4200 MHz)
Number of P-States: 35 (800-4200 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7,C8,C9,C10)
Injected C-States for CPU1 (C1,C2,C3,C6,C7)
Warning: 'cpu-type' may be set improperly (0x0705 instead of 0x0905)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_typesed: 1: "s/^[\n]*
Error://
": unterminated substitute pattern

Error:
Do you want to continue (y/n)?

**Comment by Piker-Alpha** [comment]
I cannot reproduce this. It may be an error in one of your cfg files. What you can do is uncomment the line with: **set -x** at the top of the script/run it again, and see where it fails.

**Comment by Niresh12495** [comment]
I have fixed it

**Comment by Piker-Alpha** [comment]
Ok. Cool. So how did you fix it?

**Comment by Niresh12495** [comment]
The smbios being used wasn't  an appropriate one i checked it from the verbose output
