### ISSUE TITLE
Add i7 7700HQ Please

### ISSUE THREAD

**Issue by stijn-d** [Piker-Alpha/ssdtPRGen.sh#320]
Is it possible to add the following kabylake processor:
Core i7 7700HQ
4 cores
8 threads
base clock 2800Mhz
Turbo clock 3800Mhz
Max tdp 45W

more info on intel ark: https://ark.intel.com/products/97185/Intel-Core-i7-7700HQ-Processor-6M-Cache-up-to-3_80-GHz

**Comment by Piker-Alpha** [comment]
Processor added. Please verify. Thanks.
