### ISSUE TITLE
Add i5-7500

### ISSUE THREAD

**Issue by alexsarmiento** [Piker-Alpha/ssdtPRGen.sh#321]
`sudo ./ssdtPRGen.sh

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.3 (16D32)
Brandstring: "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz"

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.
`

**Comment by Piker-Alpha** [comment]
Processor data added.
