### ISSUE TITLE
Intel core i7 6700k never reaches 800 Mhz state and TDP wrong at 95 Watts

### ISSUE THREAD

**Issue by locmer** [Piker-Alpha/ssdtPRGen.sh#323]
After using the latest beta ssdtPRGen.sh I noticed the following:

Noticed my Intel core i7 6700k never goes below 1.5 Ghz . And the TDP is listed at 95 watts which should be 91 Watt. I am wondering why the system never goes below 1.5 down to 800. I have reduced as much as possible thew load on the system, and yes I realise measuring is a load too. But I think something must not be right.

Sierra 10.12.3, GA-Z1700N-WIFI 2.0

[ssdt-dsl.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/793897/ssdt-dsl.txt)
[AppleIntelInfo-dat.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/793879/AppleIntelInfo-dat.txt)

**Comment by JrCs** [comment]
If you look at your AppleIntelInfo-dat.txt file you will see that it goes to 800Mhz (8):
CPU P-States [ **(8)** 12 14 15 16 19 20 21 22 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 ]

**Comment by Piker-Alpha** [comment]
The TDP in Skylake.cfg is set to 91 Watt. Not 95 Watt. See https://github.com/Piker-Alpha/ssdtPRGen.sh/blob/Beta/Data/Skylake.cfg#L48

The frequency will drop to lower frequencies, as you can see in the above list (note the 12 and 14 there).

Lowest frequencies will only be triggered when C-States are enabled in the BIOS and are working. Now take a look at your list and note the 8 (for 800MHz) so it does work. You can change this behaviour even further by modifying the FrequencyVectors manually, or run a newer version of the script. Then even Intel's Power Gadget will step down to 800MHz.
