### ISSUE TITLE
Core i3-380M issues

### ISSUE THREAD

**Issue by Eljeddi** [Piker-Alpha/ssdtPRGen.sh#347]
i tried thousands of solutions , tried with all arguments , is it possible that  my cpu isn't supported so i have to give up? 

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/eljeddi/Library/ssdtPRGen/Data
System information: Mac OS X 10.10.1 (14B25)
Brandstring 'Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
The Intel i3 m380 processor is too old. You need to add the missing processor data to your copy of Data/Users Defined.cfg
