### ISSUE TITLE
Error on script

### ISSUE THREAD

**Issue by Zacharybinx34** [Piker-Alpha/ssdtPRGen.sh#355]
receiving the following error:

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.5 (16F73)
Brandstring: "Intel(R) Core(TM)2 Duo CPU E8500 @ 3.16GHz"

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
See README.md (For older pre-Core I Intel processors see: ~/Library/Data/User Defined.cfg).
