### ISSUE TITLE
e5-2696 v3 unknown CPU Issue

### ISSUE THREAD

**Issue by xcry28xx** [Piker-Alpha/ssdtPRGen.sh#356]
hello.

I am using Xeon E5-2696 v3 CPU.

However, any value between CloverConfig file CPU Type items will be output only to CPUs that are not known.

I'm sorry, is there any way I can get it right?

Best Regards.

**Comment by maleorderbride** [comment]
Fill out User Defined to create an SSDT for that CPU. It works.

**Comment by Piker-Alpha** [comment]
Xeon E5-2696 v3 appears to be an OEM processor and I don't have the data for this processor. I need something like this: 'E5-2696 v3',120,1200,2300,3300,14,28

Please verify the TDP (120) frequency (3300) and max Turbo Frequency (3300), Core count and thread count.

Thank you.

**Comment by wuya2357** [comment]
fyi
'E5-2696 v3',145,1200,2300,3800,18,36
from https://en.wikipedia.org/wiki/List_of_Intel_Xeon_microprocessors

**Comment by maxx7650** [comment]
I would like this too, having the same cpu

**Comment by Piker-Alpha** [comment]
Thanks. Data Added.

**Comment by maxx7650** [comment]
Thank you Sir highly appreciated!!

**Comment by xcry28xx** [comment]
Thank you very much.

Finally, can I say one problem?

Almost everything works fine, but on Windows systems with maximum frequency, all cores work at 2.8Ghz.

In the macOS 10.12 or 10.13 build, however, all cores will operate at a maximum frequency of 2.6Ghz.

I looked through all of the forums and tried kernel patches or bios settings, but I could not solve them.

I would really appreciate it if you could give me a solution to this.

Regards.

**Comment by wuya2357** [comment]
@xcry28xx 
u need a clover patch to remove turbo frequency limit.seems a kerneltopatch entry.
sorry,u need search it by yourself.i'm not use my pc now.
also check your xcpm is alright.
