### ISSUE TITLE
having issues creating ssdt for i7-960

### ISSUE THREAD

**Issue by Culted** [Piker-Alpha/ssdtPRGen.sh#357]
i am trying to use ssdtprgen to create ssdt for i7-960 the script does not support i7-960 so i created a "User Defined.cfg" and addet this to it

gUserDefinedCPUList=(
i7-960,130,1596,3192,3458,4,8
)

when running ssdprgen with or without "-p i7-960"  i am always getting the error

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/rhokl/Library/ssdtPRGen/Data

System information: Mac OS X 10.12.5 (16F73)
Brandstring 'Intel(R) Core(TM) i7 CPU @ 9600 @ 3.20GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
User error. Data incomplete. See the data that I added to Data/User Defined.cfg in the repository.
