### ISSUE TITLE
Kabyl Lake-X Support

### ISSUE THREAD

**Issue by maleorderbride** [Piker-Alpha/ssdtPRGen.sh#363]
Hi Pike!

Hope all is well with you and your family.

I have an i5-7640x running on an X299 board, but ssdtPRGen of course says unknown processor model. Just hoping you can add support as both Kabyl Lake-X and Skylake-X are bootable in MacOS! 

I added in User Defined: 
'i5-7640X',112,800,4000,4200,4,4,64,100

But with -p I get:
System information: Mac OS X 10.12.6 (16G29)
Brandstring: "Intel(R) Core(TM) i5-7640X CPU @ 4.00GHz"

Override value: (-p) processor model, now using: i5-7640X!

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by Piker-Alpha** [comment]
Hi,

The data was added a week ago. All fine now?
