### ISSUE TITLE
Turbo Frequency in i7-5820K

### ISSUE THREAD

**Issue by arifzeeshan** [Piker-Alpha/ssdtPRGen.sh#364]
[sudo cat :tmp:AppleIntelInfo.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/1202052/sudo.cat.tmp.AppleIntelInfo.txt)
It doesn't reach the turbo frequency. 
![screen shot 2017-08-05 at 6 54 43 am](https://user-images.githubusercontent.com/26674272/28991781-27c6a7e8-79ab-11e7-933f-443096ec19f2.png)

[ssdt.aml.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/1202001/ssdt.aml.zip)
[ssdtPRGen.sh -a CPU0 -turbo 3600.txt](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/1202002/ssdtPRGen.sh.-a.CPU0.-turbo.3600.txt)

**Comment by maleorderbride** [comment]
Do you have EIST disabled in the BIOS?

**Comment by arifzeeshan** [comment]
Yes, it is disabled.

**Comment by arifzeeshan** [comment]
Fixed it ! 
I had to set  `"CPU Core Ratio" to "Sync all Cores"`  and  `"1-Core Ratio Limit" to 36.`
