### ISSUE TITLE
SSDT_pr.aml not generating

### ISSUE THREAD

**Issue by garypower** [Piker-Alpha/ssdtPRGen.sh#371]
Hey Pike, 

Thanks for producing this awesome script works great for my 10.10 build but unfortunately the SSDT_pr.aml file doesn't seem to generate on 10.12. 

Please see below the output of ./ssdtPRGen.sh -d 2 as requested in the Read Me.

`iMac:~ Gary$ ./ssdtPRGen.sh -d 2
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.6 (16G29)
Brandstring: "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz"

Override value: (-d) debug mode, now using: 2!

Setting executing bit of extractACPITables ...
_checkForExecutableFile(extractACPITables) Done.
Extracting ACPI tables ... Done.
Checking User Defined processor data ...
Checking Sandy Bridge processor data ...
Checking Ivy Bridge processor data ...
Processor data found for the Intel i7-3770
Version: models.cfg v170 / Ivy Bridge.cfg v150

Name (_HID, "ACPI0004") NOT found in DSDT
1 Scope (_PR_) {..} object(s) found in DSDT
scopeObjectData: 104e065f50525f
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4e/78
packageLength: 0x06e/110
scopeLength: 110
scopeLength: 208 (egrep pattern length: 12)
scopeObjectData length 222 (includes egrep pattern)
processorID: 01 CPU0
processorID: 02 CPU1
processorID: 03 CPU2
processorID: 04 CPU3
processorID: 05 CPU4
processorID: 06 CPU5
processorID: 07 CPU6
processorID: 08 CPU7

Scope (_PR_) {222 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Number of Scopes: 1
Generating ssdt.dsl for a 'iMac13,2' with board-id [Mac-FC02E91DDD3FA6A4]
Ivy Bridge Core i7-3770 processor [0x306A9] setup [0x0704]
With a maximum TDP of 77 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 3400 MHz)
Number of Turbo States: 5 (3500-3900 MHz)
Number of P-States: 24 (1600-3900 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 7
Adding C1
Adding C2
Adding C3
Injected C-States for CPU0 (C1,C3,C6)
Injected C-States for CPU1 (C1,C2,C3)

Compiling: ssdt_pr.dslDo you want to open ssdt.dsl (y/n)? n`

I have also attached the compressed version of ~/Library/ssdtPRGen/ACPI folder
[ACPI.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/1222012/ACPI.zip)

It seems to me that the script quits after the first question without warning. Am I running it wrong?

**Comment by garypower** [comment]
Hey Piker,

I opened the ssdt.dsl by pressing 'y' to the first question. This allowed me to save the output to my desktop and open in MacIASL. I then exported it as .aml file to the EFI partition in the correct directory. 

Restarted and I now have some speed stepping of the CPU but not the IGPU. I think this is a configuration issue on my part. I will work on it. Can you tell me is this the correct operation?

**Comment by Piker-Alpha** [comment]
The script should ask you to copy the file (from ~/Library/ssdtPRGen/ssdt-pr.aml) to a target location. This feature may fail, in which case you need to do that yourself. Simply put. Just say no to the copy action and copy it yourself.

IGPU PM isn't part of the output of this script. Never was. Never will.

**Comment by garypower** [comment]
Thanks Piker, I copied the results myself and complied them to aml in another program. 

Thanks again to you and previous dev's. This is a great tool
