### ISSUE TITLE
Editting FrequencyVectors in Mac-27ADBB7B4CEE8E61.plist

### ISSUE THREAD

**Issue by Beefcat** [Piker-Alpha/ssdtPRGen.sh#372]
Hi @Piker-Alpha ,

Thank for sharing your knowledge and tons of experience with us. Appreciate your effort and all your inputs.

I have been using your script ssdtPRGen.sh since 2014 with success.

I'm trying to edit the FrequencyVectors key in X86PlatformPlugin.kext/Contents/Resources/Mac-27ADBB7B4CEE8E61.plist (which corresponds to iMac14,2) to reduce LFM from 1000MHz to 600MHz. 

The problem is I don't know which values to change. I had a look at another post but to be honest  i don't know which value should be changes in the frequency vector and what the new value should be  

My cpu is the intel i7 4790K 

Kind regards

**Comment by Beefcat** [comment]
Please see attachments:

**Comment by Piker-Alpha** [comment]
Let's start with the processor model that you have. Does it even support 500MHz as LFM? Have you checked this?

You have two options. As far as I am aware of. The first one is to use -cpuid as boot argument and the other is to use AppleIntelInfo.kext

The trick is to alter the FreqVectors data. Here are two examples:

02 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 (no limit set)
02 00 00 00 0D 00 00 00 01 00 00 00 00 00 00 00 (0x0d/1300MHz set as limit).

**Comment by Beefcat** [comment]
Thank you for your reply,

I don't think its does, in fact I have seen some post around freezing if clock speed is below 800MHz. So I'm happy with this machine then. 

Thank you for keeping me in the railway track. Appreciate the effort.

Also, I have a MacBook Pro 13,1 with a i5-7200U processor. I will post my question on another thread that relates to that specific model. 

You can mark this issue as closed
