### ISSUE TITLE
Macbook Pro 13,1 :  P and C States (sleep)

### ISSUE THREAD

**Issue by Beefcat** [Piker-Alpha/ssdtPRGen.sh#373]
Hi @pikeralpha,

About 3 months ago i tried your script for board-id Mac-473D31EABEB93F9B. The script returned an error stating "board-id not supported"

So, i used clover to set HWPEnable and HWPValue. This works but after sleep i loose the idle clock speed value witch should be 800MHz. 

I noticed that :

1. Kaby lake config file now has the configuration data for "i5-7200U,15,500,2500,3100,2,4"
2. Models config now have the data for  board-id  Mac-473D31EABEB93F9B:MacBookPro13,1

To be honest, your work is documented very well but for the novice it is quite challenging to figure out what the difference is between using your script ssdtPRGen.sh and using HWP settings? Is this documented somewhere ?

I would much rather use your script, will the P & C states stick after sleep with your script ? Or is there something special that i need to configure besides running the script the generate the appropriate aml file.

Regards.

**Comment by Piker-Alpha** [comment]
Thanks.

The main difference between HWP and ACPI P/C-States is that the former is hardware controlled (by Intel) versus ACPI software controlled power management. In short. It is either controlled by hardware _or_ the – drivers of the – operating system. Not both.

Currently there is still no driver that controls the HWP hints (read MSR's) but that may change soon.

**Comment by Beefcat** [comment]
thank you for this insight. Appreciate it !
