### ISSUE TITLE
i7-930 Error

### ISSUE THREAD

**Issue by bytesandbolts** [Piker-Alpha/ssdtPRGen.sh#380]
Add specs for an i7-930 to 'User defined.cfg' as follows:

i7-930,130,1600,2800,3060,4,8,0,133

Appear to be getting 3 warnings and 1 error during compile.

$ ./ssdtPRGen.sh -p i7-930 -d 2
ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2017 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.12.6 (16G29)
Brandstring: "Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz"

Override value: (-p) processor model, now using: i7-930!
Override value: (-d) debug mode, now using: 2!

Setting executing bit of extractACPITables ...
_checkForExecutableFile(extractACPITables) Done.
Extracting ACPI tables ... Done.
Checking User Defined processor data ...
Processor data found for the Intel i7-930
Version: models.cfg v150 / User Defined.cfg v-1

Name (_HID, "ACPI0004") NOT found in DSDT
1 Scope (_PR_) {..} object(s) found in DSDT
scopeObjectData: 10460d5f50525f
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x46/70
packageLength: 0x0d6/214
scopeLength: 214
scopeLength: 416 (egrep pattern length: 12)
scopeObjectData length 430 (includes egrep pattern)
processorID: 00 CPU0
processorID: 01 CPU1
processorID: 02 CPU2
processorID: 03 CPU3
processorID: 04 CPU4
processorID: 05 CPU5
processorID: 06 CPU6
processorID: 07 CPU7

Scope (_PR_) {430 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Number of Scopes: 1
Generating ssdt.dsl for a 'MacPro5,1' with board-id [Mac-F221BEC8]
Intel i7-930 processor [0x106A5] setup [0x0701]
With a maximum TDP of 130 Watt, as specified by Intel
Number logical CPU's: 8 (Core Frequency: 2800 MHz)
Number of Turbo States: 1 (2933-3060 MHz)
Number of P-States: 11 (1600-3060 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for CPU0 (C1,C3,C6)
Warning: 'cpu-type' may be set improperly (0x0701 instead of 0x01)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/CPU#cpu_type
Warning: 'board-id' [Mac-F221BEC8] is not supported by Unknown power management
Warning: 'system-type' may be set improperly (1 instead of 0)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/ACPI#acpi_smartupsSetting executing bit of iasl ...
_checkForExecutableFile(iasl) Done.

Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

/Users/dansmith/Library/ssdtPRGen/ssdt.dsl     33:         Name (APSS, Package (0x0B)
Error    6062 -              Initializer list longer than declared package length ^ 

ASL Input:     /Users/dansmith/Library/ssdtPRGen/ssdt.dsl - 184 lines, 4547 bytes, 36 keywords

Compilation complete. 1 Errors, 0 Warnings, 0 Remarks, 1 Optimizations
Error: IASL status: 255 (Failed)

**Comment by Piker-Alpha** [comment]
User error. Use the correct data for the max turbo frequency (3066 -> 2800, 2933 and 3066)
