### ISSUE TITLE
i7-3770K SSDT Turbo not working

### ISSUE THREAD

**Issue by schteeben95** [Piker-Alpha/ssdtPRGen.sh#381]
I've spent the entire afternoon already on it and am not planning on waste much more time on this matter, so I thought I'd seek help from someone who actually knows what they are talking about.

I generated my SSDT by: `./ssdtPRGen.sh -f 3500 -turbo 4500 -c 2` on a i7-3770K overclocked in motherboard to 4500MHz (which works under Windows with CPU-Z). 

The result from AppleIntelInfo is:

```
AppleIntelInfo.kext v1.2 Copyright © 2012-2015 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 1
logIGPU............................: 0
logIntelRegs.......................: 1
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0x3fc14cdfa3
MWAIT C-States.....................: 4384

Model Specific Regiters
------------------------------------
MSR_CORE_THREAD_COUNT......(0x35)  : 0x40008
MSR_PLATFORM_INFO..........(0xCE)  : 0x81010F0012300
MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E008400
MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
IA32_MPERF.................(0xE7)  : 0x1AC89038FB
IA32_APERF.................(0xE8)  : 0x1A9FD9F7BC
MSR_FLEX_RATIO.............(0x194) : 0xE0000
MSR_IA32_PERF_STATUS.......(0x198) : 0x23B500002300
MSR_IA32_PERF_CONTROL......(0x199) : 0x2300
IA32_CLOCK_MODULATION......(0x19A) : 0x0
IA32_THERM_STATUS..........(0x19C) : 0x88410000
IA32_MISC_ENABLES..........(0x1A0) : 0x850089
MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x2D2D2D2D
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x0
MSR_POWER_CTL..............(0x1FC) : 0x14005F
MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
MSR_PKG_POWER_LIMIT........(0x610) : 0x8FA000148FA0
MSR_PKG_ENERGY_STATUS......(0x611) : 0x69CB228
MSR_PKG_POWER_INFO.........(0x614) : 0x1E00268
MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x18141494000004B0
MSR_PP0_POWER_LIMIT........(0x638) : 0x0
MSR_PP0_ENERGY_STATUS......(0x639) : 0x5654B2A
MSR_PP0_POLICY.............(0x63a) : 0x0
MSR_CONFIG_TDP_NOMINAL.....(0x648) : 0x23
MSR_CONFIG_TDP_LEVEL1......(0x649) : 0x1E0000000000000
MSR_CONFIG_TDP_LEVEL2......(0x64a) : 0x1E0000000000000
MSR_CONFIG_TDP_CONTROL.....(0x64b) : 0x80000000
MSR_TURBO_ACTIVATION_RATIO.(0x64c) : 0x0
MSR_PKGC3_IRTL.............(0x60a) : 0x883B
MSR_PKGC6_IRTL.............(0x60b) : 0x8850
MSR_PKGC7_IRTL.............(0x60c) : 0x8857
MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x0
MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
IA32_TSC_DEADLINE..........(0x6E0) : 0x3FC41801A9

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1600 MHz
CPU Maximum non-Turbo Frequency....: 3500 MHz
CPU Maximum Turbo Frequency........: 4500 MHz
CPU P-States [ (16) 35 ]
CPU C6-Cores [ 3 4 5 7 ]
CPU C6-Cores [ 2 3 4 5 6 7 ]
CPU P-States [ (16) 34 35 ]
CPU P-States [ (16) 30 34 35 ]
CPU P-States [ 16 29 30 34 (35) ]
CPU P-States [ (16) 29 30 33 34 35 ]
CPU P-States [ 16 29 30 31 33 34 (35) ]
CPU P-States [ (16) 29 30 31 32 33 34 35 ]
CPU P-States [ (16) 28 29 30 31 32 33 34 35 ]
CPU P-States [ (16) 26 28 29 30 31 32 33 34 35 ]
CPU P-States [ (16) 24 26 28 29 30 31 32 33 34 35 ]
CPU P-States [ (16) 24 26 27 28 29 30 31 32 33 34 35 ]
```

However, running Intel Power Gadget, the clock never goes above 35 despite the "Maximum Turbo Frequency" being 4500MHz. 

```
> sysctl machdep.xcpm.mode
machdep.xcpm.mode: 0
```

Can someone please help with this issue? It's driving me crazy.

**Comment by schteeben95** [comment]
Resolved.

Turned out the `NullCPUPowerManagement` was loaded. 
If you are facing similar issues:

 - `kextstat | grep -y nullCPU` should return nothing
 - if it returns something, find the `NullCPUPowerManagement.kext` by `sudo find / -name "NullCPUPowerManagement.kext` and delete those.
 - Your computer might not boot now. Follow the following guide:

1. Boot with your UniBeast-created USB installer.
2. Patch your `AppleIntelCPUPowerManagement.kext` with this guide:
    http://www.insanelymac.com/forum/topic/295587-power-management-for-sandyivy-bridgehaswell-cpus/
3. Boot. You now should be able to boot into the system.
4. Create the SSDT with the script from this repo.
5. Viola!

**Comment by schteeben95** [comment]
```
Stevens-Mac-Pro:Desktop steven$ sudo cat /tmp/AppleIntelInfo.dat 

AppleIntelInfo.kext v1.2 Copyright © 2012-2015 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 1
logIGPU............................: 0
logIntelRegs.......................: 1
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0xc33f24c6a2
MWAIT C-States.....................: 4384

Model Specific Regiters
------------------------------------
MSR_CORE_THREAD_COUNT......(0x35)  : 0x40008
MSR_PLATFORM_INFO..........(0xCE)  : 0x81010F0012300
MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E008400
MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
IA32_MPERF.................(0xE7)  : 0x234D2909F9
IA32_APERF.................(0xE8)  : 0x29267E8B80
MSR_FLEX_RATIO.............(0x194) : 0xE0000
MSR_IA32_PERF_STATUS.......(0x198) : 0x273B00002D00
MSR_IA32_PERF_CONTROL......(0x199) : 0x2D00
IA32_CLOCK_MODULATION......(0x19A) : 0x0
IA32_THERM_STATUS..........(0x19C) : 0x883D0000
IA32_MISC_ENABLES..........(0x1A0) : 0x850089
MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400001
MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x2D2D2D2D
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x4
MSR_POWER_CTL..............(0x1FC) : 0x14005F
MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
MSR_PKG_POWER_LIMIT........(0x610) : 0x8FA000148FA0
MSR_PKG_ENERGY_STATUS......(0x611) : 0xFFD8DBD
MSR_PKG_POWER_INFO.........(0x614) : 0x1E00268
MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x18141494000004B0
MSR_PP0_POWER_LIMIT........(0x638) : 0x0
MSR_PP0_ENERGY_STATUS......(0x639) : 0xC646D90
MSR_PP0_POLICY.............(0x63a) : 0x0
MSR_CONFIG_TDP_NOMINAL.....(0x648) : 0x23
MSR_CONFIG_TDP_LEVEL1......(0x649) : 0x1E0000000000000
MSR_CONFIG_TDP_LEVEL2......(0x64a) : 0x1E0000000000000
MSR_CONFIG_TDP_CONTROL.....(0x64b) : 0x80000000
MSR_TURBO_ACTIVATION_RATIO.(0x64c) : 0x0
MSR_PKGC3_IRTL.............(0x60a) : 0x883B
MSR_PKGC6_IRTL.............(0x60b) : 0x8850
MSR_PKGC7_IRTL.............(0x60c) : 0x8857
MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x0
MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x0
MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0x0
MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
IA32_TSC_DEADLINE..........(0x6E0) : 0xC341F01B84

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1600 MHz
CPU Maximum non-Turbo Frequency....: 3500 MHz
CPU Maximum Turbo Frequency........: 4500 MHz
CPU P-States [ 36 (45) ]
CPU C3-Cores [ 0 2 3 4 5 ]
CPU C6-Cores [ 0 1 3 5 7 ]
CPU P-States [ 36 41 (45) ]
CPU C3-Cores [ 0 1 2 3 4 5 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 ]
CPU P-States [ (16) 36 38 41 45 ]
CPU C3-Cores [ 0 1 2 3 4 5 6 ]
CPU P-States [ 16 36 38 39 41 (45) ]
CPU P-States [ 16 36 37 38 39 41 (45) ]
CPU C3-Cores [ 0 1 2 3 4 5 6 7 ]
CPU P-States [ (16) 34 36 37 38 39 41 45 ]
CPU P-States [ 16 29 34 36 37 38 39 41 (45) ]
CPU P-States [ (16) 29 32 34 36 37 38 39 41 45 ]
CPU P-States [ 16 29 31 32 34 36 37 38 39 41 (45) ]
CPU P-States [ (16) 29 31 32 34 36 37 38 39 40 41 45 ]
CPU P-States [ 16 29 31 32 34 35 36 37 38 39 40 41 (45) ]
CPU P-States [ (16) 28 29 31 32 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ 16 26 28 29 31 32 34 35 36 37 38 39 40 41 (45) ]
CPU P-States [ (16) 26 28 29 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ (16) 20 26 28 29 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ (16) 20 23 26 28 29 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ 16 20 23 25 26 28 29 31 32 33 34 35 36 37 38 39 40 41 (45) ]
CPU P-States [ (16) 20 23 25 26 27 28 29 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ (16) 20 23 24 25 26 27 28 29 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ (16) 20 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 45 ]
CPU P-States [ (16) 20 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 45 ]
```
I'm also more than happy to help if you need!

**Comment by asedghi** [comment]
Hi A little help would be greatly appreciated ..
⇒  cat /tmp/AppleIntelInfo.dat

AppleIntelInfo.kext v1.2 Copyright © 2012-2015 Pike R. Alpha. All rights reserved

Settings:
------------------------------------
logMSRs............................: 1
logIGPU............................: 0
logIntelRegs.......................: 1
logCStates.........................: 1
logIPGStyle........................: 1
InitialTSC.........................: 0x589f5ddbbc
MWAIT C-States.....................: 4384

Model Specific Regiters
------------------------------------
MSR_CORE_THREAD_COUNT......(0x35)  : 0x40008
MSR_PLATFORM_INFO..........(0xCE)  : 0x81010F0012300
MSR_PMG_CST_CONFIG_CONTROL.(0xE2)  : 0x1E000403
MSR_PMG_IO_CAPTURE_BASE....(0xE4)  : 0x10414
IA32_MPERF.................(0xE7)  : 0x1DA24BDBCF
IA32_APERF.................(0xE8)  : 0x1E78369752
MSR_FLEX_RATIO.............(0x194) : 0xE0000
MSR_IA32_PERF_STATUS.......(0x198) : 0x24FD00002500
MSR_IA32_PERF_CONTROL......(0x199) : 0x1000
IA32_CLOCK_MODULATION......(0x19A) : 0x0
IA32_THERM_STATUS..........(0x19C) : 0x883F0000
IA32_MISC_ENABLES..........(0x1A0) : 0x850089
MSR_MISC_PWR_MGMT..........(0x1AA) : 0x400000
MSR_TURBO_RATIO_LIMIT......(0x1AD) : 0x25262727
IA32_ENERGY_PERF_BIAS......(0x1B0) : 0x1
MSR_POWER_CTL..............(0x1FC) : 0x14005F
MSR_RAPL_POWER_UNIT........(0x606) : 0xA1003
MSR_PKG_POWER_LIMIT........(0x610) : 0xA58000009F40
MSR_PKG_ENERGY_STATUS......(0x611) : 0xA07796C
MSR_PKG_POWER_INFO.........(0x614) : 0x1E00268
MSR_PP0_CURRENT_CONFIG.....(0x601) : 0x1814149400000960
MSR_PP0_POWER_LIMIT........(0x638) : 0xA580
MSR_PP0_ENERGY_STATUS......(0x639) : 0x77694C1
MSR_PP0_POLICY.............(0x63a) : 0x0
MSR_CONFIG_TDP_NOMINAL.....(0x648) : 0x23
MSR_CONFIG_TDP_LEVEL1......(0x649) : 0x1E0000000000000
MSR_CONFIG_TDP_LEVEL2......(0x64a) : 0x1E0000000000000
MSR_CONFIG_TDP_CONTROL.....(0x64b) : 0x80000000
MSR_TURBO_ACTIVATION_RATIO.(0x64c) : 0x0
MSR_PKGC3_IRTL.............(0x60a) : 0x883B
MSR_PKGC6_IRTL.............(0x60b) : 0x8850
MSR_PKGC7_IRTL.............(0x60c) : 0x8857
MSR_PKG_C2_RESIDENCY.......(0x60d) : 0x73A796DC3
MSR_PKG_C3_RESIDENCY.......(0x3f8) : 0x1C23A337E
MSR_PKG_C6_RESIDENCY.......(0x3f9) : 0xC62B3F2E5
MSR_PKG_C7_RESIDENCY.......(0x3fa) : 0x0
IA32_TSC_DEADLINE..........(0x6E0) : 0x58A0DC633F

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 1600 MHz
CPU Maximum non-Turbo Frequency....: 3500 MHz
CPU Maximum Turbo Frequency........: 3900 MHz
CPU P-States [ 35 (37) 38 ]
CPU C3-Cores [ 0 4 5 ]
CPU C6-Cores [ 0 1 4 5 6 ]
CPU C7-Cores [ 0 1 4 5 6 7 ]
CPU C3-Cores [ 0 4 5 6 7 ]
CPU C6-Cores [ 0 1 4 5 6 7 ]
CPU C7-Cores [ 0 1 3 4 5 6 7 ]
CPU C3-Cores [ 0 2 3 4 5 6 7 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 ]
CPU C7-Cores [ 0 1 2 3 4 5 6 7 ]
CPU P-States [ 35 36 (37) 38 ]
CPU C3-Cores [ 0 1 2 3 4 5 6 7 ]
CPU P-States [ (16) 35 36 37 38 ]

./ssdtPRGen.sh -f 3500 -turbo 4500 -c 2 (I'm overclocked turbo to 4500)

⇒  sysctl -n machdep.xcpm.mode
1

⇒  sysctl -n machdep.xcpm.vectors_loaded_count
1

kextstat | grep -y nullCPU (returns nothing)


What vector setting did you use? Are you using any clover settings? Any advice?  

Thanks!

**Comment by schteeben95** [comment]
I remember setting the max multiplier in clover to 48 but I don't think that did anything. 
Make sure that you have set the correct overclock in the motherboard. If you boot into windows, use CPUZ to check if the OC is working first.

**Comment by asedghi** [comment]
could you post your clover config..I must be missing something small..(PS Don't forget to remove your ids). thanks..
