### ISSUE TITLE
 E5-2673 v4 CPU

### ISSUE THREAD

**Issue by emenelton** [Piker-Alpha/ssdtPRGen.sh#383]
'E5-2673 v4',135,1200,2300,3600,20,40,16,100

**Comment by Piker-Alpha** [comment]
This issue is resolved by the patch for issue #378

**Comment by emenelton** [comment]
Dear Piker-Alpha,

 

thanks, sorry about the duplicate, when I finally understood how to add my CPU to the user cfg, I did this last ‘issue’ and included the number line of this additional issue in may edited user cfg. So that is what led to me doing that.

I still haven’t got the speedsteping to work on my X99M Killer 3.1 ASROCK but KGP did ‘hit me over the head’ one last time and hopefully I have the necessary steps in place to move forward.

 

Thank-you,

 

Chris
