### ISSUE TITLE
i7-8700k unterminated substitute pattern

### ISSUE THREAD

**Issue by glekner** [Piker-Alpha/ssdtPRGen.sh#404]
Followed the readme exactly as written,

ran: "sudo sh ssdtPRGen.sh -p 'i7-8700K' -turbo 4800"

and got this:

System information: Mac OS X 10.13.1 (17B48)
Brandstring: "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"

Override value: (-p) processor model, now using: i7-8700K!
Override value: (-turbo) maximum (turbo) frequency, now using: 4800 MHz!
sed: 1: "s/^[\n]*
Error://
": unterminated substitute pattern

Error:
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

Thanks

**Comment by ManThatCodesHeroically** [comment]
Apparently, you don’t need ssdts in clover anymore. Just open your config with clover configurator and go to acpi/ssdt and check “plugintype”
