### ISSUE TITLE
Unknown processor model G4560

### ISSUE THREAD

**Issue by hjmmc** [Piker-Alpha/ssdtPRGen.sh#419]
System information: Mac OS X 10.12.6 (16G1114)
Brandstring: "Intel(R) Pentium(R) CPU G4560 @ 3.50GHz"

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by zohaad** [comment]
Here's the link needed to fix
https://ark.intel.com/products/97143/Intel-Pentium-Processor-G4560-3M-Cache-3_50-GHz
