### ISSUE TITLE
Error: Unknown processor model

### ISSUE THREAD

**Issue by jayceepho** [Piker-Alpha/ssdtPRGen.sh#430]
Hello!

Came across this issue while running the script:

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2018 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/daddyphong/Library/ssdtPRGen/Data
System information: Mac OS X 10.13.2 (17C89)
Brandstring 'Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

What are the next steps here to troubleshoot? Thanks :)

**Comment by jayceepho** [comment]
Fixed, used beta version link:

curl -o ~/ssdtPRGen.sh https://raw.githubusercontent.com/Piker-Alpha/ssdtPRGen.sh/Beta/ssdtPRGen.sh

**Comment by notehaha** [comment]
got the same problem. thank for fix this issue
