### ISSUE TITLE
Dual E5-2670 kernel panic

### ISSUE THREAD

**Issue by BrushXue** [Piker-Alpha/ssdtPRGen.sh#511]
I'm on 10.15.4 with SMBIOS MacPro6,1. 
Here's the debug info of the ssdt file:
```
./ssdtPRGen.sh -cpus 2 -d 2 -p E5-2670 -target 1 -mode custom -x 0

ssdtPRGen.sh v0.9  Copyright (c) 2011-2012 by † RevoGirl
             v6.6  Copyright (c) 2013 by † Jeroen
             v21.5 Copyright (c) 2013-2020 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

System information: Mac OS X 10.15.4 (19E266)
Brandstring: "Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz"

Override value: (-cpus) number of processors, now using: 2!
Override value: (-d) debug mode, now using: 2!
Override value: (-p) processor model, now using: E5-2670!
Override value: (-target) CPU, now using: Ivy Bridge!
Override value: (-mode) script mode changed to custom!
Override value: (-x) XCPM mode, now set to: 0!

Checking User Defined processor data ...
Checking Sandy Bridge processor data ...
Processor data found for the Intel E5-2670
Version: models.cfg v171 / Sandy Bridge.cfg v150

4 Name (_HID, "ACPI0004") object(s) found in DSDT
matchingData:
5b824d9553434b30085f4849440d414350493030303400
5b824d9553434b31085f4849440d414350493030303400
5b824b9953434b32085f4849440d414350493030303400
5b824b9953434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
Device (SCK0): 
processorID: 00 C000
processorID: 01 C001
processorID: 02 C002
processorID: 03 C003
processorID: 04 C004
processorID: 05 C005
processorID: 06 C006
processorID: 07 C007
processorID: 08 C008
processorID: 09 C009
processorID: 0a C00A
processorID: 0b C00B
processorID: 0c C00C
processorID: 0d C00D
processorID: 0e C00E
processorID: 0f C00F

gScope              : 1
gProcessorStartIndex: 16
gLogicalCPUs        : 32
gProcessorNames     : 16
Searching for 0 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x4d/77
packageLength: 0x95d/2397
scopeLength: 2397
Device (SCK1): 
processorID: 10 C100
processorID: 11 C101
processorID: 12 C102
processorID: 13 C103
processorID: 14 C104
processorID: 15 C105
processorID: 16 C106
processorID: 17 C107
processorID: 18 C108
processorID: 19 C109
processorID: 1a C10A
processorID: 1b C10B
processorID: 1c C10C
processorID: 1d C10D
processorID: 1e C10E
processorID: 1f C10F

Number of Scopes: 2

Notice: Custom mode enabled
	Skipping ACPI table extraction from host computer!
	Getting enabled Processors from...: /Users/gux215/Desktop/APIC.aml
	Getting Processor declaration from: /Users/gux215/Desktop/DSDT.aml
	Used ACPI processor labels: 
	– C000 C001 C002 C003 C004 C005 C006 C007 C008 C009 C00A C00B C00C C00D C00E C00F
	– C100 C101 C102 C103 C104 C105 C106 C107 C108 C109 C10A C10B C10C C10D C10E C10F

Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Ivy Bridge Core E5-2670 processor [0x206D7] setup [0x0a01]
With a maximum TDP of 115 Watt, as specified by Intel
Number logical CPU's: 32 (Core Frequency: 2600 MHz)
Number of Turbo States: 7 (2700-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for C000 (C1,C3,C6)
Injected C-States for C001 (C1,C3,C6)
Setting executing bit of iasl ...
_checkForExecutableFile(iasl) Done.
```
With CPUFriend, I got a kernel panic:
```
panic(cpu 0 caller 0xffffff7f99fa009b): Setting P-Limit is unsupported on this system
Backtrace (CPU 0), Frame : Return Address
0xffffff8e2af5b740 : 0xffffff8016f215cd 
0xffffff8e2af5b790 : 0xffffff801705a3c5 
0xffffff8e2af5b7d0 : 0xffffff801704bf7e 
0xffffff8e2af5b820 : 0xffffff8016ec7a40 
0xffffff8e2af5b840 : 0xffffff8016f20c97 
0xffffff8e2af5b940 : 0xffffff8016f21087 
0xffffff8e2af5b990 : 0xffffff80176c2c7c 
0xffffff8e2af5ba00 : 0xffffff7f99fa009b 
0xffffff8e2af5ba10 : 0xffffff7f99f8ae58 
0xffffff8e2af5ba40 : 0xffffff7f99f91955 
0xffffff8e2af5bab0 : 0xffffff7f99f8fd35 
0xffffff8e2af5bae0 : 0xffffff7f99028f4c 
0xffffff8e2af5bb30 : 0xffffff8017630048 
0xffffff8e2af5bb90 : 0xffffff7f9902896d 
0xffffff8e2af5bcd0 : 0xffffff7f99029121 
0xffffff8e2af5bd10 : 0xffffff8017604c55 
0xffffff8e2af5bd70 : 0xffffff80176106b2 
0xffffff8e2af5bdb0 : 0xffffff7f990283af 
0xffffff8e2af5bde0 : 0xffffff8017608c06 
0xffffff8e2af5be40 : 0xffffff8017608741 
0xffffff8e2af5bef0 : 0xffffff8017607ade 
0xffffff8e2af5bf50 : 0xffffff801760a296 
0xffffff8e2af5bfa0 : 0xffffff8016ec713e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCPUPowerManagement(222.0)[26061535-11D1-3F9A-AE00-54B47B5D2607]@0xffffff7f99f84000->0xffffff7f99fadfff
         com.apple.driver.X86PlatformShim(1.0)[8AF7E94C-12F9-38A2-B896-4E415C68BC54]@0xffffff7f99027000->0xffffff7f9902ffff
            dependency: com.apple.driver.IOPlatformPluginFamily(6.0.0d8)[17CB276E-670F-34E8-B189-8906712914D8]@0xffffff7f98fc7000
            dependency: com.apple.driver.X86PlatformPlugin(1.0.0)[D2F3502B-0794-38BD-A592-5EDC3C4639D4]@0xffffff7f9900e000
            dependency: com.apple.driver.AppleSMC(3.1.9)[601E041E-0A5C-3B6A-A4E6-45ECC7F48A2B]@0xffffff7f9805e000

BSD process name corresponding to current thread: kernel_task
Boot args: npci=0x2000 -no_compat_check -v debug=0x100 
```
Now I'm using NullCPUPowerManagement temporarily. Any idea what's happening?

**Comment by useafterfree** [comment]
E5-2670 is not an Ivy Bridge CPU. Use: `-target 0` and give it a try.

**Comment by BrushXue** [comment]
> E5-2670 is not an Ivy Bridge CPU. Use: `-target 0` and give it a try.

I tried. If I use -target 0, the frequency vector is not even being injected. The CPU will be locked at 2.6GHz(same as doing nothing)

Check this Chinese website
https://bbs.pcbeta.org/viewthread-1691133-1-1.html (You may need Google Translate)
They mentioned that SNB-E CPUs need to be injected as IVB-E so that MacPro6,1 can recognize them.

**Comment by useafterfree** [comment]
hmmm, I have never heard of that, intreresting!

I think 12,1 or 12,2 have native Sandy Bridge support.

Also, this guide is for 10.11.5 and you are on 10.15.4, so not sure how much applies.

P.s. Are you on ES version of the chip? If so, you may not even have MSR capabilities.

**Comment by BrushXue** [comment]
> hmmm, I have never heard of that, intreresting!
> 
> I think 12,1 or 12,2 have native Sandy Bridge support.
> 
> Also, this guide is for 10.11.5 and you are on 10.15.4, so not sure how much applies.
> 
> P.s. Are you on ES version of the chip? If so, you may not even have MSR capabilities.

I don’t think iMac 12,1 or 2 would help. IVB-E is much closer to SNB-E than SNB. Anyway I’ll definitely give it a shot.
Stepping C2 should be OK. The problem must be in BIOS or Clover setup.

**Comment by useafterfree** [comment]
Can you check for `_DSM`: https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/231#issuecomment-247234044

**Comment by BrushXue** [comment]
> Can you check for `_DSM`: [#231 (comment)](https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/231#issuecomment-247234044)

After commenting `_DSM` methods I can boot into the system without kernel panic
but there's no PM at all
```
CPU P-States [ 25 (26) ]
```

**Comment by useafterfree** [comment]
ok, so it looks like your generated `_DSM`s are wrong, so the _PLimit command causes a KP.

The register calls in the kext(s) have to match with what is defined in _DSM ...

Can you toggle generate C / P states in Clover and see if it guess them correctly?

My thoughts are Catalina dropped a lot of CPU support so we have to bring it back by hand.

My thoughts would be to see what legit imac12,1 imac12,2 (SBep or IBep users) are doing to get Catalina working.

Also, checkout dosdude1's Catalina Patcher.

Unfortunately, @Piker-Alpha is out of the game. He would have a lot of insight :) / :(

**Comment by BrushXue** [comment]
Clover C/P states don't work.

I think the CPU is still supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/README.md confirms that single E5-2670 works with Catalina. However when it comes to dual CPU things are different.

Here's my _DSM:
```
        Method (_DSM, 4, NotSerialized)
        {
            If (LEqual (Arg2, Zero))
            {
                Return (Buffer (One)
                {
                    0x03
                })
            }
            Return (Package (0x02)
            {
                "plugin-type",
                One
            })
        }
```

**Comment by useafterfree** [comment]
> I think the CPU is still supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/README.md confirms that single E5-2670 works with Catalina. However when it comes to dual CPU things are different.

This does not mention Catalina at all

**Comment by BrushXue** [comment]
> > I think the CPU is still supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/README.md confirms that single E5-2670 works with Catalina. However when it comes to dual CPU things are different.
> 
> This does not mention Catalina at all

He didn't update the English readme (Last update in 2017). But from the lastest Chinese document it is supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/releases

**Comment by useafterfree** [comment]
> > > I think the CPU is still supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/README.md confirms that single E5-2670 works with Catalina. However when it comes to dual CPU things are different.
> > 
> > 
> > This does not mention Catalina at all
> 
> He didn't update the English readme (Last update in 2017). But from the lastest Chinese document it is supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/releases

I see it now :)

Which mobo do you have?

**Comment by BrushXue** [comment]
> > > > I think the CPU is still supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/blob/master/docs/README.md confirms that single E5-2670 works with Catalina. However when it comes to dual CPU things are different.
> > > 
> > > 
> > > This does not mention Catalina at all
> > 
> > 
> > He didn't update the English readme (Last update in 2017). But from the lastest Chinese document it is supported. https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/releases
> 
> I see it now :)
> 
> Which mobo do you have?

ASRock EP2C602-4L/D16

**Comment by useafterfree** [comment]
> ASRock EP2C602-4L/D16

Are your processors ES (engineering samples)?

**Comment by BrushXue** [comment]
> > ASRock EP2C602-4L/D16
> 
> Are your processors ES (engineering samples)?

Definitely not ES

<img width="586" alt="Screen Shot 2020-04-08 at 9 16 14 PM" src="https://user-images.githubusercontent.com/12702149/78847946-4c6af500-79de-11ea-8901-958dfa8e9884.png">

**Comment by BrushXue** [comment]
Now I suspect that the clover patch from https://www.insanelymac.com/forum/topic/324270-sandy-bridge-e-ivy-bridge-e-power-management-1013-appstore-release/?do=findComment&comment=2698877 no longer works on 10.15.4, which causes the P-limit problem.

**Comment by useafterfree** [comment]
that is my suspicion.

It might be simpler, can you verify you have "no caches" unchecked:
![image](https://user-images.githubusercontent.com/35079898/79201168-80825380-7dec-11ea-88b4-5007b6488e7b.png)

Can you see if your boot does anything different with it checked?

Also, can you make sure you are building a kernel/kext cache?

If I am not mistaken the mechanism of patching kexts operates on the caches, so there may be some clues there.

**Comment by BrushXue** [comment]
No difference. I'm using CPUFriend and I didn't touch S/L/E or L/E so there's shouldn't be kext cache issue.
I noticed this
```
Injected C-States for C000 (C1,C3,C6)
Injected C-States for C001 (C1,C3,C6)
```
should it be C100 instead of C001?

**Comment by useafterfree** [comment]
Not sure about that injection.
Have you invalidated / rebuilt your caches?

**Comment by BrushXue** [comment]
I just installed Mojave(with many existing tutorials). Still getting the same P-limit kernel panic. We know that this motherboard+IVB works and X79+SNB also works, so there might be something wrong with the BIOS. If it can't be fixed by SSDT I'll consider getting Ivy bridge CPUs from eBay.

**Comment by useafterfree** [comment]
> I just installed Mojave(with many existing tutorials). Still getting the same P-limit kernel panic. We know that this motherboard+IVB works and X79+SNB also works, so there might be something wrong with the BIOS. If it can't be fixed by SSDT I'll consider getting Ivy bridge CPUs from eBay.

I just bought 2xE5-2670v2 on Amazon since I just found out one of my 2670's was an ES.


Prices have dropped a ton:

![image](https://user-images.githubusercontent.com/35079898/79295805-7d3fa400-7e8e-11ea-9d01-50afff516468.png)

**Comment by BrushXue** [comment]
Actually I’m interested in 2667 V2 which give the highest single core performance.

**Comment by BrushXue** [comment]
Switch to IVB-E CPUs.
