### ISSUE TITLE
i7-980x  problem！

### ISSUE THREAD

**Issue by thomasbergersen** [Piker-Alpha/ssdtPRGen.sh#521]
Why my CPU only has 2 Turbo States and the maximum state is only 2.11ghz and the minimum state is 1.6ghz？I want to maximum out at 3.46 or 3.60。

System information: Mac OS X 10.15.5 (19F101)
Brandstring: "Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz"

Override value: (-p) processor model, now using: i7-980X!

Version: models.cfg v171 / Haswell.cfg v152

Scope (_PR_) {430 bytes} with ACPI Processor declarations found in DSDT (ACPI 1.0 compliant)
Generating ssdt.dsl for a 'iMacPro1,1' with board-id [Mac-7BA5B2D9E42DDD94]
Intel i7-980X processor [0x206C2] setup [0x0701]
With a maximum TDP of 130 Watt, as specified by Intel
Number logical CPU's: 12 (Core Frequency: 3330 MHz)
Number of Turbo States: 2 (3430-3600 MHz)
Number of P-States: 21 (1600-3600 MHz)
Injected C-States for CPU0 (C1,C3,C6,C7)
Injected C-States for CPU1 (C1,C2,C3)
Warning: 'system-type' may be set improperly (1 instead of 2)
	 - Clover users should read https://clover-wiki.zetam.org/Configuration/ACPI#acpi_smartups
Compiling: ssdt_pr.dsl
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

**Comment by Buli69** [comment]
Hello Thomas
Do you solved the Problem? I have also problems to get nativ powermanagement with OpenCore 0.5.9 and MacOS 10.15.5 on old-timer DesktopPC with ASUS Rampage III Extrem and i7-980X Extreme. Do you have a working SSDT.aml for this particular CPU? Would you please share it to me?

Thanks a lot

Andi

**Comment by thomasbergersen** [comment]
> Hello Thomas
> Do you solved the Problem? I have also problems to get nativ powermanagement with OpenCore 0.5.9 and MacOS 10.15.5 on old-timer DesktopPC with ASUS Rampage III Extrem and i7-980X Extreme. Do you have a working SSDT.aml for this particular CPU? Would you please share it to me?
> 
> Thanks a lot
> 
> Andi


Hello Buli. First of all, X58 platform, I tested that clover and OC could not use intelligent frequency conversion when using native power on relatively new models.

If you need to do in new aircraft above the CPU frequency conversion processing, need your BIOS CPU performance all set to enable, and cooperate with NullCPUPowerManagement kext in clover.

Just set DummyPowerManagement to true in OC. My motherboard is gigard and the power off DSDT is not handled at present.

Below is the Hackintool test w3690 data, 980x I also tested no problem.

AppleIntelInfo.kext v3.0 Copyright © 2012-2017 Pike R. Alpha. All rights reserved.



Settings:
------------------------------------------
enableHWP............................... : 0
logMSRs................................. : 0
logIGPU................................. : 0
logIntelRegs............................ : 0
logCStates.............................. : 1
logIPGStyle............................. : 1
InitialTSC.............................. : 0x4cbd732bd08 (202 MHz)
MWAIT C-States.......................... : 4384

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 133 MHz
Maximum Efficiency Ratio/Frequency...... : 12 (1596 MHz)
Maximum non-Turbo Ratio/Frequency....... : 26 (3458 MHz)
Maximum Turbo Ratio/Frequency........... : 28 (3724 MHz)
P-State ratio * 133 = Frequency in MHz
------------------------------------------
CPU P-States [ 26 ]
CPU P-States [ 25 26 ]
CPU P-States [ 22 25 26 ]
CPU P-States [ 22 23 25 26 ]
CPU P-States [ 16 22 23 25 26 ]
CPU P-States [ 16 18 22 23 25 26 ]
CPU P-States [ 16 18 21 22 23 25 26 ]
CPU P-States [ 16 18 21 22 23 24 25 26 ]
CPU P-States [ 16 18 19 21 22 23 24 25 26 ]
CPU P-States [ 16 17 18 19 21 22 23 24 25 26 ]
CPU P-States [ 16 17 18 19 20 21 22 23 24 25 26 ]
CPU P-States [ 15 16 17 18 19 20 21 22 23 24 25 26 ]

**Comment by Buli69** [comment]
Thanks a lot…

I have to try within the next days...


Andi

**Comment by thomasbergersen** [comment]
OC I have tested the latest, you can achieve intelligent frequency conversion by opening the patch cfg, the following is the place that must be set：

ACPI->Quirks:
FadtEnableReset=True

Kernel->Quirks:
AppleCpuPmCfgLock=True
AppleXcpmCfgLock=True
AppleXcpmExtraMsrs=True

UEFI->Quirks:
IgnoreInvalidFlexRatio=True

**Comment by Buli69** [comment]
Hallo Thomas

This works without having a ssdt generated by ssdtRTGen.sh? Or are this the setting to make work the CPU-SSDT?

Thanks

Andreas

**Comment by thomasbergersen** [comment]
Buli, this is my EFI file https://drive.google.com/file/d/1h-ukfTy3VZExOdV63yUZcFwyZVdvACrX/view?usp=sharing
The files generated by SSdtrtgen.sh are not working at the correct frequency.
Second, it is not recommended to use the counterfeit CPU, there will be unexpected kernel errors
