### ISSUE TITLE
i7-8565U

### ISSUE THREAD

**Issue by alikazemkhanloo** [Piker-Alpha/ssdtPRGen.sh#528]
Hi,
How to use this script for i7-8565U?
It says:
```
Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
```
How to feed this information to the script once I have them?

**Comment by alikazemkhanloo** [comment]
I used`-h` and found the appropriate flags and provided these values, but still the same error

**Comment by tvieira20** [comment]
Any update on this issue?

**Comment by alikazemkhanloo** [comment]
@tvieira20 I used [cpufriend](https://github.com/acidanthera/CPUFriend) and [cpufriendfriend](https://github.com/corpnewt/CPUFriendFriend).I could change some stuff but finally I removed them and let the macos handle it. I'm gonna close this issue as it seems to be a dead repo.
