### ISSUE TITLE
X86PlatformPlugin problems in i5 3210M, using -xcpm and SSDT

### ISSUE THREAD

**Issue by AllanO1iveira** [Piker-Alpha/ssdtPRGen.sh#74]
I use here -xcpm argument, and use the last SSDT script with this command: ./ssdtPRGen.sh -w 3 -x 1
And i get this messages:

Nov  5 17:11:41 Allans-MacBook-Pro kernel[0]: X86PlatformPlugin::setRingTable - AICPM failed to load ring table with status 0x0: Get=0, Load=0, Install=0
Nov  5 17:11:41 Allans-MacBook-Pro kernel[0]: X86PlatformPlugin::configResourceHandler - Failed to set ring table!
Nov  5 17:11:41 Allans-MacBook-Pro kernel[0]: X86PlatformShim::sendPStates - pmCPUControl (XCPMIO_SETPSTATETABLE) returned 0x11
Nov  5 17:11:41 Allans-MacBook-Pro kernel[0]: X86PlatformShim::start - Failed to send PStates
Nov  5 17:11:41 Allans-MacBook-Pro kernel[0]: X86PlatformShim::start - Failed to send stepper

**Comment by SiddRamesh** [comment]
M getting broken Frequency in Intel Power Gadget.
Is it OK :(

And also this !

1/30/15 10:26:07.000 AM kernel[0]: X86PlatformPlugin::setRingTable - AICPM failed to load ring table with status 0x0: Get=0, Load=0, Install=0
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformPlugin::configResourceHandler - Failed to set ring table!
1/30/15 10:26:07.000 AM kernel[0]: IOPPF - Found another boot volume.SuperIODevice: [Fatal] found unsupported chip! ITE sequence ID=0xffff, Winbond sequence ID=0xfc11
1/30/15 10:26:07.000 AM kernel[0]: [AGPM Controller] unknownPlatform
1/30/15 10:26:07.000 AM kernel[0]: IOPPF: AppleIntelCPUPowerManagement mode
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:07.000 AM kernel[0]: X86PlatformShim::sendPStates - Success!
1/30/15 10:26:08.000 AM kernel[0]: X86PlatformShim::sendStepper - Done!

Is Everything OK :(
![screen shot 2015-01-30 at 11 12 01 am](https://cloud.githubusercontent.com/assets/5162770/5987739/b8eaf696-a962-11e4-8f3a-db5dfa5edf05.png)

**Comment by Piker-Alpha** [comment]
I don't think that your issue is related to the topic at hand.Feel free to open a new issues. If you do, then at least add the terminal output of ./ssdtPRGen.sh because I have really no idea what this is about.
