### ISSUE TITLE
14.1 - incorrect low frequency mode look-up table

### ISSUE THREAD

**Issue by open1010** [Piker-Alpha/ssdtPRGen.sh#78]
in 14.1 ssdtPRGen.sh
gServerIvyBridgeCPUList=(
# E3-1200 Xeon Processor Series

'E3-1290 v2',87,1200,3700,4100,4,8
'E3-1280 v2',69,1200,3600,4000,4,8
'E3-1275 v2',77,1200,3500,3900,4,8
'E3-1270 v2',69,1200,3500,3900,4,8
'E3-1265L v2',45,1200,2500,3500,4,8
'E3-1245 v2',77,1200,3400,3800,4,8
'E3-1240 v2',69,1200,3400,3800,4,8
'E3-1230 v2',69,1200,3300,3700,4,8
'E3-1225 v2',77,1200,3200,3600,4,4
'E3-1220 v2',69,1200,3100,3500,4,4
'E3-1220L v2',17,1200,2300,3500,2,4
# E5-1600 Xeon Processor Series

'E5-1620 v2',130,1200,3700,3900,4,8
'E5-1650 v2',130,1200,3500,3900,6,12
'E5-1660 v2',130,1200,3700,4000,6,12
# E5-2600 Xeon Processor Series

'E5-2687W v2',150,1200,3400,4000,8,16
'E5-2658 v2 ',95,1200,2400,3000,10,20
'E5-2648L v2',70,1200,1900,2500,10,20
'E5-2628L v2',70,1200,1900,2400,8,16
'E5-2603 v2',80,1200,1800,1800,4,4
'E5-2637 v2',130,1200,3500,3800,4,8
'E5-2630L v2',60,1200,2400,2800,6,12
'E5-2630 v2',80,1200,2600,3100,6,12
'E5-2620 v2',80,1200,2100,2600,6,12
'E5-2618L v2',50,1200,2000,2000,6,12
'E5-2609 v2',80,1200,2500,2500,4,4
'E5-2697 v2',130,1200,2700,3500,12,24
'E5-2695 v2',115,1200,2400,3200,12,24
'E5-2690 v2',130,1200,3000,3600,10,20
'E5-2680 v2',115,1200,2800,3600,10,20
'E5-2670 v2',115,1200,2500,3300,10,20
'E5-2667 v2',130,1200,3300,4000,6,16
'E5-2660 v2',95,1200,2200,3000,10,20
'E5-2650L v2',70,1200,1700,2100,10,20
'E5-2650 v2',95,1200,2600,3400,8,16
'E5-2643 v2',130,1200,3500,3800,6,12
'E5-2640 v2',95,1200,2000,2500,8,16
)

according to the intel datasheet, in Low Frequency Mode the clock frequency is 1600MHz

intel datasheet : xeon-e3-1200v2-vol-1-datasheet.pdf
page : 17
Table 1 : Intel® Xeon® Processor E3-1200 v2 Product Family SKUs
http://www.intel.com/content/www/us/en/processors/xeon/xeon-e3-1200v2-vol-1-datasheet.html

I think some other desktop CPU's Low Frequency Mode is also incorrectly set

thanks so much

thanks

**Comment by lidas123** [comment]
Hi, can you help me please? I have a computer with asus p9X79 and cpu Xeon E5-2680 v2 i have installed osx sierra and clover everything works but i have the fixed frequency, with Intel Power Gadget Monitor if i put ssdt i have i have the fixed frequency at maximum 2800 without ssdt i have fixed frequency To a minimum 1200
You know how to fix it, thank you
